### ISSUE TITLE
Inland Freight Planning 3 (Planning) - Booking information disappears right after Planning 3

### ISSUE THREAD

**Issue by ivannloyd** [johnpelquingua/freightbit-logistics#236]
Steps to Replicate:
1. Login as admin
2. Click Operations
3. Click Inland freight planning
4. Choose an approved booking and click edit 
5. Choose a Planning 2 item
6. Fill out the fields for Inland Freight Destination

Expected Result:
Booking information should remain on the page 

Actual Result:
Booking information is missing right after saving the details for Inland Freight Destination

Screenshot:
![236](https://cloud.githubusercontent.com/assets/7777788/4247638/c59d80b8-3a5c-11e4-85c0-956805f54391.png)

**Comment by JMXPSX** [comment]
Issue cannot be replicated. Issue already fixed. Please double check

**Comment by barbacenasmc** [comment]
Issue can no longer be replicated.
