### ISSUE TITLE
Booking List: Other columns exceed the boundaries of the table

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#251]
Steps to replicate:
1. Login as admin or customer service representative.
2. Navigate to booking module.

Actual Result: Other columns exceed the boundaries of the table
Expected Result: The columns should automatically adjust to the length of the table

Tested on test environment with the following details:
Browser: Google Chrome Version 27.0.1453.93 
OS: RedHat Linux

![booking](https://cloud.githubusercontent.com/assets/7791554/4659829/8dd68f1a-5511-11e4-9cc0-7576a94aee3d.png)

**Comment by ZaX09** [comment]
Issue cannot be replicated.

**Comment by JMXPSX** [comment]
This could be because of your Red Hat Linux OS and Google Chrome version is no longer updated to the latest version

**Comment by barbacenasmc** [comment]
Issue can no longer be replicated.
