### ISSUE TITLE
Bookings do not show on calendar

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#254]
Steps to replicate:
1. Add a new booking.
2. Go to calendar view on dashboard page.

Actual result: No booking schedule was displayed.
Expected result: Previously added booking should be displayed on the calendar view.

![calendar_20141027](https://cloud.githubusercontent.com/assets/7791554/4786103/a368e3b8-5d8c-11e4-9a6c-a65e86b6c1db.JPG)

**Comment by JMXPSX** [comment]
Isolated case. Some can see the booking while others cannot. Unable to research on the cause of this issue at the moment...

**Comment by barbacenasmc** [comment]
Issue can no longer be replicated.
