### ISSUE TITLE
User can delete customer that is currently associated with a booking

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#259]
Pre-condition:
There should be a booking that exist in the system.
Steps to replicate:
1. Navigate to the customer list page.
2. Delete the customer that was associated with the existing booking in the system.

Actual result: Deletion of booking still succeed. As a result, when the booking list was viewed, the customer column has no more value.
Expected result: Deletion of booking should not succeed. A prompt saying that the selected customer could not be deleted because it is currently associated with 1 or more bookings.

![booking-list_20141027](https://cloud.githubusercontent.com/assets/7791554/4787695/449e3964-5daf-11e4-97fb-617ac48fcacd.JPG)

**Comment by barbacenasmc** [comment]
Customers that have bookings can no longer be deleted but no prompt was displayed to tell the user why does the deletion did not succeed.

**Comment by barbacenasmc** [comment]
Hi Sir @JMXPSX, can you change the prompt color into a less vibrant one?
![image](https://cloud.githubusercontent.com/assets/7791554/6162408/7f8b6796-b2bd-11e4-9e2e-428ba5d7f2ac.png)

**Comment by valienteaidanleary** [comment]
Done fixing the prompt color.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
