### ISSUE TITLE
Freight Planning: Summary displays pre-selected vessel 

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#266]
Pre-condition:
There must be an existing approved booking that is already available for freight planning.
Steps to replicate:
1. Navigate to Freight Plan under Operations.
2. Click Update Status icon on a booking item.
3. On the Sea Operation section, select an existing vendor.
4. Click Search Schedule button to load the list of vessel schedules.

Actual result: The list of vessel schedules were displayed both on Sea Operation section and Summary section of booking details on top.
Expected result: The list of vessel schedules should only be displayed on Sea Operation section since there is no vessel schedule selected yet.

![load-vessel-schedule](https://cloud.githubusercontent.com/assets/7791554/4988083/4e8a5c2e-6998-11e4-9bfa-5338fe51557d.png)

**Comment by JMXPSX** [comment]
it seems you might have clicked on the edit vessel schedule already. The information that appears at the bottom of the booking information was already the vessel schedule chosen already. However on edit, the current schedule will still appear among the list of possible vessel schedules that can be chosen again.

**Comment by barbacenasmc** [comment]
Issue can no longer be replicated.
