### ISSUE TITLE
Freight Planning: User can select a vendor that has different origin and destination ports

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#267]
Pre-condition:
There must be an existing approved booking that is already available for freight planning.

Steps to replicate:
1. Navigate to Freight Plan under Operations.
2. Click Update Status icon on a booking item.
3. On the Sea Operation section, select an existing vendor.
4. Click Search Schedule button to load the list of vessel schedules.

Actual result: User can select a vendor that has different origin and destination ports
Expected result: List of available vendors should be filtered based on the origin and destination port of the current booking.

Origin and destination of current booking:
![booking-port](https://cloud.githubusercontent.com/assets/7791554/4988162/8b1c824c-6999-11e4-81df-ab5270ffdb69.png)

Loaded vessel schedules:
![vessel-schedules](https://cloud.githubusercontent.com/assets/7791554/4988163/8ea2824a-6999-11e4-8fc1-7cd8ba705835.png)

**Comment by JMXPSX** [comment]
This is already resolved. Kindly double check. The possible vessel schedules that can be chosen is now filtered between origin and destination ports, date range and vendor class.

**Comment by barbacenasmc** [comment]
Issue can no longer be replicated.
