### ISSUE TITLE
Freight Planning: Error page was displayed when user clicked Set Vendor button without selecting any item

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#268]
Pre-condition:
There must be an existing approved booking that is already available for freight planning.

Steps to replicate:
1. Navigate to Freight Plan under Operations.
2. Click Update Status icon on a particular booking.
3. At the bottom of the page where items are listed, click Set Vendor button without selecting an item (ticking the checkbox corresponding to it)

Actual result: Error page was displayed saying,
"Error: Server Error
The server encountered an error and could not complete your request.
Please try again in 30 seconds."

Expected result: User should not be able to click Set Vendor button if no item was selected.
![set-vendor](https://cloud.githubusercontent.com/assets/7791554/4988214/d5e17aa2-699a-11e4-9841-222fb1002d96.png)
![set-vendor-with-no-selected-items](https://cloud.githubusercontent.com/assets/7791554/4988215/d75cc576-699a-11e4-8c35-1a78016cd0b4.png)

**Comment by knarceo** [comment]
Already Fixed on next next push :)

**Comment by barbacenasmc** [comment]
Issue fix was verified.
