### ISSUE TITLE
Weight, width, length and height fields on add item allows zero input

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#289]
Steps to replicate:
1. Navigate customer module.
2. View the profile of a particular customer.
3. Click Items to navigate to the list of available customer items.
4. Click Add New Item.
5. Fill-out the form with necessary details. Put zero on the weight, width, length and height fields.
6. Once the details were already complete, click Save.

Actual result: Weight, width, length and height fields allows zero input.

Expected result: Weight, width, length and height fields should not allow zero inputs. Moreover, width, length and height fields are used to compute the volume of the item for bookings with LCL as service requirement. Thus, if two of those fields have positive values but the other one has zero, the outcome of the computation would still be zero because volume = length x width x height.

**Comment by ZaX09** [comment]
done

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
