### ISSUE TITLE
User was allowed to set the same date for pick-up and delivery date for booking with Shipping and Trucking as service requirement

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#290]
Steps to replicate:
1. Navigate to add booking form.
2. Select "Shipping and Trucking" as service requirement.
3. Select same date for pick-up and delivery date.
4. Fill-out the rest of the form with correct details.
5. Click Next.

Actual result: User was allowed to set the same date for pick-up and delivery date for booking with Shipping and Trucking as service requirement. No prompt was displayed to tell that the user has to select a different delivery date.

Expected result: User should not be allowed to set same date for pick-up and delivery for bookings that needs shipping.

![image](https://cloud.githubusercontent.com/assets/7791554/5295333/8f84730a-7bd0-11e4-9e83-83ba9fef7a84.png)

**Comment by JMXPSX** [comment]
Fix on push bd1e1bbb86ab2ac2626489253dce84d3f747f1bf

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
