### ISSUE TITLE
Vessel Schedules List displayed no value in Voyage Number and Vessel Name Attributes

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#292]
**Steps to replicate**
1. Create New Schedule.
2. Fill up all fields.
3. Press Save.
4. Navigate to Vessel Schedules List.

**Actual Result** Voyage number and Vessel name contains no value.

**Expected Result** All values should be displayed in each attribute provided showed in vessel schedule lists.

![vs 31](https://cloud.githubusercontent.com/assets/9795882/5388631/68ed2b98-8129-11e4-990b-42cda0e4ed64.png)

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
