### ISSUE TITLE
Arrival Time can have the same value with Departure Time eventhough they have the same date covered.

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#293]
**Steps to replicate**
1. Select Departure Date and Time.
2. Select Arrival Date same as the Departure Date.
3. Select Arrival Time same as the Departure Time.
4. Fill up the rest of the fields.
5. Press Save.

**Actual Result** Vessel Schedule has been saved.

**Expected Result** Vessel schedule must not be saved. Moreover, it should display that arrival time must be valid.

![item 6](https://cloud.githubusercontent.com/assets/9795882/5388699/a93b6f4c-812a-11e4-97ba-ea4129d5e315.png)

![item 6 1](https://cloud.githubusercontent.com/assets/9795882/5388702/bcf74c54-812a-11e4-8323-7e2d66e4b44e.png)

**Comment by JMXPSX** [comment]
Fix on push 52734732fcfcd6c1e528f066af121261845efec4
Created a validation modal so user cannot proceed when departure and arrival date is on the same date.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
