### ISSUE TITLE
Invalid Time Frame for Arrival Time

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#294]
**Steps to replicate**
1. Select the same Departure Date and Arrival Date.
2. Select Departure Time as 10:00am.
3. Select Arrival Time as 4:00am.
4. Press Save.

**Actual Result** Vessel Schedule has been saved even if the arrival time is earlier than the departure time.

**Expected Result** Vessel schedule must not be saved. Moreover, earlier time than the selected Departure Time should be disabled in Arrival Time.

![item 7](https://cloud.githubusercontent.com/assets/9795882/5388740/887ba1cc-812b-11e4-919a-ebf2dde57510.png)

**Comment by JMXPSX** [comment]
Also fixed on push 52734732fcfcd6c1e528f066af121261845efec4
User can no longer select schedule on the same date which will also fix the time as well

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
