### ISSUE TITLE
Customer/Company code that was displayed in booking number was in lower case

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#311]
Steps to replicate:
1. Navigate to new booking form.
2. Fill-out the form with necessary details.
3. Click Next.

Actual result: Customer/Company code that was displayed in booking number was in lower case
Expected result: Customer/Company code should be in upper case.

Booking number:
![image](https://cloud.githubusercontent.com/assets/7791554/5409218/fb01cad6-8221-11e4-8a08-75db10539114.png)

Actual customer code:
![image](https://cloud.githubusercontent.com/assets/7791554/5409264/cf3891c2-8222-11e4-8028-96ff6c202756.png)

**Comment by valienteaidanleary** [comment]
![asddd](https://cloud.githubusercontent.com/assets/9735872/5894450/38ae1224-a4bc-11e4-925f-dadc0d3215cd.png)

**Comment by barbacenasmc** [comment]
Duplicate issue of #366
