### ISSUE TITLE
Booking information labels and contents are not properly aligned

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#312]
Steps to replicate: 
1. Navigate to new booking page.
2. Fill-out the form with the details needed.
3. Click Next.

Actual result: Booking information labels and contents are not properly aligned
Expected result: Booking information labels and contents should be properly aligned. Moreover, labels should be larger than the content. Contents should also not be all in uppercase as well.

![image](https://cloud.githubusercontent.com/assets/7791554/5409328/c5826e72-8223-11e4-8034-3abaf06b77d1.png)

![image](https://cloud.githubusercontent.com/assets/7791554/5409332/de4748b0-8223-11e4-9e9b-dece73fcdbfc.png)

**Comment by valienteaidanleary** [comment]
![asdasd](https://cloud.githubusercontent.com/assets/9735872/5894360/e1364c5c-a4b9-11e4-9651-6f255990e8c7.png)

**Comment by barbacenasmc** [comment]
Labels and content are not properly aligned due to different font size. Could it be possible to adjust the font size of the content to make it consistent with the label?

**Comment by valienteaidanleary** [comment]
![asd](https://cloud.githubusercontent.com/assets/9735872/6161003/49a34f98-b21f-11e4-9899-2960fe3b1e40.png)

**Comment by barbacenasmc** [comment]
Hi @valienteaidanleary, what I mean here is the horizontal alignment of the labels and contents. As you can see, because the font size of the content is larger than the labels, they are not that much aligned.

**Comment by valienteaidanleary** [comment]
Hi maam @barbacenasmc ganito po ba yung tinutukoy nyo na dapat gawin ? :) 
![asd](https://cloud.githubusercontent.com/assets/9735872/6223880/4342d072-b627-11e4-8838-32f807793d90.png)

**Comment by barbacenasmc** [comment]
Yup, is this already pushed to the repo?

**Comment by valienteaidanleary** [comment]
Done.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
