### ISSUE TITLE
Accumulated volume and weight of booking items on dashboard includes items of unapproved booking

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#314]
Steps to replicate:
1. Add a new booking for LCL.
2. Do not approve the booking.
3. Go to dashboard page.

Actual result: Accumulated volume and weight of booking items on dashboard includes items of the unapproved booking.
Expected result: Accumulated volume and weight of booking items on dashboard should only include items of approved booking

![image](https://cloud.githubusercontent.com/assets/7791554/5430379/3aded8b8-844a-11e4-94b4-070d58cfef56.png)

![image](https://cloud.githubusercontent.com/assets/7791554/5430387/517fd374-844a-11e4-9d13-1ac68989e615.png)

![image](https://cloud.githubusercontent.com/assets/7791554/5430388/59cebd10-844a-11e4-9ce2-df02879a329a.png)

**Comment by johnpelquingua** [comment]
We removed this feature. @barbacenasmc please close thanks!

**Comment by barbacenasmc** [comment]
Closing this issue because the feature has been removed.
