### ISSUE TITLE
"Choose this vessel" link should be an icon

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#317]
For consistency, the link for selecting vessel schedule for freight planning should be an icon/button. 

![image](https://cloud.githubusercontent.com/assets/7791554/5450073/27e8c8a8-853b-11e4-9e0f-d1c984017441.png)

**Comment by knarceo** [comment]
Done.

**Comment by barbacenasmc** [comment]
Issue fix was verified.
