### ISSUE TITLE
Extended Ascii Characters were not Accepted in the Name Fields.

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#318]
**Steps to replicate**
1. Navigate to Booking page.
2. Click Add Contact Person button.
3. Indicate extended ascii characters 128-165 like **Ñ** in namefields.

**Actual Result** Displays validation message indicating "Please match the requested format: Name should not contain special character and/or numbers."

**Expected Result** Extended ascii characters 128-165 should be expected.

![extended ascii characters](https://cloud.githubusercontent.com/assets/9795882/5520412/6f79c47c-89bb-11e4-944e-ff4f51cb3ab6.PNG)

**Comment by ZaX09** [comment]
done

**Comment by barbacenasmc** [comment]
Issue can still be replicated. Please see image below:
![image](https://cloud.githubusercontent.com/assets/7791554/5833222/aad62eb0-a18b-11e4-941c-5d9c403fb6e5.png)

**Comment by ZaX09** [comment]
fixed

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
