### ISSUE TITLE
Phone or Mobile field Accepts No Value

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#319]
**Steps to replicate**
1. Navigate to Booking Page.
2. Click the Add Contact Person/ Add Consignee button.
3. Input alphabetical characters in the phone/mobile field.
4. Press tab.

**Actual Result** Accepts no value for phone/ mobile fields.

**Expected Result** Should have a validation message indicating, "phone/mobile field is required"

![phone mobile](https://cloud.githubusercontent.com/assets/9795882/5520452/d02a626c-89bc-11e4-9023-aa2f8377205a.PNG)

![consignee phone mobile](https://cloud.githubusercontent.com/assets/9795882/5520453/dc1cd3c0-89bc-11e4-83b6-e8e9b65cfb0e.PNG)

**Comment by ZaX09** [comment]
done

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
