### ISSUE TITLE
Invalid Email Format was accepted in Edit Contact Info

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#320]
**Steps to replicate**
1. Navigate to Booking page.
2. Click edit contact info
3. Input invalid email format in email address field.
4. Click Save.

**Actual Result** Update information saved.

**Expected Result** Should have a validation message indicating, "please match the requested format"

![basic info edit](https://cloud.githubusercontent.com/assets/9795882/5520498/11d4404c-89be-11e4-8325-9514152b1a1e.PNG)

**Comment by valienteaidanleary** [comment]
done.

**Comment by barbacenasmc** [comment]
Issue fix was verified.
