### ISSUE TITLE
Special Characters were Accepted in all fields of Add Address.

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#321]
**Steps to replicate**
1. Navigate to Booking Page.
2. Click Add Address.
3. Indicate special characters in all fields.
4. Click Save

**Actual Result** all text fields accept special characters

**Expected Result** Should have a validation message indicating "Please match the requested format: Address Line 1/ Address Line 2/ City/ Region/ Zip  should not contain special characters"

![add address accepts special characters](https://cloud.githubusercontent.com/assets/9795882/5520534/6dc3739a-89bf-11e4-902f-9185b88525de.PNG)

![add address accepts special characters1](https://cloud.githubusercontent.com/assets/9795882/5520535/76a389a0-89bf-11e4-8e30-68100cbb7643.PNG)

**Comment by ZaX09** [comment]
done

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
