### ISSUE TITLE
Required field: Address Type Accepts no Value.

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#322]
**Steps to replicate**
1. Navigate to Booking Page.
2. Click Add Address button.
3. Fill up all required fields except for address type.
4. Click Save.

**Actual Result** Accepts no value for address type.

**Expected Result** Should have a validation message indicating "address type is required."

![no value for address type](https://cloud.githubusercontent.com/assets/9795882/5520589/b8a36f1c-89c1-11e4-8a62-4fe5e555a501.PNG)

**Comment by ZaX09** [comment]
done

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
