### ISSUE TITLE
Wrong Validation Message for Invalid Email Format in Email Address Field.

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#323]
**Steps to replicate**
1. Navigate to Booking page.
2. Click Add contact person/ Add Consignee button.
3. Input invalid email format in email address field.
4. Click save

**Actual Result** Displays validation message indicating "Please enter an email address"

**Expected Result** Should have a validation message indicating, "please match the requested format"

![consignee email](https://cloud.githubusercontent.com/assets/9795882/5520618/ab1562c8-89c2-11e4-9199-8f8a45543b42.PNG)

**Comment by valienteaidanleary** [comment]
done.

**Comment by barbacenasmc** [comment]
Issue fix was verified.
