### ISSUE TITLE
Position Field has No Character Limit

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#324]
**Steps to replicate**
1 Navigate to Booking Page.
2. Click Add Contact Person button.
3. Input infinite amount of characters in position field.

**Actual Result** No character limit

**Expected Result** User should be given maximum amount of input characters in position field.

![position field infinte char](https://cloud.githubusercontent.com/assets/9795882/5520661/52f45282-89c4-11e4-9176-0cabdff3c126.PNG)

**Comment by barbacenasmc** [comment]
Issue fix was verified.
