### ISSUE TITLE
Saved Information were not shown in the list of Contact Person

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#325]
**Steps to replicate**
1. Navigate to Booking Page.
2. Click Add Contact Person.
3. Fill up all fields
4. Click Save.
5. Click drop down menu of contact person.

**Actual Result** Saved information were not shown in the list of contact person.

**Expected Result** Saved information should be listed in drop down menu of contact person.

![add contact person](https://cloud.githubusercontent.com/assets/9795882/5520694/c9446ffc-89c5-11e4-93a5-dd3a4caa8bfc.PNG)

![contact person field](https://cloud.githubusercontent.com/assets/9795882/5520696/d62f07a4-89c5-11e4-8db8-ff664d23393b.PNG)

**Comment by knarceo** [comment]
Done

**Comment by barbacenasmc** [comment]
Issue fix was verified.
