### ISSUE TITLE
Item Information fields have no character limits.

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#326]
**Steps to replicate**
1. Navigate to Booking page.
2. Fill up all fields in page 1.
3. Click Next.
4. Fill up all fields in Item information.
5. Input infinite amount of characters in Rate, Item Name, Commodity, Declared Value fields.

**Actual Result** No character limits

**Expected Result** User should be given a maximum amount of input characters in the field.

![item info no limit](https://cloud.githubusercontent.com/assets/9795882/5520769/8f048046-89c7-11e4-9c25-078d6a065975.PNG)

**Comment by ZaX09** [comment]
done

**Comment by barbacenasmc** [comment]
Comments section still allow unlimited number of characters which results to an error page when trying to add the item to list. Please see image below:
![image](https://cloud.githubusercontent.com/assets/7791554/5832838/fdfe4c90-a185-11e4-9e07-909058ac5638.png)

**Comment by ZaX09** [comment]
done

**Comment by barbacenasmc** [comment]
Hi @ZaX09, kindly set the character limit to 255 instead of 250 to maximize the data storage capacity. Thanks!

**Comment by ZaX09** [comment]
done

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
