### ISSUE TITLE
Required fields in Item Information can be leave as blank.

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#327]
**Steps to replicate**
1. Navigate to Booking Page.
2. Fill up all required fields in the first page.
3. Click Next.
4. Navigate to Item Information section.
5. Input information in Item Quantity, Rate and Commodity fields only.

**Actual Result**  Only Item Quantity, Rate, and Commodity fields are required to have input information, while the rest of the required fields can leave as blank.

**Expected Result** Should have a validation message indicating "fields are required"

![item info 2](https://cloud.githubusercontent.com/assets/9795882/5520816/e5c09e64-89c8-11e4-9fc7-20bce1b4757f.PNG)

**Comment by ZaX09** [comment]
done

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
