### ISSUE TITLE
Invalid Validation Message for Weight/ Volume fields.

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#328]
**Steps to replicate**
1. Navigate to Booking page.
2. Fill up all required fields in page 1.
3. Click Next.
4. Navigate to Item Information.
5. Input invalid set of characters like alphabetical characters in weight / volume field.
6. Press Tab.
7. Click Save.

**Actual Result** Displays a validation message indicating Invalid field value for field "orderItem.weight"

**Expected Result** Should have a proper validation message.

![weight vol](https://cloud.githubusercontent.com/assets/9795882/5520857/08920238-89ca-11e4-87e7-accf0bdb8092.PNG)

**Comment by ZaX09** [comment]
done

**Comment by ZaX09** [comment]
done

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
