### ISSUE TITLE
HTTP Status 500- could not execute statement

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#330]
**Steps to replicate**
1. Navigate to Booking page.
2. Click New Booking button.
3. Fill up all fields.
4. Check all notifications type.
5. Click Next.

**Actual Result** http status 500- could not execute statement

**Expected Result** Should proceed to the next page.

![all notif](https://cloud.githubusercontent.com/assets/9795882/5521130/a2316cb4-89d2-11e4-9835-90248f13b57f.PNG)

![http status 500](https://cloud.githubusercontent.com/assets/9795882/5521131/add52e8e-89d2-11e4-9667-ab7907331d12.PNG)

**Comment by knarceo** [comment]
Fixed on next update of database

**Comment by barbacenasmc** [comment]
Issue can still be replicated as of Jan. 14, 2015 11:28 AM

**Comment by barbacenasmc** [comment]
Hi @knarceo , I would like to follow up for this. Issue can still be replicated on the live site. Any updates? Thanks.
![image](https://cloud.githubusercontent.com/assets/7791554/5832313/602a97e6-a17e-11e4-8b10-cc8bea9a13ee.png)

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
