### ISSUE TITLE
The Summation of Total Rate in the Item List has incorrect Value.

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#331]
**Steps to replicate**
1. Navigate to Booking page.
2. Click the New Booking button.
3. Fill up all required fields.
4. Click Next.
5. Fill up Item Information.
6. Click Add Item to List.
7. Check for the Total Rate of Item List.

**Actual Result** Should display the correct value of the total rate in the item list.

**Expected Result** Total rate has incorrect value.

![total value](https://cloud.githubusercontent.com/assets/9795882/5521561/d45ba0a4-89de-11e4-964a-501589ac050f.PNG)

**Comment by barbacenasmc** [comment]
Issue fix was verified.
