### ISSUE TITLE
Edit Booking: Added items were saved even if changes were not saved

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#332]
Steps to replicate:
1. Create a new booking with 1 item.
2. Approve the newly created booking.
3. Edit the booking and add another item.
4. Do not click Save but rather go to freight plan and view the booking.

Actual result: Added item were saved. The booking already have 2 items.
Expected result: The booking should only have 1 item.

![image](https://cloud.githubusercontent.com/assets/7791554/5626086/4b4f84a8-95c1-11e4-9bf0-02b0adc629d9.png)

![image](https://cloud.githubusercontent.com/assets/7791554/5626101/73f5fcde-95c1-11e4-8236-9a92ece60277.png)

**Comment by valienteaidanleary** [comment]
cannot replicate this issue.

**Comment by barbacenasmc** [comment]
Hi @valienteaidanleary, I was able to replicate the issue on the live site. You might want to check?

**Comment by JMXPSX** [comment]
This is because the "add container" button technically adds the containers into the booking itself. This is a limitation of struts as the input form and the table all show into one view. 

The resolve this, a delete icon was added to remove the unintended container/item that was added into the order however if in the process of cancelling the booking. It will only change the status of the main booking itself to cancelled.

**Comment by barbacenasmc** [comment]
Thus, the "Save Booking" button has no use because initially, when you click "Next" from page 1, the booking was already saved with an "Incomplete" status, then on page 2, once an item/container is added to the list, the booking will then have a "Pending" status. I tried it without clicking the "Save Booking" button and it produced a booking with a "Pending" status like in the image below:
![image](https://cloud.githubusercontent.com/assets/7791554/6183870/b5b8a0b2-b395-11e4-9d6e-5dee48c4471c.png)

With this situation, what could be the best implementation that we should have?

**Comment by barbacenasmc** [comment]
Hi, I just asked our PO to review this issue. And he commented that as an enhancement, the "Save Booking" button should be changed to Preview or View Summary. Then on the summary page, the "Save" button should be changed to "Done".

**Comment by barbacenasmc** [comment]
Hi team, any updates on this?

**Comment by JMXPSX** [comment]
Changed Button names to your suggested labels

**Comment by barbacenasmc** [comment]
Thanks. Enhancements were verified.
