### ISSUE TITLE
Page was not automatically focused on Sea Operation section when clicked Set Vendor

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#333]
Steps to replicate:
1. Go to freight plan and open an ongoing booking.
2. Click Set Vendor (single/multiple items).

Actual result: Page was focused on the "Booking Information" section
Expected result: Page should be automatically focused on Sea Operation section 

![image](https://cloud.githubusercontent.com/assets/7791554/5626199/455c6b40-95c3-11e4-96da-60b5c0c09c37.png)

![image](https://cloud.githubusercontent.com/assets/7791554/5626204/552aec04-95c3-11e4-8d68-759739bd5e38.png)

**Comment by valienteaidanleary** [comment]
done.

**Comment by barbacenasmc** [comment]
Issue can still be replicated.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
