### ISSUE TITLE
Section name for freight plan was "Sea Freight" for bulk setting of vendor

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#334]
Steps to replicate:
1. Go to freight plan and open an ongoing booking with more than 1 items.
2. Click the set vendor icon corresponding to 1 item.

Actual result: Section name for selecting shipping vendor was 'Freight Plan"
![image](https://cloud.githubusercontent.com/assets/7791554/5626237/dd07cd04-95c3-11e4-852e-4989353ff75e.png)

3. Go back to freight items.
4. Check multiple freight items and click "Set Vendor" button.

Actual result: Section name for selecting vendor was "Sea Operation"
![image](https://cloud.githubusercontent.com/assets/7791554/5626240/f49b0f3a-95c3-11e4-86ac-f757d0fd22b1.png)

Expected result: Section name should display "Freight Plan"

**Comment by valienteaidanleary** [comment]
fixed on next push.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
