### ISSUE TITLE
Inappropriate prompt was displayed when tried to search vessel schedule without selecting a shipping vendor

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#335]
Steps to replicate:
1. Go to freight plan and open and ongoing booking.
2. Click Set Vendor for a freight item.
3. Click Search Schedule without selecting a vendor.

Actual result: A prompt saying "Vessel Schedule loaded!" was displayed.
Expected result: "Vessel Schedule loaded!" should no longer be displayed or the Search Schedule button should be disabled instead if no vendor was selected.

![image](https://cloud.githubusercontent.com/assets/7791554/5626457/90acc830-95c6-11e4-82a1-e3f05e1f5630.png)

**Comment by valienteaidanleary** [comment]
done.

**Comment by barbacenasmc** [comment]
Issue can still be replicated. Please see image below:
![image](https://cloud.githubusercontent.com/assets/7791554/5813796/693bca6e-a0be-11e4-9fe1-f4b2cf097807.png)

**Comment by valienteaidanleary** [comment]
maam tatanggalin po ba yung prompt na yun ? kase ginawa ko pong required
yung sa vendor para di sya mag sesearch pag walang laman yung sa dropdown.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
