### ISSUE TITLE
No icon displayed for delete on the legends section

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#336]
Steps to replicate:
1. Navigate to user accounts list under accounts module.

Actual result: No icon displayed for delete on the legends section
Expected result: There should be an icon corresponding to "Delete"
![image](https://cloud.githubusercontent.com/assets/7791554/5626986/aaf61348-95cd-11e4-8686-7ca524dc4f2c.png)

**Comment by valienteaidanleary** [comment]
fixed.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
