### ISSUE TITLE
Prompt for indicating success of user deletion was not in proper letter case

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#337]
Steps to replicate:
1. Navigate to user accounts list under accounts module.
2. Delete an existing user account.

Actual result: Prompt for indicating success of user deletion was "Success! A User has been Deleted."
Expected result: Prompt should display "Success! User account has been deleted."

![image](https://cloud.githubusercontent.com/assets/7791554/5627044/4a79d2ce-95ce-11e4-8166-0cecff04f6bf.png)

**Comment by valienteaidanleary** [comment]
fixed on next push.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
