### ISSUE TITLE
Create Booking: Edit contact form has no indication of required fields

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#338]
Steps to replicate:
1. Go to create booking page.
2. Click Edit Contact Info button.

Actual result: Edit contact form has no indication of required fields.
Expected result: Phone, mobile and email address fields should have asterisks(*).

![image](https://cloud.githubusercontent.com/assets/7791554/5734763/1b4806fa-9bf6-11e4-85ae-8c66ba1ed8c4.png)

**Comment by valienteaidanleary** [comment]
done.

**Comment by barbacenasmc** [comment]
Issue can still be replicated. Please see image below:
![image](https://cloud.githubusercontent.com/assets/7791554/5813759/d9f11954-a0bd-11e4-95a1-8784cafe496b.png)

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
