### ISSUE TITLE
Create Booking: Edit contact form has no placeholders to indicate standard format

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#339]
Steps to replicate:
1. Go to create booking page.
2. Click Edit Contact Info button.
3. Clear the values of all fields.

Actual result: There were no placeholders to indicate standard format.
Expected result: There should be placeholders to indicate standard format just like the new customer page.

Actual edit contact form:
![image](https://cloud.githubusercontent.com/assets/7791554/5734814/d40dc224-9bf6-11e4-840f-f65aadc355f0.png)

New customer form:
![image](https://cloud.githubusercontent.com/assets/7791554/5734840/35ee9ee6-9bf7-11e4-862a-3583a000fade.png)

**Comment by valienteaidanleary** [comment]
done.

**Comment by barbacenasmc** [comment]
Issue can still be replicated. Please see image below:
![image](https://cloud.githubusercontent.com/assets/7791554/5813755/b8ba00f2-a0bd-11e4-95d0-3bb1c76dd262.png)

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
