### ISSUE TITLE
Create Booking: Delivery date was automatically filled-out with selected date on pick-up date

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#340]
Steps to replicate:
1. Navigate to create booking page.
2. On the booking information section, select a pick-up date.

Actual result: Delivery date was automatically filled-out with selected date on pick-up date
Expected result: Delivery date should remain blank until the user selects a date.

![image](https://cloud.githubusercontent.com/assets/7791554/5751979/a20ca19e-9ca7-11e4-983f-e63456fa10fe.png)

**Comment by valienteaidanleary** [comment]
done.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
