### ISSUE TITLE
Create Booking: All fields were not cleared from their value after changing freight type

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#341]
Steps to replicate:
1. Navigate to create booking form.
2. Fill-out the form with necessary details.
3. Change the freight type.

Actual result: The form was cleared except for payment mode, customer contact details, notification checkboxes, comments and contact person.
Expected result: All fields should be cleared from their value

![image](https://cloud.githubusercontent.com/assets/7791554/5753364/e65ceed8-9cc2-11e4-84ae-48390d9b88e6.png)
![image](https://cloud.githubusercontent.com/assets/7791554/5753375/0ad14e8a-9cc3-11e4-944e-f36a0839b2c3.png)

**Comment by valienteaidanleary** [comment]
done.

**Comment by barbacenasmc** [comment]
All other fields were cleared except for checkbox. Please see image below:
![image](https://cloud.githubusercontent.com/assets/7791554/5813733/45d34198-a0bd-11e4-9fd6-b81d7c0aa482.png)

**Comment by JMXPSX** [comment]
Fix on push f8cd0bba4ac1ca9a2edf379744b23c57596e4d6e

Certain fields need not to reset as it will might be a hassle to the user that all fields wil reset when the customer is changed instead fields that only reset are the ones associated to the Customer chosen at the beginning of the new booking page.

**Comment by barbacenasmc** [comment]
Hi Sir @JMXPSX, the last thing we need to close this issue is to see that the notification types are unchecked once the freight type is changed. I guess this can be possible because the notification checkboxes can already behave that way when you change the customer.

**Comment by valienteaidanleary** [comment]
hi maam all checkboxes now are unchecked when the freight type changed.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
