### ISSUE TITLE
Create Booking: Error page was displayed when user entered more than 255 characters on comment

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#342]
Steps to replicate:
1. Navigate to create booking form.
2. Fill-out the form with necessary details. Use more than 255 characters on comment text area.
3. Click Next button.

Actual result: An error page was displayed saying "Data truncation: Data too long for column 'comments' at row 1"
Expected result: The text area for comment should only allow 255 characters to avoid displaying the error message.

![image](https://cloud.githubusercontent.com/assets/7791554/5753152/1e8beb64-9cbf-11e4-8b8f-1c06283db1ca.png)

**Comment by valienteaidanleary** [comment]
done.

**Comment by barbacenasmc** [comment]
Issue fix was already verified. Comment box now only allows 255 characters.
