### ISSUE TITLE
Create Booking: Layout of order details summary became disarranged after using 255 characters on comments

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#343]
Steps to replicate:
1. Navigate to create booking page.
2. Fill-out the form with necessary details. Use 255 characters on text area for comments.
3. Click Next button.

Actual Results: Layout of order details summary became disarranged
Expected Results: Order details summary should maintain a proper layout when maximum number characters were displayed on any field.

Actual Layout:
![image](https://cloud.githubusercontent.com/assets/7791554/5753476/1513603e-9cc5-11e4-90cf-ccb022f5ba6b.png)

Standard Layout:
![image](https://cloud.githubusercontent.com/assets/7791554/5753487/367beffc-9cc5-11e4-8cfc-381669eadcb3.png)

**Comment by valienteaidanleary** [comment]
Done.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
