### ISSUE TITLE
Create Booking: Label of first name on add consignee form was not capitalized

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#344]
Steps to replicate:
1. Navigate to create booking form.
2. Click "Add Consignee" button at the "Consignee Information" section.
3. Observe the label for first name field.

Actual result: Label displayed was "First name"
Expected result: Label for first name should be "First Name" to be consistent with the rest of the fields.

![image](https://cloud.githubusercontent.com/assets/7791554/5754282/5dadd278-9cd1-11e4-9809-67a75966b641.png)

**Comment by valienteaidanleary** [comment]
done.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
