### ISSUE TITLE
Create Booking: Addition of address still succeeded even if no address type was selected

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#345]
Steps to replicate:
1. Navigate to Create Booking form.
2. Select a customer.
3. Click Add Address button on the Customer Information section.
4. Fill-out the form but skip selecting an address type.
5. Click Save.

Actual result: Addition of address still succeeded
Expected result: Addition of address should not succeed and a validation message indicating that address type should be specified should display

![image](https://cloud.githubusercontent.com/assets/7791554/5771998/83832602-9d84-11e4-9163-bc3a46564d21.png)

![image](https://cloud.githubusercontent.com/assets/7791554/5771999/930f3bd8-9d84-11e4-9efb-7af079ad5878.png)

**Comment by valienteaidanleary** [comment]
Done.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
