### ISSUE TITLE
Create Booking: Validation message was displayed on Edit Contact form even if fax number field is optional

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#347]
Steps to replicate:
1. Navigate to Create Booking form.
2. Fill-out the select a customer.
3. Click Edit Contact Info button.
4. Clear the fax number field is there's any value.
5. Click Save.

Actual result: Attempt to save changes did not succeed and a validation message was displayed on the fax number field saying "Please fill out this field."
Expected result: No validation message should display because fax number field is optional

![image](https://cloud.githubusercontent.com/assets/7791554/5772303/5c35099c-9d8b-11e4-92bf-4f79642d75cf.png)

**Comment by valienteaidanleary** [comment]
Done.

**Comment by barbacenasmc** [comment]
Hi @valienteaidanleary, this issue can still be replicated. Kindly see image below.
![image](https://cloud.githubusercontent.com/assets/7791554/5812689/b7e4a74e-a0aa-11e4-9af1-6fa2648550de.png)

**Comment by valienteaidanleary** [comment]
done fixing po maam sa edit booking ko pala nailagay.

**Comment by barbacenasmc** [comment]
Alright, thanks @valienteaidanleary.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
