### ISSUE TITLE
Create Booking: User was able to save incomplete phone number thru Edit Contact form

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#348]
Steps to replicate:
1. Navigate to Create Booking form.
2. Select a customer.
3. Click "Edit Contact Info" button.
4. Change the phone number into 6 digit number only.
5. Click Save.

Actual result: Attempt to save incomplete number succeeded.
Expected result: Save should not succeed and a validation message indicating that input on phone number field is invalid.

![image](https://cloud.githubusercontent.com/assets/7791554/5772511/c6dc3cd6-9d8e-11e4-9324-cf73dfdfd01c.png)

**Comment by valienteaidanleary** [comment]
Done.

**Comment by barbacenasmc** [comment]
Hi @valienteaidanleary, this issue can still be replicated. Kindly see image below.
![image](https://cloud.githubusercontent.com/assets/7791554/5812661/34d191aa-a0aa-11e4-82a9-86e16783a46e.png)

**Comment by barbacenasmc** [comment]
Field input was already validated. However, validation message should indicate the required number of digits instead of the format since the field masking already corrects it for the user.

**Comment by valienteaidanleary** [comment]
done fixing.

**Comment by barbacenasmc** [comment]
Issue fix as already verified.
