### ISSUE TITLE
Create Booking: User was able to save incomplete mobile number thru Edit Contact form

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#349]
Steps to replicate:
1. Navigate to Create Booking form.
2. Select a customer.
3. Click "Edit Contact Info" button.
4. Change the mobile number into 6 digit number only.
5. Click Save.

Actual result: Attempt to save incomplete number succeeded.
Expected result: Save should not succeed and a validation message indicating that input on mobile number field is invalid.

![image](https://cloud.githubusercontent.com/assets/7791554/5772525/10cf74c0-9d8f-11e4-82e4-5e2d43d04f45.png)

**Comment by valienteaidanleary** [comment]
Done.

**Comment by barbacenasmc** [comment]
Hi @valienteaidanleary, this issue can still be replicated. Kindly see image below.
![image](https://cloud.githubusercontent.com/assets/7791554/5812644/d7b721e2-a0a9-11e4-9c06-cda92769c395.png)

**Comment by barbacenasmc** [comment]
Field input was already validated. However, validation message should indicate the required number of digits instead of the format since the field masking already corrects it for the user.

**Comment by valienteaidanleary** [comment]
done fixing.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
