### ISSUE TITLE
Create Booking: Edit contact form accepts invalid email inputs

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#350]
Steps to replicate:
1. Navigate to Create Booking form.
2. Select a customer.
3. Click "Edit Contact Info" button.
4. Enter invalid inputs on email like the following:

Abc.example.com
A@b@c@example.com 
a"b(c)d,e:f;g<h>i[j\k]l@example.com
just"not"right@example.com
this is"not\allowed@example.com
this\ still\"not\\allowed@example.com 
john..doe@example.com
john.doe@example..com

5. Click Save.

Actual result: Update still succeeded.
Expected result: Update should not succeed but a validation message indicating that input was invalid on email address field should display.

![image](https://cloud.githubusercontent.com/assets/7791554/5772610/34c9f354-9d90-11e4-9435-d24af87e830d.png)

![image](https://cloud.githubusercontent.com/assets/7791554/5772624/5cf439d4-9d90-11e4-88ff-50e29af68cb0.png)

![image](https://cloud.githubusercontent.com/assets/7791554/5772629/76a101d2-9d90-11e4-999a-8026fd1584ba.png)

![image](https://cloud.githubusercontent.com/assets/7791554/5772639/8ebaa2c8-9d90-11e4-90b3-446075cdf82f.png)

![image](https://cloud.githubusercontent.com/assets/7791554/5772642/a56dfe16-9d90-11e4-8462-db94dbe753f6.png)

![image](https://cloud.githubusercontent.com/assets/7791554/5772653/c885b81c-9d90-11e4-8283-a5262964a286.png)

![image](https://cloud.githubusercontent.com/assets/7791554/5772716/096f5a8a-9d92-11e4-982c-f4d9027efef0.png)

![image](https://cloud.githubusercontent.com/assets/7791554/5772725/25ddfc80-9d92-11e4-94a3-1b62cadca390.png)

**Comment by ZaX09** [comment]
![issue 350](https://cloud.githubusercontent.com/assets/9165543/5829988/ba66bade-a154-11e4-865b-133683041af3.jpg)

issue is resolved in the updated system

**Comment by barbacenasmc** [comment]
Issue fix was already verified.

**Comment by barbacenasmc** [comment]
Validation message still did not indicate the requested format. Please see image below:
![image](https://cloud.githubusercontent.com/assets/7791554/5870222/5a52fe72-a303-11e4-8df9-df5c1ae7d279.png)

**Comment by valienteaidanleary** [comment]
Done fixing.

**Comment by barbacenasmc** [comment]
Kindly use example@domain.com for specified format sample.

**Comment by valienteaidanleary** [comment]
Done.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
