### ISSUE TITLE
Create Booking: User was able to save incomplete fax number thru Edit Contact form

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#351]
Steps to replicate:
1. Navigate to Create Booking form.
2. Select a customer.
3. Click "Edit Contact Info" button.
4. Change the fax number into 6 digit number only.
5. Click Save.

Actual result: Attempt to save incomplete number succeeded.
Expected result: Save should not succeed and a validation message indicating that input on fax number field is invalid.

![image](https://cloud.githubusercontent.com/assets/7791554/5773283/4dd2a5de-9d9b-11e4-9e4f-16b5284a111d.png)

**Comment by valienteaidanleary** [comment]
done

**Comment by barbacenasmc** [comment]
Hi @valienteaidanleary, this issue can still be replicated. Kindly see image below.
![image](https://cloud.githubusercontent.com/assets/7791554/5812622/77dbd0ce-a0a9-11e4-9655-34f3dd5e849d.png)

**Comment by barbacenasmc** [comment]
Field input was already validated. However, validation message should indicate the required number of digits instead of the format since the field masking already corrects it for the user.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
