### ISSUE TITLE
Create Booking: Add new contact did not succeed when used an existing contact last name

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#352]
Steps to replicate:
1. Navigate to Create Booking form.
2. Select a customer.
3. Click "Add Contact" button on Customer Information section.
4. Fill-out the form and use a last name that was already used by another contact person.
5. Click Save.

Actual result: Add contact form was closed but new contact was not added to the corresponding dropdown list. Try to click the Add Contact button again and a validation message on the last name field was displayed saying "Contact already exists".

Expected result: Add new contact form should accept last names that were already used by another contact person.

![image](https://cloud.githubusercontent.com/assets/7791554/5773484/1e8d46a0-9d9e-11e4-869b-5b7d2d9bc734.png)

**Comment by valienteaidanleary** [comment]
Done.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.

**Comment by barbacenasmc** [comment]
Issue can be replicated again in as of today, Jan. 26, 2015. Please see image below:
![image](https://cloud.githubusercontent.com/assets/7791554/5895789/23771ace-a564-11e4-89dc-6a9d32b812ef.png)

**Comment by JMXPSX** [comment]
Can add contact person even with the same last name

**Comment by JMXPSX** [comment]
Fix on push b22e9f2fa4c9ea96f2b1143c8c5aa21290c9b730

**Comment by barbacenasmc** [comment]
Issue can still be replicated. Please see image below.
![image](https://cloud.githubusercontent.com/assets/7791554/6160456/1a4e1640-b29e-11e4-86b2-b6374265474e.png)

**Comment by barbacenasmc** [comment]
Changed label to medium because it becomes a blocker issue.

**Comment by barbacenasmc** [comment]
Issue can no longer be replicated.
