### ISSUE TITLE
Create Booking: Incorrect contact person for consignee was displayed on dropdown list

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#353]
Steps to replicate:
1. Navigate to create booking form.
2. Select a customer.
3. Observe the contact person field for consignee.

Actual result: Incorrect contact person was displayed. Checked on customer module and found out that it was different.
Expected result: Contact person field should display the correct contact person of the selected consignee.

![image](https://cloud.githubusercontent.com/assets/7791554/5813225/ff30513e-a0b4-11e4-8a05-4b3ba52b21f1.png)

![image](https://cloud.githubusercontent.com/assets/7791554/5813228/12d0be72-a0b5-11e4-861e-110acd60a973.png)

**Comment by ZaX09** [comment]
[Contact Person] list under [Consignee Information] can be found by navigating through Customer-View Customer Profile-Consignee-View Consignee Information.

![353_1](https://cloud.githubusercontent.com/assets/9165543/5830365/5b6c7d9c-a15a-11e4-9cc3-c482becc81bc.jpg)
![353_3](https://cloud.githubusercontent.com/assets/9165543/5830366/5b992158-a15a-11e4-8778-e28f8d446675.jpg)

**Comment by barbacenasmc** [comment]
Yup, I actually looked on the same page. I checked the database yesterday and seems like Create Booking page pulls out contact person with "Shipper" contactType instead of "C CONTACT."

**Comment by barbacenasmc** [comment]
Hi team, I would like to follow up for this issue. This might affect the user to create a booking due to incorrect details that were pulled out by the form.

**Comment by barbacenasmc** [comment]
Changed status to high because one of the major functionalities of the system is impaired unless this issue is fixed.

**Comment by JMXPSX** [comment]
Fixed on push fb938b8c3fda4f6850f8c52ce408228c0aa522a2

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
