### ISSUE TITLE
Add Consignee: Cannot add new consignee due to a validation that appears on zip code

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#354]
Steps to replicate:
1. Navigate to customer module.
2. View the information of an existing customer.
3. Go to consignee list.
4. Click "New Consignee" button.
5. Fill-out the form with correct details.
6. Click Save.

Actual results: Could not proceed with saving consignee details. A validation message appears saying , "Please match the requested format, ZIP should not contain special characters and/or letters."
Expected result: Validation message should not appear because specified ZIP format was met.

![image](https://cloud.githubusercontent.com/assets/7791554/5830672/ed690806-a15e-11e4-8c95-ad54a4965432.png)

**Comment by ZaX09** [comment]
done

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
