### ISSUE TITLE
Error page was displayed when tried to view consignee list of a customer

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#355]
Steps to replicate:
1. Navigate to customer module.
2. View customer profile of Walmart.
3. Click Consignee sub menu.

Actual result: Error page was displayed.
Expected result: List of consignees should display.

Note: This might be related with issue no. 354. When I checked the database, the difference of Walmart from other customer is that it has a consignee that has a contact type "C CONTACT" compare to others that have "Shipper"

![apache tomcat 7 0 57 - error report](https://cloud.githubusercontent.com/assets/7791554/5831904/d8b185b0-a176-11e4-9ccf-90f4515e1018.png)

**Comment by knarceo** [comment]
Fixed on next update of database...........................hopefully :)

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
