### ISSUE TITLE
Freight Plan: Breadcrumb and "Back" button displays "Freight Plan: Items" on bulk setting of vessel schedule for FCL

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#357]
Steps to replicate:
1. Navigate to freight plan and open and ongoing booking with FCL as service requirement.
2. Check the freight items and click "Set Vessel Schedule" button.

Actual results: Breadcrumb and "Back" button displays "Freight Plan: Items"
Expected results: Breadcrumb and "Back" button should display "Freight Plan: Containers"
![image](https://cloud.githubusercontent.com/assets/7791554/5832272/308a1b98-a17d-11e4-9f8d-85e3226fcc9a.png)

**Comment by barbacenasmc** [comment]
Same thing also happens when clicked Edit Vessel Schedule.

**Comment by valienteaidanleary** [comment]
Done.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
