### ISSUE TITLE
Create Booking: Add address form accepts spaces on required fields

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#358]
Steps to replicate:
1. Navigate to booking module.
2. Click New Booking.
3. Select a customer.
4. Click "Add Address" button beside the pick-up address field.
5. Enter spaces on all required fields.
6. Click Save.

Actual result: Addition of new customer address still succeeded.
Expected result: Addition of new address should not succeed.A validation message should display on the first required field that it should be filled-out

![image](https://cloud.githubusercontent.com/assets/7791554/5895619/bbf6bf0c-a55f-11e4-965b-b8d5f48d836a.png)

**Comment by valienteaidanleary** [comment]
Done.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
