### ISSUE TITLE
Create booking: Error page was displayed when used spaces on required fields of Add Contact form

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#359]
Steps to replicate:
1. Navigate to booking module.
2. Click New Booking.
3. Select a customer.
4. Click the "Add Contact" button beside the contact person field.
5. Enter spaces on required fields. Fill-out the required fields with masking like phone number field.
6. Click Save.

Actual result: An error page was displayed with a message "not-null property references a null or transient value : com.sr.biz.freightbit.common.entity.Contacts.client"

Expected result: Addition of new address should not succeed. A validation message should display on the first required field that it should be filled-out

![image](https://cloud.githubusercontent.com/assets/7791554/5895653/ceecd0b4-a560-11e4-87d3-e3e424428049.png)

![image](https://cloud.githubusercontent.com/assets/7791554/5895656/d24e8f7c-a560-11e4-804e-71ac1c3f28fd.png)

**Comment by valienteaidanleary** [comment]
Done.

**Comment by valienteaidanleary** [comment]
Done.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
