### ISSUE TITLE
Add Contact Form: Position field accepts more than 45 characters which results to an error page

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#360]
Steps to replicate:
1. Navigate to booking module.
2. Click "New Booking" button.
3. Select a customer.
4. Click "Add Contact" button beside the Contact Person field.
5. Enter more than 45 characters on the position field.
6. Fill-out the rest of the form correctly.
7. Click "Save" button.

Actual results: Position field accepts more than 45 characters which results to an error page after clicking Save. 

Expected result: Position field should only allow 45 characters in maximum based on the database.

![image](https://cloud.githubusercontent.com/assets/7791554/5895828/5a6de12e-a565-11e4-8adb-b4619391d9f5.png)

![image](https://cloud.githubusercontent.com/assets/7791554/5895825/45c2f552-a565-11e4-8cdf-b64ca0eb5c07.png)

**Comment by valienteaidanleary** [comment]
Done.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
