### ISSUE TITLE
Add Contact Form: Last name field accepts more than 30 characters which results to an error page

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#361]
Steps to replicate:
1. Navigate to booking module.
2. Click "New Booking" button.
3. Select a customer.
4. Click "Add Contact" button beside the Contact Person field.
5. Enter more than 30 characters on the last name field.
6. Fill-out the rest of the form correctly.
7. Click "Save" button.

Actual results: Last name field accepts more than 30 characters which results to an error page after clicking Save.

Expected result: Last name field should only allow 30 characters in maximum based on the database.

![image](https://cloud.githubusercontent.com/assets/7791554/5895849/aa72f16e-a565-11e4-9beb-a4090d16ae32.png)

![image](https://cloud.githubusercontent.com/assets/7791554/5895869/e2daf84e-a565-11e4-9f81-65d4b1af88fe.png)

**Comment by valienteaidanleary** [comment]
Done.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
