### ISSUE TITLE
Add Contact Form: First name field accepts more than 30 characters which results to an error page

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#362]
Steps to replicate:
1. Navigate to booking module.
2. Click "New Booking" button.
3. Select a customer.
4. Click "Add Contact" button beside the Contact Person field.
5. Enter more than 30 characters on the first name field.
6. Fill-out the rest of the form correctly.
7. Click "Save" button.

![image](https://cloud.githubusercontent.com/assets/7791554/5895905/8c37b58a-a566-11e4-8aa5-e10886f5c21e.png)

![image](https://cloud.githubusercontent.com/assets/7791554/5895903/7a31e3d8-a566-11e4-83f3-5e102abc31ef.png)

**Comment by valienteaidanleary** [comment]
Done.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
