### ISSUE TITLE
Add Contact Form: Middle name field accepts more than 30 characters which results to an error page

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#363]
Steps to replicate:
1. Navigate to booking module.
2. Click "New Booking" button.
3. Select a customer.
4. Click "Add Contact" button beside the Contact Person field.
5. Enter more than 30 characters on the middle name field.
6. Fill-out the rest of the form correctly.
7. Click "Save" button.

![image](https://cloud.githubusercontent.com/assets/7791554/5896006/8aaba2d8-a568-11e4-8d71-b4cb26178ffe.png)

![image](https://cloud.githubusercontent.com/assets/7791554/5896026/cf78d778-a568-11e4-9d04-75f9f8953ba8.png)

**Comment by valienteaidanleary** [comment]
Done.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
