### ISSUE TITLE
Add Contact Form: Email field accepts more than 50 characters which results to an error page

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#364]
Steps to replicate:
1. Navigate to booking module.
2. Click "New Booking" button.
3. Select a customer.
4. Click "Add Contact" button beside the Contact Person field.
5. Enter more than 50 characters on the email field.
6. Fill-out the rest of the form correctly.
7. Click "Save" button.

![image](https://cloud.githubusercontent.com/assets/7791554/5896057/5d39bf28-a569-11e4-8250-8dd85a31eec7.png)

![image](https://cloud.githubusercontent.com/assets/7791554/5896063/7ba9cf52-a569-11e4-8bf2-e3de0ddb167f.png)

**Comment by valienteaidanleary** [comment]
Done.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
