### ISSUE TITLE
Add Customer Item: Validation message was displayed on weight field even if input was valid

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#365]
Steps to replicate:
1. Navigate to customer module.
2. View the profile of an existing customer.
3. Go to items.
4. Add a new item. Fill-out the form correctly.
5. Click Save.

Actual result: Addition of new customer item could not succeed. A validation message on the weight field was displayed saying, "Please match the requested format. XXXX.XX or enter an integer greater than 0.

Expected result: Addition of new customer item should succeed.

![add-item](https://cloud.githubusercontent.com/assets/7791554/5913168/50969384-a61a-11e4-9df5-5adabc9e5e39.png)

**Comment by valienteaidanleary** [comment]
Done.

**Comment by ierroljohn** [comment]
Issue fix was already verified. but issue can be replicated now in the length field. [Feb. 2, 2015]
![1](https://cloud.githubusercontent.com/assets/9795903/5996428/78562e56-aae4-11e4-9c91-9b9ceb17fe21.png)

**Comment by valienteaidanleary** [comment]
Done.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
