### ISSUE TITLE
Add Booking: Letters on booking number was displayed in lowercase when entered lowercase letters on add customer page

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#366]
Steps to replicate:
1. Create a new customer. Enter the customer code in lowercase (notice that it automatically becomes uppercase when entered on the field.
2. Go to Create Booking form.
3. Fill-out the form and select the previously created customer.
4. Click Next.

Actual result: On the summary of booking information on the 2nd page, letters on booking number was displayed in lowercase.

Expected result: All letters on booking number should be in uppercase.

![image](https://cloud.githubusercontent.com/assets/7791554/5913248/8b184c22-a61b-11e4-93b0-9ab3b66c85a2.png)

**Comment by JMXPSX** [comment]
Issue cannot be replicated

**Comment by barbacenasmc** [comment]
Issue can no longer be replicated.
