### ISSUE TITLE
Accounts: User: Incomplete Lists of User Type

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#368]
**Steps to replicate**
1. Navigate to User Accounts.
2. Create New User.
3. Click the drop down list  of User Type.

**Actual Result**
- The dropdown list does not include:
   - Customer
   - Sales Officer

**Expected Result**
- The dropdown list for User Type should display the following:
   - System Administrator
   - Customer
   - Customer Relations Officer
   - Freight Operations Officer
   - Freight Documentations Specialist
   - Freight Operations Specialist
   - Freight Operations Manager
   - Inland Freight Officer
   - Sales Officer

![screen shot 2015-01-27 at 1 18 03 pm](https://cloud.githubusercontent.com/assets/9795882/5913929/5b48341a-a627-11e4-8562-ee43874d66ac.png)

**Comment by barbacenasmc** [comment]
Issue can no longer be replicated.
