### ISSUE TITLE
Accounts: User: No Role Restrictions for User Type.

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#369]
**Steps to replicate**
1. Navigate to User Accounts.
2. Create New User.
3. Select User Type as Customer Relations Department.
4. Select a Role in Permission Panel as Admin System.
5. Click Save.

**Actual Result**
- User Type has no restrictions in each role assigned.
- A new user has been added

**Expected Result**
- Account should not be successfully created.
- Each User Type has its own Respective Role:
   - Admin - All Roles
   - Customer - Customer
   - Customer Relations Department - Customer Relations
   - Freight Operations Officer - Sea Freight
   - Freight Operations Specialist - Inland Freight
   - Freight Operations Manager - Sea and Inland Freight
   - Freight Documents Specialist - Document Specialist
   - Inland Freight Officer - Inland Freight
   - Sales Officer - Sales

![screen shot 2015-01-27 at 1 36 02 pm](https://cloud.githubusercontent.com/assets/9795882/5914095/fe561d96-a629-11e4-939d-6ca8076eb25f.png)

![screen shot 2015-01-27 at 1 36 52 pm](https://cloud.githubusercontent.com/assets/9795882/5914102/342c80c2-a62a-11e4-93cd-f1a7042a8855.png)

**Comment by barbacenasmc** [comment]
Issue is no longer valid due to new implementation.
