### ISSUE TITLE
User Accounts: Misleading Validation Messages.

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#370]
**Steps to replicate**
1. Navigate to User Accounts.
2. Create New user.
3. Fill up all fields.
4. Include spaces for the input in User Name field.
   *User name:* Xenon XXX
5. Click Save.

**Actual Result**
It displays a validation message indicating "Please match the requested format: Username must have minimum 4 characters"

**Expected Result**
Account should be successfully created.

![screen shot 2015-01-27 at 1 53 49 pm](https://cloud.githubusercontent.com/assets/9795882/5914173/f843c8a2-a62b-11e4-9d6b-37c223da6dc4.png)

**Comment by valienteaidanleary** [comment]
Done.

**Comment by ierroljohn** [comment]
Issue can still be replicated as of February 2, 2015

This issue is caused by the 'whitespace' between words in the User Name, Adding user will succeed if username only has 1 world else, error message will be shown.
![3](https://cloud.githubusercontent.com/assets/9795903/5997392/a25157ba-aaf5-11e4-9000-5b06a7ebbefb.png)

**Comment by valienteaidanleary** [comment]
Done.

**Comment by barbacenasmc** [comment]
Hi @valienteaidanleary , I would like to ask how was this issue solved? When I used username with space in between, creation of user account succeeded.

**Comment by ZaX09** [comment]
Fixed: username may only contain alphanumeric input excluding whitespace. min 3, max 25

**Comment by barbacenasmc** [comment]
Hi @ZaX09, I tried to use "shielamarie" but the validation message still displays.

**Comment by ZaX09** [comment]
fixed

**Comment by valienteaidanleary** [comment]
username can now only accept underscores,dash,alphanumeric.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
