### ISSUE TITLE
User Accounts: Missing Permission Panel

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#371]
**Steps to Replicate**
1. Navigate to User Accounts.
2. Create New User.
3.. Fill up all fields.
4. Enter User Name that is already existing.
5.  Click Save.

**Actual Result**
- It displays a validation message indicating that username already exists.
- Permission panel was not  properly loaded.

**Expected Result**
It should display a validation message indicating  that username already exists. Moreover, same user Interface should be displayed.

![screen shot 2015-01-27 at 2 09 03 pm](https://cloud.githubusercontent.com/assets/9795882/5914304/253db6b8-a62e-11e4-866e-a5ddd1f7a4f6.png)

![screen shot 2015-01-27 at 2 01 40 pm](https://cloud.githubusercontent.com/assets/9795882/5914263/6fe4a9b6-a62d-11e4-9779-b858cbb06fb2.png)

**Comment by barbacenasmc** [comment]
Duplicate issue of #248
