### ISSUE TITLE
Edit User Accounts: Error page was displayed after saving

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#372]
**Steps to replicate**
1. Navigate to User Account Page.
2. Select User.
3. Click the Edit Icon.
4. Navigate to Edit User Page.
5. Click Save.

**Actual Result**
The server encountered an internal error that prevented it from fulfilling this request.

**Expected Result**
User information should be successfully updated.

![screen shot 2015-01-27 at 2 14 53 pm](https://cloud.githubusercontent.com/assets/9795882/5914338/f1ae8ff6-a62e-11e4-9baf-8c1c912cf18c.png)

![apache tomcat 7 0 57 error report](https://cloud.githubusercontent.com/assets/9795882/5933580/9322a704-a6fd-11e4-8927-4e9d418641cc.png)

**Comment by JMXPSX** [comment]
Cannot replicate error as Leary

**Comment by ierroljohn** [comment]
Cannot replicate this issue

**Comment by barbacenasmc** [comment]
Hi, I checked this on live site and resulted to customized error page. 
![image](https://cloud.githubusercontent.com/assets/7791554/6036270/6222ec60-ac7d-11e4-8798-f1b07f536f6b.png)

**Comment by barbacenasmc** [comment]
Issue can still be replicated. 
![error 500 null](https://cloud.githubusercontent.com/assets/7791554/6206311/033b6b84-b5c2-11e4-9c86-2e964c0cc958.png)

**Comment by barbacenasmc** [comment]
Issue can still be replicated.

**Comment by JMXPSX** [comment]
known issue

**Comment by barbacenasmc** [comment]
Hi team, any update on this?

**Comment by knarceo** [comment]
Fixed on next push.

**Comment by Leirum** [comment]
Issue fix was already verified.
