### ISSUE TITLE
Group Accounts: HTTP Status 500 - could not execute statement

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#373]
**Steps to replicate**
1. Navigate to Group Account.
2. Navigate to Add Group Page.
3. Input Value in Code Field exceeding by 3 characters
4 Click Save

**Actual Result**
- Infinite number of characters can be input by the user in each field provided in Add Group Panel
- The server encountered an internal error that prevented it from fulfilling this request.

**Expected Result**
Since the group can only accepts limited characters for the code, code field should only provide up to 3 characters.

![screen shot 2015-01-27 at 3 00 40 pm](https://cloud.githubusercontent.com/assets/9795882/5914702/561b2b4c-a635-11e4-8673-03d452c5e06f.png)

![screen shot 2015-01-27 at 3 05 36 pm](https://cloud.githubusercontent.com/assets/9795882/5914809/fd2644f2-a636-11e4-82b7-0f9f3bb13b54.png)

**Comment by valienteaidanleary** [comment]
Done.

**Comment by barbacenasmc** [comment]
Issue can still be replicated.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
