### ISSUE TITLE
Color for bookings with "Incomplete" status is incorrect

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#374]
Steps to replicate:
1. Navigate to booking module.
2. Create a new booking.
3. Once done with the 1st page of the form, click the Booking List link on the breadcrumb.

Actual result: Color for booking with "Incomplete" status is red
Expected result: Color for booking with "Incomplete" status should be orange.

![image](https://cloud.githubusercontent.com/assets/7791554/5914400/fb835af6-a62f-11e4-99fb-47e5a0f6d789.png)

**Comment by Leirum** [comment]
Issue fix was verified
