### ISSUE TITLE
Group Account: Page Navigation Fails

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#375]
**Steps to replicate**
1. Navigate to Group Account.
2. Navigate to New Group Page.
3. Navigate to Last Page in Users Panel

**Actual Result**
The page navigates back to the log in page.

**Expected Result**
The page should proceed to the last page of the Users panel.

![screen shot 2015-01-27 at 3 55 21 pm](https://cloud.githubusercontent.com/assets/9795882/5915209/cddd3faa-a63d-11e4-9864-7338f7f9f27d.png)

![screen shot 2015-01-27 at 3 55 39 pm](https://cloud.githubusercontent.com/assets/9795882/5915214/d82802ba-a63d-11e4-835e-e8a36532d282.png)

**Comment by valienteaidanleary** [comment]
Done.

**Comment by Leirum** [comment]
Issue fix was already verified as of today, February 3, 2015.
