### ISSUE TITLE
Add User Accounts: Name Fields Accept Special Characters

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#376]
**Steps to replicate**
1. Navigate to User Accounts.
2. Create New User.
3. Input special characters in the name fields. (First Name/ Last Name/ User Name)
4. Click Save.

**Actual Result**
- Navigate into a new page display all the saved information of the new user.
- Displays a validation message indicating ""Success! A New User has been added""

**Expected Result**
- Registration of account should not be succeeded
- It should navigate back to the registration page when Save button has been clicked by the user.
- It should display a validation message indicating that the name field does not accepts special characters.

![screen shot 2015-01-27 at 4 21 44 pm](https://cloud.githubusercontent.com/assets/9795882/5915424/b5d020e6-a640-11e4-9a06-1a22319b0a23.png)

![screen shot 2015-01-27 at 4 22 03 pm](https://cloud.githubusercontent.com/assets/9795882/5915470/1d5b81ec-a641-11e4-97ca-0fce05afcea5.png)

**Comment by valienteaidanleary** [comment]
Done.

**Comment by ierroljohn** [comment]
Issue fix was already verified as of today February 2, 2015
