### ISSUE TITLE
Add Booking: Success message for adding new item was in color red

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#377]
Steps to replicate:
1. Create a new booking with LCL as service requirement.
2. On step 2 page, click "Add New Item" button.
3. Fill-out the form with correct details, then click Save.

Actual result: Success message for adding new item was in color red
Expected result: Success message for adding new item should be in color green.

![add-item-success](https://cloud.githubusercontent.com/assets/7791554/5915516/a34bf796-a641-11e4-8189-91f5c8f0990c.png)

**Comment by JMXPSX** [comment]
Fix on 09a89827bea620bbe0ec6bbd5f5a3a577ba9b1c4

**Comment by barbacenasmc** [comment]
Issue fix was already verified.

**Comment by barbacenasmc** [comment]
Issue can be replicated again. Both in adding container or item to list.
![image](https://cloud.githubusercontent.com/assets/7791554/6181336/623a4450-b36c-11e4-9110-35111ebd1d2a.png)
