### ISSUE TITLE
Add Booking: Booking was still created even if Cancel button was clicked on step 1

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#378]
Steps to replicate:
1. Navigate to add booking page.
2. Fill-out the form with necessary details.
3. Click Cancel button.
4. Click Yes to confirm.

Actual result: Booking was still created with an "Incomplete" status
Expected result: Booking should not be created.

![image](https://cloud.githubusercontent.com/assets/7791554/5915892/f47b163e-a645-11e4-873d-7aa50b7ef543.png)

**Comment by JMXPSX** [comment]
Fix on 09a89827bea620bbe0ec6bbd5f5a3a577ba9b1c4

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
