### ISSUE TITLE
Cancel button is in color grey on Edit Booking page

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#379]
Steps to replicate:
1. Navigate to booking module.
2. Click Edit icon on an existing booking.
3. Observe the Cancel button at the bottom of the page.

Actual result: Cancel button is in color grey.
Expected result: Cancel button should be in color red.

![image](https://cloud.githubusercontent.com/assets/7791554/5916010/1a7e69e8-a647-11e4-9d0e-17c8d9f71b19.png)

**Comment by JMXPSX** [comment]
Fix on 09a89827bea620bbe0ec6bbd5f5a3a577ba9b1c4

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
