### ISSUE TITLE
Add Group Account: White Spaces Were Accepted as Valid Value

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#380]
**Steps to replicate**
1. Navigate to Group Account.
2. Navigate to New Group Page.
3. Input white spaces in all fields of Add Group Panel
4. Click Save.

**Actual Result**
Group was successfully added

**Expected Result**
- Save button should not be disabled.
- White spaces should be considered as null value.
- It should display a validation message indicating "Please fill out this field"

![screen shot 2015-01-27 at 5 32 51 pm](https://cloud.githubusercontent.com/assets/9795882/5916308/d6551a38-a64a-11e4-8ea7-52d50ca3d814.png)

![screen shot 2015-01-27 at 5 34 34 pm](https://cloud.githubusercontent.com/assets/9795882/5916366/519f3282-a64b-11e4-967f-59afb6b61c1f.png)

**Comment by valienteaidanleary** [comment]
Done.

**Comment by ierroljohn** [comment]
Issue fix was already verified as of today February 2, 2015
but issue arise after the fix because now Group Name that contains white space in between words are being blocked see this --> #398
