### ISSUE TITLE
Edit Booking: A number "27" was displayed in between Yes and No button on cancel confirmation message

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#381]
Steps to replicate:
1. Navigate to booking list.
2. Click Edit icon on an existing booking
3. On the editable form of the booking, click Cancel button.

Actual result: A number "27" was displayed in between Yes and No button oncancel confirmation message
Expected result: There should be no number to display in between Yes and No button

![image](https://cloud.githubusercontent.com/assets/7791554/5931388/4fcb19fc-a6d8-11e4-99f2-503d487aa1c1.png)

**Comment by jjsarmiento** [comment]
cannot replicate error.

**Comment by JMXPSX** [comment]
This is already fixed

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
