### ISSUE TITLE
IFO Dispatch Plan: Invalid Icon Access in the Action Panel

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#382]
**Steps to replicate**
1. Log in as Inland Freight Officer.
2. Navigate to Operations --> Dispatch Plan.
3. Observe the Action Panel in Dispatch Plan List Frame.

**Actual Result**
Set Vendor Icon was enabled in the Action Panel of Dispatch Plan List with Incomplete Status.

**Expected Result**
- Set Vendor in the Action Panel of Dispatch Plan List with Incomplete Status should be disabled.
- Only the viewing of booking information should be enabled for the Dispatch Plan with Incomplete Status

![screen shot 2015-01-28 at 10 16 55 am](https://cloud.githubusercontent.com/assets/9795882/5931364/e1a4f060-a6d7-11e4-9cb2-3635c227a93a.png)

**Comment by knarceo** [comment]
Wrong reference, sorry.

**Comment by johnpelquingua** [comment]
Hi @barbacenasmc @knarceo any updates on this? Thanks!

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
