### ISSUE TITLE
Edit Booking: Booking was deleted when clicked and confirmed Cancel on page 1 or 2

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#383]
**Steps to replicate:**
1. Navigate to booking module.
2. Click Edit icon on an existing booking.
3. On the editable form of booking, click Cancel button.
4. Click Yes to confirm.

**Actual result:** Booking was deleted from the list.
**Expected result:** 
- Page should return to the booking list if from page 1
- Page should return to page 1 if from page 2

![image](https://cloud.githubusercontent.com/assets/7791554/5931666/8c5d2f6a-a6db-11e4-937b-de949572ad76.png)

**Comment by JMXPSX** [comment]
Cancel now reverts back the user to the Booking list for Add and Edit Booking. Delete can only be done on the booking list view only.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
