### ISSUE TITLE
Dispatch Plan: Page displays Freight Plan page after adding new vendor

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#384]
**Steps to replicate**
1. Log in as Admin / Inland Freight Officer
2. Navigate to Operations --> Dispatch Plan
3. Select an item in the Dispatch Plan List.
4. Click the Set Vendor Icon in the Action Panel.
5. Select Vendor
6. Click the Edit Vendor button.
7. Navigate to Dispatch Plan: Origin
8. Click the Add Vendor/ Add Driver/ Add Truck button.
9. Fill up all fields.
10. Click Save.

**Actual Result**
After hitting the save button, it navigates to Freight Plan page.

**Expected Result**
- Add frame should be closed and navigates back to the Dispatch Plan page.
- Saved information should be added into the dropdown list of vendor/ driver/ truck code.

![screen shot 2015-01-28 at 11 53 15 am](https://cloud.githubusercontent.com/assets/9795882/5932266/30fd83ae-a6e5-11e4-9e05-b1e991dbeeaa.png)

![screen shot 2015-01-28 at 11 55 08 am](https://cloud.githubusercontent.com/assets/9795882/5932437/79d8d7e2-a6e8-11e4-85c4-6a3dbf99c5d8.png)

**Comment by knarceo** [comment]
I don't know for IFO but for admin, this issue was fixed on next push.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
