### ISSUE TITLE
IFO Dispatch Plan: The page navigates to Freight Plan: Containers After Hitting the Edit Vendor button without selecting any item

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#387]
**Steps to replicate**
1. Log in as Inland Freight Officer.
2. Navigate to Operations --> Dispatch Plan
3. Select an Item in the Dispatch Plan: List
4. Click the Set Vendor Icon.
5. Navigate to Dispatch Plan: Items.
6. Click the Edit Vendor button without selecting any vendor.

**Actual Result**
The page navigates to Freight Plan: Containers.

**Expected Result**
- It should display a validation message indicating "Please select a vendor"
- The page should stay on Dispatch Plan: Items.

![screen shot 2015-01-28 at 1 23 43 pm](https://cloud.githubusercontent.com/assets/9795882/5932966/da540056-a6f2-11e4-9cb2-217a6e78c1b7.png)

![screen shot 2015-01-28 at 1 23 55 pm](https://cloud.githubusercontent.com/assets/9795882/5932974/16d63198-a6f3-11e4-9c04-34d3779b18d5.png)

**Comment by knarceo** [comment]
I don't know for IFO but for admin, this issue was fixed on next push.

**Comment by johnpelquingua** [comment]
Hi @barbacenasmc any updates on this?

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
