### ISSUE TITLE
Customer: Unresponsive Design in Medium Size Browser

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#388]
**Steps to replicate**
1. Log in as Admin
2. Navigate to Customer Module.
3. Resize the browser into medium.

**Actual Result**
The design doesn't respond upon the medium size of browser.

**Expected Result**
- Design responsiveness should be based upon the size of browser of the user.

![unresponsive design](https://cloud.githubusercontent.com/assets/9795882/5953511/d1c2d7ea-a7c5-11e4-8952-789cc5831806.png)

**Comment by johnpelquingua** [comment]
What is the size of this viewport?

**Comment by Leirum** [comment]
size is 768 x 1280.

**Comment by egmsantos** [comment]
Bug fixed. Changed table class = "table-responsive table responsive-scroll list-table".

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
