### ISSUE TITLE
Add Customer: Data too long for column 'customerName' at row 1

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#389]
**Steps to replicate**
1. Log in as Admin
2. Navigate to Customer Module
3. Click the New User button.
4. Input 51 characters in the Company Name/ Customer Name field.
5. Fill out the rest of the fields.

**Actual Result**
- No character limit for user input
- Data truncation: Data too long for column 'customerName' at row 1

**Expected Result**
- Input should be automatically disabled, once the user reached the limit of 50 characters for the given field.

![too long cname](https://cloud.githubusercontent.com/assets/9795882/5953694/7800d0e2-a7c8-11e4-965c-3c6019e89300.png)

![a](https://cloud.githubusercontent.com/assets/9795882/5953842/26a37414-a7ca-11e4-9d68-4cd210fe2b43.png)

**Comment by ZaX09** [comment]
done

**Comment by ierroljohn** [comment]
issue can still be replicated as of today February 2, 2015

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
