### ISSUE TITLE
Add Customer: Required Field: Company Code Accepts White Spaces

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#390]
**Steps to replicate**
1. Log in as Admin
2. Navigate to Customer Module
3. Click the New Customer button.
4. Input white spaces in Company Name/ Customer Name field.
5. Fill out the rest of the fields.
6. Click Save.

**Actual Result**
- Save button was enabled.
- The page navigates to customer module.
- It displayed a validation message indicating ""Success! New Customer has been added""
- Saved information with white spaces value in the field of Company code has been listed in the Customer List.

**Expected Result**
- Save button should not be enabled.
- White spaces should be considered as null value

![c code white spaces](https://cloud.githubusercontent.com/assets/9795882/5954007/8a569aa2-a7cc-11e4-85a1-4d06fd9c7572.png)

![c code](https://cloud.githubusercontent.com/assets/9795882/5954023/ca96c060-a7cc-11e4-815f-0edb2a118bf0.png)

![null value c code](https://cloud.githubusercontent.com/assets/9795882/5954161/a7eaf822-a7ce-11e4-8eba-f4989340c232.png)

**Comment by valienteaidanleary** [comment]
done.

**Comment by barbacenasmc** [comment]
Issue can still be replicated on create customer form.

**Comment by valienteaidanleary** [comment]
done.

**Comment by valienteaidanleary** [comment]
done.

**Comment by ierroljohn** [comment]
Issue fix was already verified as of today February 2, 2015
but because of the fix Company Name with white space now considered invalid #397
