### ISSUE TITLE
Add Customer: Value in Website Field should be well-formed

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#391]
**Steps to replicate**
1. Log in as Admin
2. Navigate to Customer Module
3. Click the New Customer button.
4. Input plaintext in Website field.
5. Fill out the rest of the field.
6. Click Save.

**Actual Result**
New Customer has been successfully added.

**Expected Result**
- Website must be well-formed.
- It should display a validation message for the proper format of value in the website field.

![website plaintext](https://cloud.githubusercontent.com/assets/9795882/5954104/00fb7a5a-a7ce-11e4-8600-4e31837d2c40.png)

![website](https://cloud.githubusercontent.com/assets/9795882/5954110/0add666e-a7ce-11e4-99c9-6ae2469e8504.png)

**Comment by valienteaidanleary** [comment]
done.

**Comment by barbacenasmc** [comment]
Issue can still be replicated:
![image](https://cloud.githubusercontent.com/assets/7791554/5973423/08d4de62-a8a3-11e4-838c-a0eff744829b.png)

**Comment by valienteaidanleary** [comment]
done.

**Comment by ierroljohn** [comment]
Issue fix was already verified as of today February 2, 2015.
