### ISSUE TITLE
Add Customer: Data too long for column 'signatureCard' at row1

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#392]
**Steps to replicate**
1. Log in as Admin
2. Navigate to Customer Module
3. Click the New Customer button.
4. Input 31 characters in Customer Information Sheet Number.
5. Fill out the rest of the field.
6. Click Save.

**Actual Result**
- HTTP Status 500 - could not execute statement
- Data truncation: Data too long for column 'signatureCard' at row1

**Expected Result**
Input should be automatically disabled, once the user reached the limit of 30 characters for the given field.

![cisn1](https://cloud.githubusercontent.com/assets/9795882/5954331/f2f33bb6-a7d0-11e4-82c3-3afe683b7996.png)

![cisn2](https://cloud.githubusercontent.com/assets/9795882/5954295/7b7e44a4-a7d0-11e4-850e-fc81c44e9ebb.png)

**Comment by ZaX09** [comment]
done

**Comment by barbacenasmc** [comment]
Issue can still be replicated:
![image](https://cloud.githubusercontent.com/assets/7791554/5973279/644b7de8-a8a1-11e4-9fa1-548c924a9648.png)
![image](https://cloud.githubusercontent.com/assets/7791554/5973291/7d938c14-a8a1-11e4-865e-82cb85f6c937.png)

**Comment by Leirum** [comment]
issue fix was already verified as of today February 3, 2015
