### ISSUE TITLE
Add & Edit Customer: Data too long for column 'aaf' at row 1

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#393]
**Steps to replicate**
*Add Customer*
1. Log in as Admin
2. Navigate to Customer Module
3. Click the New Customer button
4. Input 31 characters in Account Application Form Number field.
5. Fill out the rest of the field.
6. Click Save.

or

*Edit Customer*
1. Log in as Admin
2. Navigate to customer Module
3. Click the Edit icon in the Action Panel of any customer.
4. Input 31 characters in Account Application Form Number field.
5. Fill out the rest of the field.
6. Click Save.

**Actual Result**
*Add Customer*
- HTTP Status 500 - could not execute statement
- Data truncation: Data too long for column 'aaf' at row 1

*Edit Customer*
- HTTP Status 500 - could not execute statement; SQL [n/a]; nested exception is org.hibernate.exception.DataException: could not execute statement
- Data truncation: Data too long for column 'aaf' at row 1

**Expected Result**
Input should be automatically disabled, once the user reached the limit of 30 characters for the given field.

![41 1](https://cloud.githubusercontent.com/assets/9795882/5954750/8ca40d1c-a7d6-11e4-9bc3-017c6e03162b.png)
![41 2](https://cloud.githubusercontent.com/assets/9795882/5954751/8ce2c138-a7d6-11e4-9c33-690c4c028f38.png)

![79 1](https://cloud.githubusercontent.com/assets/9795882/5955050/9206f5dc-a7d9-11e4-85d6-4b3dc0640c61.png)

**Comment by valienteaidanleary** [comment]
done.

**Comment by barbacenasmc** [comment]
Issue can still be replicated.
![image](https://cloud.githubusercontent.com/assets/7791554/5973183/4c99487a-a8a0-11e4-9160-0f25f8793ffc.png)
![image](https://cloud.githubusercontent.com/assets/7791554/5973183/4c99487a-a8a0-11e4-9160-0f25f8793ffc.png)

**Comment by barbacenasmc** [comment]
-Issue fix was already verified on edit form.
-Issue can still be replicated on create form.

**Comment by valienteaidanleary** [comment]
done.

**Comment by ierroljohn** [comment]
Issue fix was already verified as of today February 2, 2015

**Comment by ierroljohn** [comment]
Issue fix was already verified as of today February 2, 2015
