### ISSUE TITLE
Edit Customer: Company Name Field Accepts White Spaces as Valid Value

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#394]
**Steps to replicate**
1. Log in as Admin
2. Navigate to Customer Module
3. Click the Edit icon in the Action Panel of any customer.
4. Delete the Value in the field of Company Name/ Customer Name.
5. Input white spaces in the field of Company Name/ Customer Name.
6. Click Save.

**Actual Result**
- The page navigates to Customer module --> Customer Profile
- It displays validation message indicating ""Success! Customer has been updated"".
-  There is a null value in Company Name/ Customer Name.

**Expected Result**
- White spaces should be considered as a null value
- It should display a validation message indicating "Please fill out this field"

![46 1](https://cloud.githubusercontent.com/assets/9795882/5954866/18a2b754-a7d8-11e4-9c51-ae4f9b5a6f77.png)

![46 2](https://cloud.githubusercontent.com/assets/9795882/5954867/18a5969a-a7d8-11e4-9071-8327336e4508.png)

**Comment by valienteaidanleary** [comment]
done.

**Comment by barbacenasmc** [comment]
Validation message is incorrect. It should be "Company/Customer name is required"

![image](https://cloud.githubusercontent.com/assets/7791554/5973109/6856ffcc-a89f-11e4-8de4-add4543611c9.png)

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
