### ISSUE TITLE
Edit Customer: Void Validation Message for Company Code

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#395]
**Steps to replicate**
1. Log in as Admin
2. Navigate to Customer Module
3. Click the Edit icon in the Action Panel of any customer.
4. Change the value of the Company Code into an existing one.
5. Click Save

**Actual Result**
- Invalid validation message.
- Displays a label indicating err.customerCode.already.exist

**Expected Result**
- Customer profile should not be successfully updated.
- It should display a validation message indicating "Customer already exists."

![50](https://cloud.githubusercontent.com/assets/9795882/5955350/026bd5ba-a7dd-11e4-9c28-8379ed37c084.png)

**Comment by valienteaidanleary** [comment]
Done.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
