### ISSUE TITLE
Add Customer: Inappropriate validation message was displayed when used spaces on company name

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#396]
**Steps to replicate:**
1. Navigate to add customer form.
2. Use spaces on company name field.
3. Fill-out the rest of the required fields.
4. Click Save.

Actual result: Inappropriate validation message was displayed
Expected result: A validation message saying "Please match requested format" should display.

![image](https://cloud.githubusercontent.com/assets/7791554/5973803/7f0c4d82-a8a7-11e4-827f-298c5c872917.png)

**Comment by valienteaidanleary** [comment]
done.

**Comment by Leirum** [comment]
Issue fix was already verified as of today, February 3, 2015.
