### ISSUE TITLE
Add Customer: Required Field: Company Name not accepting Name with white space in between words

### ISSUE THREAD

**Issue by ierroljohn** [johnpelquingua/freightbit-logistics#397]
**Steps to Replicate**

1. Log in as Admin
2. Navigate to Customer Module
3. Click the New Customer button.
4. Input a Company Name in Company Name/ Customer Name field with white spaces in between words e.g. 'Sample Company Name'
5. Fill out the rest of the fields.
6. Click Save.

**Actual Results**

- Adding of Customer not succeeded even if the user input a valid Company Name with white space in between
- If the user only input a one word company name, adding will succeed not Company Name with more than one word
- A validation message was displayed saying "Please match the requested format"

**Expected Result**

- Adding of costumer should succeed
- Customer name with white space in between words should be accepted and considered valid Name

![2](https://cloud.githubusercontent.com/assets/9795903/5996801/3d9ab71c-aaeb-11e4-8361-bbe08f5b698f.png)

**Comment by valienteaidanleary** [comment]
Done.

**Comment by Leirum** [comment]
Issue fix was already verified
