### ISSUE TITLE
Add Group Account:  Name field not accepting 'Name' with white space in between words

### ISSUE THREAD

**Issue by ierroljohn** [johnpelquingua/freightbit-logistics#398]
**Steps to replicate**
1. Navigate to Group Account.
2. Navigate to New Group Page.
3. Input a group name with white space in between e.g. 'Group Name Sample'
4. Click Save.

**Actual Result**
- Adding of group account not succeeded
- Group name with white space in between words not accepted
- A validation message was displayed saying "please match the requested field"

**Expected Result**
- Saving should be successful because the value is correct
- No validation message should be displayed

![4](https://cloud.githubusercontent.com/assets/9795903/5997684/d3f3baca-aaf9-11e4-8d99-e217437bd502.png)

**Comment by valienteaidanleary** [comment]
Done.

**Comment by Leirum** [comment]
Issue fix was already verified as of today, February 3, 2015.
