### ISSUE TITLE
User can still set vessel schedule/vendor on cancelled bookings

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#400]
Pre-condition:
There must be an existing cancelled booking.

Steps to replicate:
1. Navigate to freight plan/dispatch plan.
2. Observe the action icons available for a booking with "CANCELLED" status.

Actual result: Set vessel schedule/vendor icon is still available
Expected result: There should be no available icon for setting vessel schedule or vendor.

![image](https://cloud.githubusercontent.com/assets/7791554/6034123/0c351e90-ac5a-11e4-89a6-0a91476e341c.png)

![image](https://cloud.githubusercontent.com/assets/7791554/6034157/624290f6-ac5a-11e4-9312-0ab485ce96a0.png)

**Comment by valienteaidanleary** [comment]
fixed on next push.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
