### ISSUE TITLE
Add Customer: Validation message was displayed on website field even if input was valid

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#401]
Steps to replicate:
1. Navigate to "Add Customer" page.
2. Fill-out the form with correct inputs.
3. Click "Save".

Actual Result: Validation message was displayed on website field even if input was valid. 
Expected Result: Addition of new customer should succeed.

![image](https://cloud.githubusercontent.com/assets/7791554/6034617/d54fd5e0-ac5f-11e4-8411-1196413e1db9.png)

**Comment by valienteaidanleary** [comment]
unable to add www. validation. website should still allow entry without the need to append www. at the beginning -- Jojo

**Comment by barbacenasmc** [comment]
Hi @valienteaidanleary, would it be alright if you remove the format validation instead?

**Comment by valienteaidanleary** [comment]
pag tinanggal po yung format validation pwede po mag add ng pure
whitespaces at special characters si user ok lang po ba yun ?

**Comment by valienteaidanleary** [comment]
fixed on next push. user can now add website with this format "www.example.com and example.com"

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
