### ISSUE TITLE
Create Booking: Edit item form does not display item name

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#402]
Steps to replicate:
1. Create a new booking with LCL as service mode.
2. On page 2, add 1 item.
3. Click the edit icon corresponding to the added item.

Actual result: Name field does not display the item name.
Expected result: Name field should display the item name.

![image](https://cloud.githubusercontent.com/assets/7791554/6036053/a7b357fa-ac79-11e4-98be-2a2573f44031.png)
![image](https://cloud.githubusercontent.com/assets/7791554/6036060/c82f2b44-ac79-11e4-9e39-ef78295161fd.png)

**Comment by valienteaidanleary** [comment]
done fixed by sir.jo.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
