### ISSUE TITLE
Booking number was not updated when customer number was changed

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#403]
Steps to replicate:
1. Create a new booking.
2. Go to customer module and change the customer number.
3. Go back to booking page and view the previously created booking.

Actual result: Booking number was not updated 
Expected result: Booking number should be updated

![image](https://cloud.githubusercontent.com/assets/7791554/6036213/9218ea60-ac7c-11e4-9c0f-08d530f258ea.png)

![image](https://cloud.githubusercontent.com/assets/7791554/6036206/830cdee6-ac7c-11e4-9e1a-dc1513737ca1.png)

**Comment by JMXPSX** [comment]
Fix on push # ac1be34897f6fad600f787cae4e7add1605b84ec

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
