### ISSUE TITLE
Create/Edit Booking: Notification type label has no asterisk symbol even if it is required

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#404]
Steps to replicate:
1. Navigate to create or edit booking page.
2. Observe the notification type label.

Actual result: Notification type label has no asterisk symbol
Expected result: Notification type label should have an asterisk symbol

![image](https://cloud.githubusercontent.com/assets/7791554/6037059/ff546d5e-ac89-11e4-9d8d-ec2e418f60cb.png)

**Comment by valienteaidanleary** [comment]
done.

**Comment by barbacenasmc** [comment]
Hi @valienteaidanleary , I think, the fix was only applied on edit booking form but not yet on the create booking form. 

On create - 
![image](https://cloud.githubusercontent.com/assets/7791554/6054143/8a13bcc0-ad24-11e4-9b03-2e77fc34e1f5.png)

On edit - 
![image](https://cloud.githubusercontent.com/assets/7791554/6054144/97e2f83e-ad24-11e4-989d-7c1c57664d3b.png)

**Comment by valienteaidanleary** [comment]
Done fixed on next push.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
