### ISSUE TITLE
Vessel schedules were not deleted after deleting a shipping vendor

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#405]
Pre-condition:
-There should be an existing shipping vendor with a vessel schedule
Steps to replicate:
1. Delete the shipping vendor.
2. Go to vessel schedule list.

Actual result: The vessel schedule that belongs to the previously selected vendor was still on the list.
Expected result: The vessel schedule should be automatically deleted. Then, the freight plan and dispatch plan will also display an error page. Please see below:

![image](https://cloud.githubusercontent.com/assets/7791554/6037600/972b16ae-ac90-11e4-849c-0886f81ffc8e.png)

![image](https://cloud.githubusercontent.com/assets/7791554/6037542/a06c063e-ac8f-11e4-8d72-c64a18648160.png)

![image](https://cloud.githubusercontent.com/assets/7791554/6037539/950c6694-ac8f-11e4-841d-37e2c8c5c03c.png)

**Comment by JMXPSX** [comment]
System will now prevent the deletion of a Shipping Vendor when there is an associated vessel schedules.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
