### ISSUE TITLE
Deletion of sub items of customers that was used in booking caused an error page

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#406]
**Steps to replicate**
1. Log in as Admin
2. Navigate to Booking module
3. Click the Edit icon in the Action Panel of Booking List
4. Observe the fields in the Customer Information
5. Navigate to Customer Module.
6. Click the View Information icon in the Action Panel of Customer List.
7. Delete the sub items used in booking.

**Actual Result**
- Used subitems in booking was successfully deleted.
- After the successful deletion of used subitems in booking, the server encountered an internal error in:
   - Booking
   - Freight Plan
   - Dispatch Plan

**Expected Result**
Sub items that was already in used in booking should not be deleted.

![booking](https://cloud.githubusercontent.com/assets/9795882/6053847/f4502e8e-ad1f-11e4-9150-7aeb6d0d3597.png)

**Comment by JMXPSX** [comment]
Cannot replicate issue. Even after deleting the sub-item in Customer Module. Booking, Freight and Dispatch modules still ok

**Comment by barbacenasmc** [comment]
Hi Sir @JMXPSX, have you tried deleting the consignee of the customer that was used in a booking? I still encounter an error page by doing this. Please see below:
![error 500 server error 4](https://cloud.githubusercontent.com/assets/7791554/6206702/cdeb2006-b5ca-11e4-96cb-042082417cf9.png)

**Comment by JMXPSX** [comment]
Fix on push b9a4c31f22a00c0a08fb93beff3617b501e7f0e6

**Comment by barbacenasmc** [comment]
Error message was still displayed when deleted a contact person of a consignee.
![error 500 server error 5](https://cloud.githubusercontent.com/assets/7791554/6223620/cd8e2796-b6a8-11e4-88ca-db0f7d6c0001.png)

**Comment by barbacenasmc** [comment]
Here are the list of the remaining customer sub-items that have no prompt to tell the user that it should not be deleted when associated with an ongoing booking:
-Address
-Contact person
-Item
-Consignee contact

**Comment by johnpelquingua** [comment]
PINGING @JMXPSX @valienteaidanleary

**Comment by valienteaidanleary** [comment]
done.

**Comment by Leirum** [comment]
Issue fix was already verified.
