### ISSUE TITLE
Consignee information was displayed in the address list of the customer after the successful deletion of address.

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#407]
**Steps to replicate**
1. Log in as Admin
2. Navigate to Customer Module
3. Click the View Information Icon in the Action Panel of Customer List
4. Navigate to Address List of the Customer.
5. Create New Address.
6. When the address was successfully added, delete the address.

**Actual Result**
- Address was successfully deleted
- The address of the consignee was displayed in the address list after the successful deletion.

**Expected Result**
- Only the customer address should be displayed in the address list.

![add address](https://cloud.githubusercontent.com/assets/9795882/6053976/09a409d4-ad22-11e4-9aa5-42801114a453.png)

![delete address](https://cloud.githubusercontent.com/assets/9795882/6053983/1e8f6ece-ad22-11e4-9506-67f5e8db3ecf.png)

**Comment by valienteaidanleary** [comment]
fixed on next push.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
