### ISSUE TITLE
Add Contact Person: Misleading Validation Message for Contact Number.

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#408]
**Steps to replicate**
1. Log in as Admin
2. Navigate to Customer module
3. Add New Customer
4. Fill out all required fields with valid inputs.
5. Click Save

**Actual Result**
It displays a validation message indicating "Please match the requested format (XXX)XXX-XXXX Contact Number should not contain special characters and/or letters."

**Expected Result**
New contact person should be successfully added.

![screen shot 2015-02-05 at 10 54 58 am](https://cloud.githubusercontent.com/assets/9795882/6054298/4602ea54-ad26-11e4-82a7-a80dc56bfb2c.png)

**Comment by valienteaidanleary** [comment]
Done fixed on next push.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
