### ISSUE TITLE
Add Shipping Vessel: User can create a vessel using an existing vessel name

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#409]
Steps to replicate:
1. Navigate to vendor module.
2. Open the profile of a shipping vendor.
3. Add a new vessel.
4. Add another vessel that has the same name and vessel type with the previous one.

Actual result: Creation of vessel succeeded.
Expected result: Creation of vessel should not succeed. A validation message should display saying that the vessel name already exists.

![image](https://cloud.githubusercontent.com/assets/7791554/6054574/1fd5080e-ad2a-11e4-955a-bcf4797c86d7.png)

**Comment by knarceo** [comment]
Fixed on next push on cloud.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
