### ISSUE TITLE
Cannot edit vessel schedule of multiple freight order items with Planning 2 status

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#410]
Steps to replicate:
1. Navigate to freight plan.
2. Open a booking with multiple items.
3. Set vessel schedule for all items to change their status to planning 2.
4. Check all items and click "Edit Vessel Schedule" button,

Actual result: Edit of vessel schedule could not proceed. A prompt saying "Status must be planning 1 only" was displayed.

Expected result: Edit of vessel schedule should proceed.

![image](https://cloud.githubusercontent.com/assets/7791554/6054917/becd6ad2-ad2f-11e4-8ded-b13e1cb7369c.png)

**Comment by knarceo** [comment]
Fixed on next push.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
