### ISSUE TITLE
Freight Plan Edit Vessel Schedule: Error Page was loaded after filtering the vendor for viewing the list of schedules

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#411]
**Steps to replicate**
1. Log in as Admin
2. Navigate to Operations --> Freight Plan
3. Click "Set Vessel Schedule Icon" in the Action Panel of Order # WAL-0008
4. Select an item in Freight Plan
5. Click Edit Vessel Schedule.
6. Select a Vendor
7. Click Filter by Vendor

**Actual Result**
- HTTP Status 500 id to load is required for loading
- The server encountered an internal error in that prevented it from loading the list of schedules of the selected vendor.

**Expected Result**
- Schedules of selected vendor that was inclusive in booking information should be displayed in the lists.

![vendor schedule](https://cloud.githubusercontent.com/assets/9795882/6055390/112251e0-ad39-11e4-9dd3-462037530f6b.png)
![filter by vendor](https://cloud.githubusercontent.com/assets/9795882/6055391/11547a94-ad39-11e4-91b7-d0975e9a465a.png)

**Comment by knarceo** [comment]
I believe this issue does not exist anymore on next push because HTTP 500 did not appear to me. ^_^

**Comment by barbacenasmc** [comment]
Issue can no longer be replicated.
