### ISSUE TITLE
View Booking Information: Contact person of consignee does not display

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#412]
**Steps to replicate:**
1. Navigate to booking list.
2. Click "View Booking Information" icon corresponding to a booking from the list.
3. Observe the contact person on the Consignee Information section.

**Actual result:** Contact person of consignee does not display
**Expected result:** Contact person of consignee should display

![image](https://cloud.githubusercontent.com/assets/7791554/6055565/dd39dcfa-ad3c-11e4-8b5c-048fee03cd25.png)

Expected data to display:
![image](https://cloud.githubusercontent.com/assets/7791554/6055568/f85f857a-ad3c-11e4-8a91-d6caaea94fec.png)

**Comment by valienteaidanleary** [comment]
Done. fixed on next push

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
