### ISSUE TITLE
Add/Edit Customer Form: Customer types still show Premium B and Economy B

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#413]
**Steps to replicate:**
1. Go to add/edit customer form.
2. Click the customer type dropdown list to show options.

**Actual result:** Customer types still show Premium B and Economy B
**Expected result:** Customer types should only display Premium, Regular and Economy.

![image](https://cloud.githubusercontent.com/assets/7791554/6055628/2aceddf2-ad3e-11e4-96a5-0cdd14dd6b40.png)

![image](https://cloud.githubusercontent.com/assets/7791554/6055625/1b4f8200-ad3e-11e4-8e6c-ced2bf1d340a.png)

**Comment by knarceo** [comment]
Fixed on next database pull.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
