### ISSUE TITLE
Dispatch Plan: Adding of New Driver/ Truck proceeds to an error page.

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#414]
**Steps to replicate**
1. Log in as Admin
2. Navigate to Operations --> Dispatch Plan
3. Select the Set Vendor Icon  in the Action Panel of Order # WAL-0008
4. Select an item in Dispatch Plan with Planning 2 Status.
5. Click the Set Vendor button.
6. Navigate to Dispatch Plan: Origin
7 Select Vendor
8. Click the Add Driver/ Add Truck button.
9. Fill out all required fields.
10. Click Save.

**Actual Result**
- The server encountered an internal error

**Expected Result**
- Driver should be successfully added in the selected vendor.
- Truck should be successfully added.

![add driver](https://cloud.githubusercontent.com/assets/9795882/6055672/e452b8d4-ad3e-11e4-8a6b-7cade0418f2d.png)

**Comment by knarceo** [comment]
Fixed on next push, see my reference.

**Comment by barbacenasmc** [comment]
-Set Vendor for multiple items is already okay
-Set Vendor for a single item is already okay
-Edit Vendor for multiple items is not yet okay. Please see image below:
![image](https://cloud.githubusercontent.com/assets/7791554/6160920/3dc558ee-b2a4-11e4-8403-9bc5b993fa48.png)

**Comment by knarceo** [comment]
Fixed on next push :wrench:

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
