### ISSUE TITLE
Edit Contact Person: Middle Name had changed into a required field.

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#415]
**Steps to replicate**
1. Log in as admin
2. Navigate to Vendor Module
3. Click the Information Icon in the Action Panel of the Vendor List
4. Navigate to Contacts.
5. Click the Edit Icon in the Action Panel of Contact Person List.
6. Leave the Middle Name field with null value.
7. Click Save.

**Actual Result**
It displays a validation message indicating "Please fill out this field."

**Expected Result**
Middle Name field can leave with a null value since it is not a required field.

![screen shot 2015-02-05 at 2 34 35 pm](https://cloud.githubusercontent.com/assets/9795882/6055997/0e44d09a-ad45-11e4-9ebd-5d6d0ff19772.png)

**Comment by valienteaidanleary** [comment]
done fixed on next push

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
