### ISSUE TITLE
Set schedule/vendor icon for freight and dispatch planning are different

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#416]
Steps to replicate:
1. Navigate to the freight item list of a particular booking.
2. Navigate to the dispatch item list of a particular booking.

Actual result: Set schedule/vendor icon for freight and dispatch planning are different
Expected result: Set schedule/vendor icon for freight and dispatch planning should be the same

**Freight Plan**
![image](https://cloud.githubusercontent.com/assets/7791554/6160362/c5a008f2-b29c-11e4-8b82-fdb79f3fb886.png)

**Dispatch Plan**
![image](https://cloud.githubusercontent.com/assets/7791554/6056031/d021aa4e-ad45-11e4-8d72-8c02943fda8a.png)

**Comment by JMXPSX** [comment]
It looks the same to me...

**Comment by barbacenasmc** [comment]
Hi Sir @JMXPSX , kindly check updated image attachmets

**Comment by valienteaidanleary** [comment]
fixed on next push.

**Comment by barbacenasmc** [comment]
Issue can still be replicated. Please see image below for dispatch plan:
![image](https://cloud.githubusercontent.com/assets/7791554/6181129/3069719c-b369-11e4-8274-75276b83ba50.png)

**Comment by JMXPSX** [comment]
Fix on Push 8b9b193f94958e4e1726a248ccbd5c52fe0a7fdc

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
