### ISSUE TITLE
Add Items to Booking: Amount was displayed on declared value field instead on rate field

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#417]
Steps to replicate:
1. Create a new booking with FCL as service requirement.
2. On page to, select a container size.

Actual result: Corresponding amount was displayed on declared value field instead on rate field
Expected result: Amount should be displayed on rate field.

![image](https://cloud.githubusercontent.com/assets/7791554/6056101/31c7e956-ad47-11e4-9efb-2dfb7c6a36fd.png)

**Comment by valienteaidanleary** [comment]
This is working as intended. Declared Value corresponds to the Container and the contents inside all rolled into one.

**Comment by barbacenasmc** [comment]
Will close this issue due to clarifications on the requirement as the PO stated.
