### ISSUE TITLE
Vessel schedule list: Irrelevant legend icons are displayed

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#418]
Steps to replicate:
1. Navigate to vessel schedule list.
2. Observe the legend icons at the bottom.

Actual result: Irrelevant legend icons are displayed
Expected result: 
-Shipping, trucking, information, approve and cancel icons should be removed.
-Edit icon should be changed according to what was used on the list.

![image](https://cloud.githubusercontent.com/assets/7791554/6056118/9cd70664-ad47-11e4-9fc7-c211897a1010.png)

**Comment by valienteaidanleary** [comment]
Done fixed on next push.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
