### ISSUE TITLE
Dispatch Plan: Edit Vendor for Door to Door Service mode, retrieves null values in each field.

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#420]
**Steps to replicate**
1. Log in as Admin
2. Create New Booking with a Service Mode of Door to Door
3. Navigate to Freight Plan and set the vendor of the created booking.
4. Navigate to Dispatch Plan and set its vendor
5. In dispatch plan module, select the vendor with an ongoing status and click the Edit Vendor button.

**Actual Result**
- All fields in dispatch plan origin and destination have null values.

**Expected Result**
- Last saved information for both dispatch plan: origin and destination should be retrieved in each field.

![door to door edit vendor](https://cloud.githubusercontent.com/assets/9795882/6057364/777eeca4-ad58-11e4-8043-1edf10379e7a.png)

**Comment by JMXPSX** [comment]
Added quick view of current vendors on push 548322bfc0553c95b81a5d5b61cb1af82c50c60a

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
