### ISSUE TITLE
Dispatch Plan: Year model and gross weight were not saved when adding truck

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#421]
Steps to replicate:
1. Navigate to dispatch plan 
2. Open an ongoing booking with items for dispatch planning.
3. Click for Set Vendor button for a selected item.
4. Click Add Truck.
5. Fill-out the form and click Save.

Actual result: Year model and gross weight were not saved. Also checked the details of the truck on vendor module but data were still not displayed.
Expected result: Year model and gross weight should be saved.

![image](https://cloud.githubusercontent.com/assets/7791554/6160848/34d56dc4-b2a3-11e4-8208-526a7d0cfd07.png)

![image](https://cloud.githubusercontent.com/assets/7791554/6160860/687e369c-b2a3-11e4-8941-ebe0340556c2.png)

**Comment by knarceo** [comment]
![capture](https://cloud.githubusercontent.com/assets/9584157/6162268/dbd8af16-b2ba-11e4-8c44-b2d60b8d73a7.PNG)


but mine did :cry:

**Comment by JMXPSX** [comment]
Issue cannot be replicated as per Aidan

**Comment by barbacenasmc** [comment]
Hi everyone, what I mean here is to add trucking through dispatch plan page. I can still replicate this on my end.
![image](https://cloud.githubusercontent.com/assets/7791554/6162478/e9e95444-b2be-11e4-99ff-8a4c9ef3f660.png)

**Comment by knarceo** [comment]
![capture](https://cloud.githubusercontent.com/assets/9584157/6162612/1e90c892-b2c1-11e4-9fd0-133897bc9239.PNG)
but i did :sob:

**Comment by barbacenasmc** [comment]
Hi, just found out that the real issue behind this is issue #425. Closing this issue as invalid.
