### ISSUE TITLE
Shipment Monitoring: Selected items cannot be unchecked

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#422]
Steps to replicate:
1. Navigate to shipment monitoring page.
2. Click "Update Status" icon corresponding to a booking.
3. On the list of items/containers, check the main checkbox.
4. Try to uncheck the main checkbox to deselect all items.

Actual result: Items was not unchecked
Expected result: Items should be unchecked

![image](https://cloud.githubusercontent.com/assets/7791554/6163585/5f8d99f2-b2cf-11e4-9cd1-a6c45bbdb8bc.png)

**Comment by knarceo** [comment]
Fixed on next push, including the same problem in Dispatch Planning and Documents Module check issues.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
