### ISSUE TITLE
Dispatch Plan: Edit vendor of a single item still displays all items on preview

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#423]
Steps to replicate:
1. Navigate to dispatch plan.
2. Open a booking with multiple items.
3. Set an inland vendor for each item if none of them has vendor yet.
4. Check one item and click Edit Vendor button.

Actual results: On the preview section of item, all items where displayed even if the purpose is to set vendor for a single item only.

Expected result: Only the selected item should display on the list

![image](https://cloud.githubusercontent.com/assets/7791554/6181554/b694bfe6-b36f-11e4-9ff5-ecbb6ac782ea.png)

**Comment by knarceo** [comment]
Fixed on next push.

**Comment by Leirum** [comment]
Issue fix was already verified.
