### ISSUE TITLE
Dispatch Plan: Truck type, plate number, gross weight were not automatically updated when changed truck

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#425]
Steps to replicate:
1. Navigate to dispatch plan.
2. Open a booking that has items for inland freight planning.
3. Set vendor for any of the item.
4. On the dispatch planning page, select a vendor from the dropdown list. (Automatically, corresponding driver, truck code and other details display on the fields.)
5. Select another truck code from the list.

Actual result: Truck type, plate number, gross weight were not automatically updated
Expected result: Truck type, plate number, gross weight should be automatically updated based on the details of the selected truck.

![image](https://cloud.githubusercontent.com/assets/7791554/6183646/3fbbcef0-b392-11e4-824f-5b3f26464889.png)

![image](https://cloud.githubusercontent.com/assets/7791554/6183642/36e36a18-b392-11e4-9dde-0e1ad18a3bb2.png)

**Comment by knarceo** [comment]
Fixed on next push.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
