### ISSUE TITLE
Dispatch Plan: Cannot add driver/truck when editing vendor of items

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#426]
Steps to replicate:
1. Navigate to dispatch plan.
2. Open a booking with items that were already done with inland freight planning.
3. Check all items and click Edit Vendor.
4. On the dispatch plan page, select a vendor.
5. Click Add Driver or Add Truck button.

Actual result: Both action results to a prompt telling that the user needs to select a vendor first.
Expected result: Add driver or add truck form should display.

![image](https://cloud.githubusercontent.com/assets/7791554/6183749/ea771e3e-b393-11e4-85c8-fcbb8af91b9f.png)

**Comment by knarceo** [comment]
Fixed on next push.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
