### ISSUE TITLE
IFO: Sub-menus for Operation module do not display

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#427]
Steps to replicate:
1. Login as IFO User.
2. Click the Operations module.

Actual result Sub-menus for Operation module do not display
Expected result: Dispatch plan and shipment monitoring should display

![image](https://cloud.githubusercontent.com/assets/7791554/6206213/d5789cdc-b5bf-11e4-99a6-54a783094692.png)

**Comment by johnpelquingua** [comment]
Please test

**Comment by barbacenasmc** [comment]
Issue fix was already verified.

**Comment by barbacenasmc** [comment]
Another issue was produced after fixing this issue. Please see #437
