### ISSUE TITLE
Cannot login to newly created user accounts

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#428]
Steps to replicate:
1. Create user accounts for admin ad regular customer role.
2. Login using to each created account.

Actual result: A white page with broken image was displayed. A message saying "Hi, you do not have permission to access this page!" was also displayed.
Expected result: User dashboard should display.
![image](https://cloud.githubusercontent.com/assets/7791554/6206957/e7c88f62-b5d0-11e4-8e31-82935f7660f0.png)

**Comment by johnpelquingua** [comment]
Please test for admin and reg customer

**Comment by barbacenasmc** [comment]
Issue can still be replicated.
![image](https://cloud.githubusercontent.com/assets/7791554/6240456/dac2dfbe-b749-11e4-8a29-eaf4975741c4.png)

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
