### ISSUE TITLE
Create User: Customer field becomes enabled when selected "Customer Relations Department" as user type

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#429]
Steps to replicate:
1. Go to create user page.
2. Select "Customer Relations Department" as user type.

Actual result: Customer field becomes enabled.
Expected result: Customer field should not be enabled. It should only be available for "Regular Customer" user type.

![customer-relations](https://cloud.githubusercontent.com/assets/7791554/6206982/bf40b26c-b5d1-11e4-9fcd-fed86c0adf37.png)

**Comment by valienteaidanleary** [comment]
done fixed on next push.

**Comment by valienteaidanleary** [comment]
Done.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
