### ISSUE TITLE
Sales has no permission to create a new booking

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#431]
Steps to replicate:
1. Login as sales.
2. Navigate to booking list.

Actual results: User has no permission to create a new booking.
Expected result: User should have a permission to create a new booking

![image](https://cloud.githubusercontent.com/assets/7791554/6207990/5ae12ec2-b5eb-11e4-9a08-8265fa90be9f.png)

**Comment by valienteaidanleary** [comment]
fixed on next push.

**Comment by valienteaidanleary** [comment]
Done.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
