### ISSUE TITLE
Dashboard of sales user account has no customer

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#433]
Steps to replicate:
1. Login as sales.
2. Observe the available menus on the right side.

Actual result: There was no menu option for customer module.
Expected result: There should be a menu for customer module.

![image](https://cloud.githubusercontent.com/assets/7791554/6208825/90e24cc8-b5f9-11e4-8a31-efa1085ce5de.png)

**Comment by valienteaidanleary** [comment]
fixed on next push.

**Comment by valienteaidanleary** [comment]
Done.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
