### ISSUE TITLE
Edit Profile: Contact no. field has no masking for standard format

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#434]
Steps to replicate:
1. Login to any user account.
2. Go to edit profile page.
3. Clear the values on the contact no. field.
4. Enter a new contact no.

Actual result: There was no masking for the standard format of the contact no.
Expected result There should be masking that will automatically put parentheses and dashes based on the standard format of the contact no.

![image](https://cloud.githubusercontent.com/assets/7791554/6208883/51e0b28e-b5fa-11e4-8b24-9d4591878998.png)

**Comment by valienteaidanleary** [comment]
fixed on next push.

**Comment by valienteaidanleary** [comment]
Done.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
