### ISSUE TITLE
Login: Non-user friendly error message was displayed when entered incorrect login credentials

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#435]
Steps to replicate:
1. Go to login page.
2. Enter incorrect username and password.
3. Click Login button.

Actual result: Non-user friendly error message was displayed saying "UserDetailsService returned null, which is an interface contract violation."
Expected result: A message saying "Bad credentials." should display.

![image](https://cloud.githubusercontent.com/assets/7791554/6208926/b5dd1ca0-b5fa-11e4-96a6-f71e8e88e65d.png)

**Comment by johnpelquingua** [comment]
Please test

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
