### ISSUE TITLE
IFO user can access customer module

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#436]
Steps to replicate:
1. Navigate to Inland Freight Officer.
2. Enter any of the following URL on address bar.
http://localhost:8080/freightbit/customers/customerListNew.action
http://localhost:8080/freightbit/customers/customerList.action

Actual result: User can still access the customer module
Expected result: User should see a 404 page.

![image](https://cloud.githubusercontent.com/assets/7791554/6223811/596f1ab0-b6ac-11e4-946a-b1ff59647f0d.png)

**Comment by johnpelquingua** [comment]
Please test

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
