### ISSUE TITLE
IFO user can access freight planning and vessel schedules

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#437]
Steps to replicate:
1. Login as Inland Freight Officer.
2. Enter any of the URL below on the address bar:
http://localhost:8080/freightbit/operations/viewSeaFreightList.action
http://localhost:8080/freightbit/operations/viewVesselSchedules.action

Actual result: User can still view the freight plan and vessel schedule pages.
Expected result: User should not be able to view these pages.

**Freight Plan**
![image](https://cloud.githubusercontent.com/assets/7791554/6240409/1f7a166e-b749-11e4-8b6f-c9a6beecca3c.png)

**Vessel Schedules**
![image](https://cloud.githubusercontent.com/assets/7791554/6240405/09444702-b749-11e4-9423-b7a31f1756a0.png)

**Comment by Leirum** [comment]
Issue can still be replicated.

**Comment by barbacenasmc** [comment]
Closing this issue for it is no longer valid.
