### ISSUE TITLE
Booking list of CRO user has no "New Booking" button

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#438]
Steps to replicate:
1. Login as Customer Relations Officer.
2. Go to booking list.

Actual result: There was no "New Booking" button. (However, he can access the new booking page by directly navigating to this link - http://localhost:8080/freightbit/orders/loadAddOrderPage

Expected result: There should be a "New Booking" button on the booking list of a CRO user.
![image](https://cloud.githubusercontent.com/assets/7791554/6241278/4a7f2672-b755-11e4-8b2d-b3b873ad3a55.png)

**Comment by valienteaidanleary** [comment]
fixed on next push.

**Comment by Leirum** [comment]
Issue fix was already verified.
