### ISSUE TITLE
CRO user can access freight plan, dispatch plan and vessel schedules page

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#439]
Steps to replicate:
1. Login as Customer Relations Officer.
2. Enter any of the URL below on the address bar:
http://localhost:8080/freightbit/operations/viewSeaFreightList.action
http://localhost:8080/freightbit/operations/viewInlandFreightList.action
http://localhost:8080/freightbit/operations/viewVesselSchedules.action

Actual result: User can still view the freight plan, dispatch plan and vessel schedules pages.
Expected result: User should not be able to view these pages.

**Freight Plan**
![image](https://cloud.githubusercontent.com/assets/7791554/6241327/2e4a0520-b756-11e4-87cb-349d3ff87247.png)

**Dispatch Plan**
![image](https://cloud.githubusercontent.com/assets/7791554/6241332/495bcb0a-b756-11e4-8000-29d9182e3ada.png)

**Vessel Schedules**
![image](https://cloud.githubusercontent.com/assets/7791554/6241385/f91835c4-b756-11e4-9b01-f31203d4f362.png)

**Comment by Leirum** [comment]
Issue can still be replicated.

**Comment by JMXPSX** [comment]
Checked. CRO blocked access for Operations Module freight plan, dispatch plan and vessel schedules

**Comment by Leirum** [comment]
Issue can still be replicated on 
http://192.168.5.163:8080/freightbit/operations/viewSeaFreightList.action
http://192.168.5.163:8080/freightbit/operations/viewInlandFreightList.action
http://192.168.5.163:8080/freightbit/operations/viewVesselSchedules.action

**Comment by barbacenasmc** [comment]
Vessel schedule is already okay. But CRO can still access the freight and dispatch plan page by navigating directly through the URL

**Comment by knarceo** [comment]
Fixed on next push.

**Comment by Leirum** [comment]
replicating this issue results in
![screen shot 2015-05-06 at 11 13 06 am](https://cloud.githubusercontent.com/assets/9795882/7486972/f074a9ea-f3e0-11e4-80dc-bfc1d1a77d93.png)

**Comment by Leirum** [comment]
Issue fix was already verified.
