### ISSUE TITLE
CRO user can access yard management sub-pages

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#441]
Steps to replicate:
1. Login as Customer Relations Officer.
2. Enter any of the URL below on the address bar:
http://localhost:8080/freightbit/operations/viewContainerList.action
http://localhost:8080/freightbit/operations/viewConsolidationContainerList.action

Actual result: User can still view the container management list and consolidation page.
Expected result: User should not be able to view these pages.

**Container Management**
![image](https://cloud.githubusercontent.com/assets/7791554/6241741/5c309f74-b75d-11e4-9a0a-16dd42cc91d9.png)

**Consolidation**
![image](https://cloud.githubusercontent.com/assets/7791554/6241734/22f1f096-b75d-11e4-92b5-6570cd8a306e.png)

**Comment by Leirum** [comment]
Issue can still be replicated.

**Comment by barbacenasmc** [comment]
Issue can no longer be replicated on URL - http://eios.ernest.com.ph/operations/viewContainerList.action
Issue can still be replicated on URL - http://eios.ernest.com.ph/operations/viewConsolidationContainerList.action

**Comment by JMXPSX** [comment]
Checked. CRO blocked access for Yard Management module

**Comment by Leirum** [comment]
Issue can still be replicated on URL:
http://localhost:8080/freightbit/operations/viewContainerList.action
http://localhost:8080/freightbit/operations/viewConsolidationContainerList.action

**Comment by barbacenasmc** [comment]
Issue can still be replicated. Any updates on this?

**Comment by knarceo** [comment]
Fixed on next push.

**Comment by Leirum** [comment]
Issue fix was already verified.
