### ISSUE TITLE
Freight Plan: User can select same location for origin and destination for filter

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#442]
Steps to replicate:
1. Navigate to Freight Plan.
2. Select "Manila" as origin.
3. Select "Bacolod" as destination. (Observe here that "Manila" is no longer included in the destination list.)
4. Click Sort button.
5. After the list has been filtered, click again the destination dropdown list.

Actual result: "Manila" is again available in the list.
Expected result: Once a particular port has been selected for origin or destination, it should no longer be available to the other field.
![image](https://cloud.githubusercontent.com/assets/7791554/6242665/8e4ccc92-b76e-11e4-8309-d182b1bc4583.png)

**Comment by knarceo** [comment]
Fixed on next push

**Comment by Leirum** [comment]
Issue fix was already verified.
