### ISSUE TITLE
Freight Plan: Dropdown list on origin or destination for filtering list no longer displays once selected blank on the other field

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#443]
Steps to replicate:
1. Navigate to Freight Plan.
2. Select "Manila" as origin.
3. Select "Bacolod" as destination. 
4. Click Sort button.
5. After the list has been filtered, click again the origin/destination dropdown list and select blank.
6. Click the other field to show the dropdown list.

Actual result: Dropdown list no longer display.
Expected result: Dropdown list should display.

![image](https://cloud.githubusercontent.com/assets/7791554/6242706/3c801986-b76f-11e4-8523-a59f914d33d4.png)

**Comment by knarceo** [comment]
Fixed on next push

**Comment by Leirum** [comment]
Issue fix was already verified.
