### ISSUE TITLE
Freight Plan: No way to display again all items after filtering the list

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#444]
Steps to replicate:
1. Navigate to freight plan.
2. Filter the list by any preferred origin and destination.

Actual result: There was no option to display all items again, or to clear the filter. Even refreshing the page won't show it. The user needs to click Freight Plan under Operations on the menu again to do so.

Expected result: There should be a way to display again all the items or clear the filter.

![image](https://cloud.githubusercontent.com/assets/7791554/6242754/f91d3510-b76f-11e4-9ed8-44cf9b642748.png)

**Comment by knarceo** [comment]
Fixed on next push

**Comment by Leirum** [comment]
Issue fix was already verified.
