### ISSUE TITLE
Dispatch Plan: Details about freight plan were not displayed when selected Set Vendor for multiple items

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#445]
Steps to replicate:
1. Navigate to dispatch plan.
2. Open a booking with multiple items with planning 2 as status.
3. Check the items and click Set Vendor.

Actual result: Details about freight plan were not displayed
Expected result: Details about freight plan should be displayed. (Because setting vendor of a single items behave this way.)

**Set vendor (multiple items)**
![dispatch plan](https://cloud.githubusercontent.com/assets/7791554/6242857/83cfdd56-b771-11e4-9fe7-1b9dd9673946.png)

**Set vendor (single item, clicked set vendor icon corresponding to 1 item)**
![dispatch plan 1](https://cloud.githubusercontent.com/assets/7791554/6242880/d8b4b2ba-b771-11e4-9dbf-aa5bd2dc6ba0.png)

**Comment by JMXPSX** [comment]
Fix on Push b239d9a2a7e637a6086cef30a64a816a8320da5d

**Comment by Leirum** [comment]
Issue fix was already verified.
