### ISSUE TITLE
Dispatch Plan: View of planning information has a disorganized layout

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#446]
Steps to replicate:
1. Navigate to dispatch plan page.
2. Open a booking with items that was already set with inland freight vendor.
3. Click "View Information" icon corresponding to 1 item.

Actual result: View planning information page has a disorganized layout. 
Expected result: Dispatch plan section should have the same width with the booking information section and back button should be at the bottom.

![dispatch plan 2](https://cloud.githubusercontent.com/assets/7791554/6242977/cd29b128-b773-11e4-9fdb-88fb8c17ed37.png)

**Comment by JMXPSX** [comment]
Fix on Push e21209f10d6aa37295935ea6d6871daac6600936

**Comment by Leirum** [comment]
Issue fix was already verified.
