### ISSUE TITLE
Freight Plan: Different Page Layout was Displayed in Clicking the Edit Vessel Schedule Icon and Button

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#447]
**Steps to replicate**
1. Log in as Admin
2. Navigate to Operations --> Freight Plan.
3. Select the order # Wal-0000 and set its vessel schedule.
4. Select the Voyage # 3579 and click the Edit Vessel Schedule button.
5. At the same time, click the edit schedule icon in the action panel of Voyage # 3579.
6. Compare the layout of both page navigated by clicking the Edit Vessel Schedule Icon and Button.

**Actual Result**
![screen shot 2015-02-25 at 1 49 50 pm](https://cloud.githubusercontent.com/assets/9795882/6365605/40c2ace4-bcf5-11e4-8881-1e70095c8726.png)

**Expected Result**
-It should display the same browser tab title.
-Both page should have similar user interface and content.
-Voyage # 2GO-111 should not be displayed in the current schedule when Set Vessel Schedule button has been clicked by the user.

**Edit Vessel Schedule (multiple items)**

![screen shot 2015-02-25 at 11 29 30 am](https://cloud.githubusercontent.com/assets/9795882/6365473/10b0eba8-bcf3-11e4-994a-209639704f8d.png)

![edit vessel schedule button](https://cloud.githubusercontent.com/assets/9795882/6365470/10a9164e-bcf3-11e4-9f91-26156660bf91.png)

**Edit Vessel Schedule (single item, clicked edit schedule icon corresponding to 1 item)**

![screen shot 2015-02-25 at 11 29 14 am](https://cloud.githubusercontent.com/assets/9795882/6365472/10ace5f8-bcf3-11e4-9e35-4297d69bdbd7.png)

![edit vessel schedule icon](https://cloud.githubusercontent.com/assets/9795882/6365471/10a95b22-bcf3-11e4-99a2-961dec5f6173.png)

**Comment by johnpelquingua** [comment]
@knarceo Can you please check this? Thanks!

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
