### ISSUE TITLE
Dispatch Plan: Different Page Layout was Displayed in Clicking the Set Vendor Icon and Button

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#448]
**Steps to replicate**
1. Log in as Admin
2. Navigate to Operations --> Dispatch Plan Plan.
3. Select the order # Wal-0000 and click its Set Vendor Icon.
4. Select the item with a Planning 3 Status, and click the Set Vendor Button
5. At the same time, click the Set Vendor icon in the action panel of the selected item.
6. Compare the layout of both page navigated by clicking the Set Vendor Icon and Button.

**Actual Result**
![screen shot 2015-02-25 at 2 18 17 pm](https://cloud.githubusercontent.com/assets/9795882/6365901/34a1093e-bcf9-11e4-8b93-562d696d6213.png)

**Expected Result**
-Both page should have similar content, layout and user interface.

Set Vendor Schedule Icon(single item, clicked edit schedule icon corresponding to 1 item)
![dispatch plan set vendor icon](https://cloud.githubusercontent.com/assets/9795882/6365841/7f56fec6-bcf8-11e4-9f36-89ceef18e5bc.png)

Set Vendor Schedule Button (multiple items)
![dispatch plan set vendor button](https://cloud.githubusercontent.com/assets/9795882/6365840/7f0b94cc-bcf8-11e4-8e4d-2100770284bc.png)

**Comment by Leirum** [comment]
Issue can still be replicated.

Set Vendor Button
![3 2](https://cloud.githubusercontent.com/assets/9795882/7487232/14bac19a-f3e6-11e4-9e3d-520916527ab8.png)

Set Vendor Icon
![3 1](https://cloud.githubusercontent.com/assets/9795882/7487235/20a3134a-f3e6-11e4-9aee-f7d2e850a2b9.png)

**Comment by knarceo** [comment]
Cannot be replicated, the only difference I see is if you click "Select Vendor Button" for multiple items, it will display the freight plan differently than the "Select Vendor Icon" for single items.

**Comment by barbacenasmc** [comment]
No longer an issue.
