### ISSUE TITLE
Dispatch Plan Orders Trucking: Full Truck Load table cells size is different from the Less Truck Load table; Each row doesn't have a background color that depends upon the item status.

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#449]
**Steps to replicate**
1. Log in as Admin
2. Navigate to Operations --> Dispatch Plan.
3. Navigate to Trucking.
4. Compare the table of Full Truck Load and Less Truck Load.

**Actual Result**
- Full Truck Load and Less Truck Load Table Cells have different width for the attribute of Customer, Consignee and Mode.
- No background color for each table row.

**Expected Result**
-Both FTL and LTL Table size should be the same in terms of width, length and height.
-Background color for each table row should depend upon the item status.

![full truck load](https://cloud.githubusercontent.com/assets/9795882/6366299/9338f90c-bcfe-11e4-9a0d-49bb53cc51af.png)
![less truck load](https://cloud.githubusercontent.com/assets/9795882/6366300/933d5e66-bcfe-11e4-860f-50f7ad3b8513.png)

**Comment by valienteaidanleary** [comment]
fixed on next push.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
