### ISSUE TITLE
Missing Icons in Every Page (Mozilla Firefox)

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#450]
**Steps to replicate**
1. Log in as Admin (in both chrome and firefox)
2. Navigate to Booking module.

**Actual Result**
-Icons in every page were missing in firefox.

**Expected Result**
-Icons should be displayed(Firefox).
 
**Mozilla Firefox**
![firefox](https://cloud.githubusercontent.com/assets/9795882/6366972/2d4bae8c-bd08-11e4-8f7c-e66634d6a761.png)

**Google Chrome**
![chrome](https://cloud.githubusercontent.com/assets/9795882/6366973/2db90676-bd08-11e4-81ae-336a5441c599.png)

**Comment by ZaX09** [comment]
issue already fixed in live site

**Comment by barbacenasmc** [comment]
Issue can still be replicated. Icons were displayed only when on home page.

**Comment by knarceo** [comment]
what version of firefox are you using?

**Comment by barbacenasmc** [comment]
version 35.0.1

**Comment by Leirum** [comment]
Issue fix was already verified.
