### ISSUE TITLE
Edit Booking: Misaligned label for Consignee Information (Mozilla Firefox)

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#451]
**Steps to replicate**
1. Log in as Admin (in Firefox)
2. Navigate to Booking module.
3. Select an item in the booking list and click the Edit Booking icon in the action panel
4. Navigate to Consignee Information frame.

**Actual Result**
- Misaligned label for Consignee Information

**Expected Result**
- "Consignee Information" text label should be on the same row. (same coordinates as customer information)

![consignee information label](https://cloud.githubusercontent.com/assets/9795882/6367140/22da8b06-bd0a-11e4-9c20-a6b410cd69f0.png)

**Comment by knarceo** [comment]
Please check Firefox version. Thanks

**Comment by Leirum** [comment]
Issue can still be replicated on Firefox v. 36.0.1

**Comment by barbacenasmc** [comment]
Issue can no longer be replicated on latest version of Firefox or Chrome
