### ISSUE TITLE
Shipment Monitoring: Clicking the Update Status Icon Proceeds to an Error Page.

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#452]
**Steps to replicate**
1. Log in as Admin
2. Navigate to Operations --> Shipment Monitoring
3. Click the Update Status Icon in the Action Panel of any Item.

**Actual Result**
- Proceeds to an error page.

**Expected Result**
- It should navigate to update status page.

![error](https://cloud.githubusercontent.com/assets/9795882/6367779/53f86a30-bd11-11e4-8c64-dfe5722abec2.png)

**Comment by JMXPSX** [comment]
Please update database to recent

**Comment by barbacenasmc** [comment]
Issue can no longer be replicated.
