### ISSUE TITLE
Freight Plan and Dispatch Plan: Order # Bal-0000 and Bal-0003 Proceeds to an Error Page.

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#453]
**Steps to replicate**
1. Log in as Admin
2. Navigate to Operations --> Freight Plan or Operations --> Dispatch Plan.
3. Select the Order # Bal-0000 or Order # Bal-0003
4. Click any of its icon in the action panel.

**Actual Result**
- Proceeds to an error page.

**Expected Result**
- Set Vessel Schedule Icon should proceed to Freight Item List Page.
- View Booking Information should proceed to Booking Information Page.

![error page](https://cloud.githubusercontent.com/assets/9795882/6367935/cea0cea2-bd12-11e4-8fd4-eb3992f3bebf.png)

**Comment by JMXPSX** [comment]
Please update database to recent

**Comment by barbacenasmc** [comment]
Issue fix can still be replicated on live site which is updated as of 12pm, Feb. 26.

**Comment by barbacenasmc** [comment]
Issue can no longer be replicated.
