### ISSUE TITLE
View Booking Information: Misspelled Label for Comments

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#454]
**Steps to replicate**
1. Log in as Admin
2. Navigate to Booking module
3. Select the Order # Bal-0004 and click its View Booking Information Icon.

**Actual Result**
- Misspelled label for Comments
- Displays "Commentssssss"

**Expected Result**
- It should be correctly spelled as "Comments"

![commentssss](https://cloud.githubusercontent.com/assets/9795882/6368067/177b8116-bd14-11e4-9246-86d8b247c1ed.png)

**Comment by JMXPSX** [comment]
This is already resolved. Build must be current

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
