### ISSUE TITLE
Freight Plan: No Search Results when Sorting the Orders in Less Container Load.

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#455]
**Steps to replicate**
1. Log in as Admin
2. Navigate to Operations --> Freight Plan
3. Navigate to Less Container Load.
4. Sort the Freight Plan List.

**Actual Result**
- Non-stop processing of LCL orders.
- No Search Results.

**Expected Result**
- It should display the LCL orders containing the values in sorting.

![1](https://cloud.githubusercontent.com/assets/9795882/6384756/a075088e-bd9b-11e4-913c-d2021e1d91c7.png)

![2](https://cloud.githubusercontent.com/assets/9795882/6384755/a072bbb0-bd9b-11e4-9bc2-da34e6c64cab.png)

**Comment by knarceo** [comment]
Fixed on next push.

**Comment by barbacenasmc** [comment]
Issue can still be replicated when tried to filter using ports that are supposed to show no results.
![image](https://cloud.githubusercontent.com/assets/7791554/6497575/9e3cca26-c31c-11e4-9780-58fd7e692949.png)

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
