### ISSUE TITLE
Dispatch Plan: View Booking Information: Misaligned Values of Consignee Information

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#456]
**Steps to replicate**
1. Log in as Admin
2. Navigate to Operations --> Dispatch Plan
3. Select the Order # WAL-0000 and click its View Booking Information Icon.

**Actual Result**
- Misaligned values in Consignee Information.

**Expected Result**
- Customer Information and Consignee Information should be on the same coordinates.

![booking information](https://cloud.githubusercontent.com/assets/9795882/6384952/98f6228e-bd9e-11e4-9eb7-88451ac86c70.png)

**Comment by ZaX09** [comment]
fixed

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
