### ISSUE TITLE
Dispatch Plan: Sorting of Orders in Trucking Depends upon the Sorting Made in Origin Tab; There's No Button for Viewing the Complete Dispatch Plan List after the Successful Sorting of Orders.

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#457]
**Steps to replicate**
1. Log in as Admin
2. Navigate to Operations --> Dispatch Plan
3. In Origin tab, sort the orders in Dispatch Plan List.
4. Then navigate to Trucking.

**Actual Result**
- Selected value in Sort by Origin was also implemented in sort by location in trucking.
- There is no button for viewing all the orders after the successful sorting of information.

**Expected Result**
- Change of values in sort by location (Trucking) should not depend upon the sorting made in origin tab.
- There should be a button for displaying all the orders in dispatch plan list after the successful sorting of information.

![sort by origin](https://cloud.githubusercontent.com/assets/9795882/6385060/f42b7810-bd9f-11e4-8819-0c134ed9896d.png)

![sort by location](https://cloud.githubusercontent.com/assets/9795882/6385061/f4328ccc-bd9f-11e4-858a-478e59738b9a.png)

**Comment by knarceo** [comment]
Fixed on next push

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
