### ISSUE TITLE
Shipment Monitoring: Text Attribute is not Fitted on its Cells.

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#458]
**Steps to replicate**
1. Log in as Admin
2. Navigate to Operations --> Shipment Monitoring

**Actual Result**
- Text attribute (with icons) is not fitted on its cells.

**Expected Result**
- Text attribute should be fitted on its cells.
- Each row should have the same height.

![order list](https://cloud.githubusercontent.com/assets/9795882/6385419/738c4734-bda4-11e4-9c24-2ac19d70ba49.png)

**Comment by valienteaidanleary** [comment]
fixed on next push.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
