### ISSUE TITLE
Missing Legend Panel in Customer and Vendor Module.

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#459]
**Steps to replicate**
1. Log in as Admin
2. Navigate to Customer Module.
3. Open in New tab the Vendor Module and Accounts --> User module.

**Actual Result**
- Missing Legend Panel in Customer and Vendor Module

**Expected Result**
- It should also display a Legend Panel in Customer and Vendor Module as like what is shown in the User module.

**Vendor Module**
![view vendor list](https://cloud.githubusercontent.com/assets/9795882/6385675/44fa5c9a-bda8-11e4-8b0e-662b579edf62.png)

**Customer Module**
![view customer list](https://cloud.githubusercontent.com/assets/9795882/6385676/4501992e-bda8-11e4-88fb-160568fd8cf2.png)

**User Module**
![user page](https://cloud.githubusercontent.com/assets/9795882/6385677/4501a5ae-bda8-11e4-9c27-c3a2b65ad84d.png)

**Comment by valienteaidanleary** [comment]
fixed on next push.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
