### ISSUE TITLE
New Booking: Text input in Comments Field goes Beyond the Boundary of the Order Details Frame.

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#460]
**Steps to replicate**
1. Log in as Admin
2. Navigate to Booking module
3. Create New Booking
4. Fill out all required fields.
5. Input 255 characters in the Comments Area Text Field.
6. Click Next
7. Observe the Order Details Frame. 

**Actual Result**
- Text input in comments field goes beyond the boundary of the order details frame.

**Expected Result**
- Comments should be fitted on the given width of the order details frame.

![edit booking](https://cloud.githubusercontent.com/assets/9795882/6385949/792d320e-bdac-11e4-8b38-e34700734723.png)
![view add booking](https://cloud.githubusercontent.com/assets/9795882/6385950/79613c66-bdac-11e4-9e3c-036c391caa7b.png)

**Comment by valienteaidanleary** [comment]
fixed on next push.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
