### ISSUE TITLE
Edit Booking: Delivery Address and Contact Person fields were empty for an ongoing booking

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#461]
Steps to replicate:
1. Navigate to booking list.
2. Click the edit icon corresponding to an booking with an ongoing status.

Actual result: The delivery address and contact person fields were empty.
Expected result: The delivery address and contact person fields should have content.

![image](https://cloud.githubusercontent.com/assets/7791554/6386910/8d43b032-bdbc-11e4-98eb-48a0a80e96fc.png)

**Comment by knarceo** [comment]
Fix on push b033834f24dd2456274237ab43d5fd4059bcb21c

-- Jojo

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
