### ISSUE TITLE
Dispatch Plan: Icon for trucking tab is missing

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#462]
Steps to replicate:
1. Navigate to dispatch plan.

Actual result: Icon for trucking tab is missing. (This is specific for live site only).
Expected result: Icon for trucking tab should display. 

![image](https://cloud.githubusercontent.com/assets/7791554/6386956/a2bc5454-bdbd-11e4-9941-767a9ee7ef73.png)

**Comment by valienteaidanleary** [comment]
fixed on next push.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
