### ISSUE TITLE
Add Customer: Customer type still reflects more than three types

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#463]
Steps to replicate:
1. Navigate to add customer page.
2. Click the dropdown list for customer types.

Actual result: Customer types display Premium, Regular, Economy and Premium B.
Expected result: There should be no more "Premium B" on the list.

![image](https://cloud.githubusercontent.com/assets/7791554/6409503/a714ac44-be9f-11e4-859b-4156b5c7f9c5.png)

**Comment by knarceo** [comment]
Fixed on next update of database.

**Comment by barbacenasmc** [comment]
Issue can no longer be replicated.
