### ISSUE TITLE
IFO user dashboard has no freight plan sub-menu

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#464]
Steps to replicate:
1. Login as IFO user.
2. Click the Operations module.

Actual result: There is no sub-menu for freight plan.
Expected result: There should be a sub-menu for freight plan.

![ifo-no-freight-plan_20150302](https://cloud.githubusercontent.com/assets/7791554/6434474/c5c8b820-c0c4-11e4-82d6-fc6bd0957f65.JPG)

**Comment by valienteaidanleary** [comment]
fixed on next push.

**Comment by barbacenasmc** [comment]
Cannot test due to a blocker issue - https://github.com/johnpelquingua/freightbit-logistics/issues/483

**Comment by JMXPSX** [comment]
Added Inland Freight Officer the ability to view Freight Planning albeit the capability to edit and create Freight related documents

**Comment by Leirum** [comment]
Issue fix was already verified.
