### ISSUE TITLE
IFO user can access the link for freight plan but page displays blank

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#465]
Steps to replicate:
1. Login as IFO user.
2. Enter this link on the URL - http://eios.ernest.com.ph/operations/viewSeaFreightList.action

Actual result: Page displays blank
Expected result: User should be able to see the freight plan page but has viewing rights only.
![ifo-no-freight-plan_20150302](https://cloud.githubusercontent.com/assets/7791554/6434491/3267d9e8-c0c5-11e4-8031-e8c6cdcf168d.JPG)

**Comment by JMXPSX** [comment]
Added Inland Freight Officer the ability to view Freight Planning albeit the capability to edit and create Freight related documents

**Comment by Leirum** [comment]
Issue fix was already verified.
