### ISSUE TITLE
IFO user dashboard has no vessel schedule sub-menu

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#466]
Steps to replicate:
1. Login as IFO user.
2. Click the operations module.

Actual result: There is no sub-menu for vessel schedule
Expected result: There should be a sub-menu for vessel schedule.
![ifo-no-freight-plan_20150302](https://cloud.githubusercontent.com/assets/7791554/6434523/e4a0852e-c0c5-11e4-9031-89c5a5332335.JPG)

**Comment by valienteaidanleary** [comment]
fixed on next push.

**Comment by barbacenasmc** [comment]
Cannot test due to a blocker issue - https://github.com/johnpelquingua/freightbit-logistics/issues/483

**Comment by JMXPSX** [comment]
Corrected on next push. Given the ability for the Inland Freight Officer to view Vessel Schedules only but cannot edit and delete them. This is needed to have an effective planning for Actual Pick-up and Delivery

**Comment by Leirum** [comment]
Issue fix was already verified.
