### ISSUE TITLE
Add Items: Success message was in color red

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#467]
Steps to replicate:
1. Add a new booking.
2. On the page 2 of add booking form, add 1 containter/item.

Actual result: Success message was in color red.
Expected result: Success message should be in color green.

![image](https://cloud.githubusercontent.com/assets/7791554/6437294/ae279cda-c0f7-11e4-97b2-2ee27bbf19f1.png)

**Comment by knarceo** [comment]
Fixed on next push

**Comment by valienteaidanleary** [comment]
fixed on next push.

**Comment by barbacenasmc** [comment]
Issue can no longer be replicated.
