### ISSUE TITLE
Add Booking Item: Quantity was cleared after updating an item

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#468]
Steps to replicate:
1. Add a new booking.
2. On the page 2 of the add booking form, add a new container/item.
3. Once the container/item was added to the list, click the edit icon corresponding to it.
4. On the edit item details form, click OK button.

Actual result: Page reloads and the quantity of the item was cleared.
Expected result: The quantity of the item should display.

![image](https://cloud.githubusercontent.com/assets/7791554/6437383/3dec8852-c0f9-11e4-9da9-e02715b5db90.png)

**Comment by knarceo** [comment]
Fixed on next push.

**Comment by barbacenasmc** [comment]
Issue can no longer be replicated.
