### ISSUE TITLE
Edit Booking Item: Commodity field was required

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#469]
Steps to replicate:
1. Add a new booking.
2. On the page 2 of the add booking form, add a new container/item.
3. Once the container/item was added to the list, click the edit icon corresponding to it.
4. If the commodity field has no value, click OK button. Otherwise, clear its value first then click OK.

Actual result: A validation message saying "Please fill-out this field." was displayed.
Expected result: Saving of changes should proceed and no validation message should display.

![image](https://cloud.githubusercontent.com/assets/7791554/6437481/8885f2d0-c0fa-11e4-8090-160f09ec4cbe.png)

**Comment by valienteaidanleary** [comment]
fixed on next push.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
