### ISSUE TITLE
Error page was displayed after adding another booking item

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#470]
Steps to replicate:
1. Add a new booking.
2. On the page 2 of the add booking form, add a new container/item.
3. Once the container/item was added to the list, click the edit icon corresponding to it.
4. On the edit item details form, click OK button.
5. Try to add another item to the list.

Actual result: After clicking "Add Container to List" or "Add Item to List", error page was displayed.
Expected result: Adding of item should succeed.

![image](https://cloud.githubusercontent.com/assets/7791554/6437515/ef421ff8-c0fa-11e4-9abd-9d523c29119f.png)

**Comment by knarceo** [comment]
Fixed on next push.

**Comment by barbacenasmc** [comment]
Issue can no longer be replicated.
