### ISSUE TITLE
Add Booking: Modal displayed after clicking cancel from page 1 and page 2 are different

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#473]
Steps to replicate:
1. Navigate to add booking form.
2. Click the cancel button at the bottom of the page.
3. Fill-out the form to proceed to next page.
4. Click the cancel button at the bottom of the page.

Actual result: "No" button on modal from page 1 is white while on page 2, it is blue.
Expected result: "No" button on page 2 should also be white.

**Page 1:**
![image](https://cloud.githubusercontent.com/assets/7791554/6455054/5e84d358-c18a-11e4-87b2-0d11b2b1b365.png)

**Page 2:**
![image](https://cloud.githubusercontent.com/assets/7791554/6455080/8b111abc-c18a-11e4-8b3b-e31ab6daa8eb.png)

**Comment by valienteaidanleary** [comment]
fixed on next push.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
