### ISSUE TITLE
Add Booking: Error page was displayed when clicked "Next" without any input on the form

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#474]
Steps to replicate:
1. Navigate to add booking form.
2. Do not fill-out any field on the form.
3. Click "Next" button.

Actual result: Error page was displayed.
Expected result: Validation message on the first required field should display.

![image](https://cloud.githubusercontent.com/assets/7791554/6455108/db53cfc4-c18a-11e4-9b06-421c089640ba.png)

**Comment by barbacenasmc** [comment]
Issue can still be replicated:
![image](https://cloud.githubusercontent.com/assets/7791554/6497395/f8980312-c319-11e4-988c-5fbe5f58d0b3.png)

**Comment by knarceo** [comment]
Thats weird mam, my next button on the live site was disabled because it has validations.

**Comment by barbacenasmc** [comment]
But it was enabled on my end. Please see below:
![image](https://cloud.githubusercontent.com/assets/7791554/6497778/321d98cc-c31f-11e4-9b81-5845cd7b8bf8.png)

To replicate this, click the new booking button on the booking module. Once the form displays, scroll down and do not click anything on the form. But when you click any field on the form, that's the only time when the "Next" button becomes disabled.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
