### ISSUE TITLE
IFO user can access the link for vessel schedule but page displays blank

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#475]
Steps to replicate:
1. Login as IFO user.
2. Enter this link on the URL - http://localhost:8080/freightbit/operations/viewVesselSchedules.action

Actual result: Page displays blank
Expected result: User should be able to see the vessel schedule page but has viewing rights only.

![image](https://cloud.githubusercontent.com/assets/7791554/6455315/8b99d5a2-c18d-11e4-9149-f4b31f1c9d09.png)

**Comment by JMXPSX** [comment]
Added the ability for IFO to view for the vessel schedule but remove ability to edit and delete vessel schedules

**Comment by Leirum** [comment]
Issue fix was already verified.
