### ISSUE TITLE
IFO user cannot update status of a shipment

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#476]
Steps to replicate:
1. Login as IFO.
2. Navigate to shipment monitoring page.
3. Try to update the status of a booking item.

Actual result: 404 page was displayed after clicking "Yes" from the confirmation message.
Expected result: Updating of status should succeed.

![image](https://cloud.githubusercontent.com/assets/7791554/6455485/65bf1dfe-c18f-11e4-8739-ce4c66944325.png)

**Comment by johnpelquingua** [comment]
Hi Shiela, for this issue as per Sir Jan said during our meeting last time, only the admin can update the shipment status. Thanks!

**Comment by JMXPSX** [comment]
As for my understanding, Freight Operations Manager can change mostly all shipment status, Freight Operations Officer for all Sea voyage related statuses and Inland Freight Officer are for land related statuses only.

**Comment by Leirum** [comment]
Issue fix was already verified.
