### ISSUE TITLE
IFO user has no permission to access vendor module

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#477]
Steps to replicate:
1. Login as IFO.
2. Enter this URL on the address bar : 
**Localhost** - http://localhost:8080/freightbit/vendor/viewVendors.action
**Live Site** - http://eios.ernest.com.ph/vendor/viewVendors.action

Actual result: 404 page was displayed. Moreover, there is no vendor module displayed on the user's dashboard.
Expected result: User should have permission to access vendor module but can access trucking vendors only.

![image](https://cloud.githubusercontent.com/assets/7791554/6455590/fca8d876-c190-11e4-8fc0-cb22c7542bc7.png)

**Comment by JMXPSX** [comment]
I would also like to add that Inland Freight Officer Role can only add and edit Trucking vendors only.

**Comment by Leirum** [comment]
Issue fix was already verified.
