### ISSUE TITLE
IFO user can access consolidation page

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#478]
Steps to replicate:
1. Login as IFO.
2. Enter this URL on the address bar : 
**Localhost** - http://localhost:8080/freightbit/operations/viewConsolidationContainerList.action
**Live Site** - http://eios.ernest.com.ph/operations/viewConsolidationContainerList.action

Actual result: Consolidation page was displayed.
Expected result: User should have no permission to access consolidation page.

![image](https://cloud.githubusercontent.com/assets/7791554/6455621/87abccee-c191-11e4-879c-3a44805ee2ae.png)

**Comment by JMXPSX** [comment]
I believe Inland Freight Officer is the one who is in charge of consolidation of items to containers since the this role mostly handles all inland vendors, trucks and container related transactions...

**Comment by barbacenasmc** [comment]
Issue can no longer be replicated.
