### ISSUE TITLE
IFO user has no permission to edit his own profile

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#479]
Steps to replicate:
1. Login as IFO user.
2. Go to edit profile page:
**Localhost** - http://localhost:8080/freightbit/core/loadEditUserProfile.action
**Live site** - http://eios.ernest.com.ph/core/loadEditUserProfile.action

Actual result: 404 page was displayed.
Expected result: Edit profile page should be displayed.

![image](https://cloud.githubusercontent.com/assets/7791554/6455686/6d8bef46-c192-11e4-8156-ea63e94a359c.png)

**Comment by Leirum** [comment]
Issue fix was already verified.
