### ISSUE TITLE
Freight and dispatch planning details of a cancelled on-going booking still exist

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#480]
Note: Used FCL to cover freight and dispatch planning.

Steps to replicate:
1. Cancel a booking with an ongoing status. (This presumes that the booking has already gone through freight and dispatch planning.)
2. Approve again the booking.
3. Navigate to freight plan page.
4. Open the previously approved booking.

Actual result: The previous details for freight and dispatch planning still exists.
Expected result: Once a booking was cancelled, all the related planning details should also be cleared.

![image](https://cloud.githubusercontent.com/assets/7791554/6456266/f25f359a-c19a-11e4-8f31-4f39ba7e0770.png)

**Comment by knarceo** [comment]
Cancel will not delete any associated order items and booking however if the user deletes the booking instead then all orderitems and documents get deleted as well.

This is because of cancelled bookings can still be reinstated unless requested to be changed by Sir Jan. -- Jojo

**Comment by barbacenasmc** [comment]
Hi @knarceo, if that's the case, how will the booking status be changed from "APPROVED" to "ON GOING" if it already has freight planning and dispatch planning details?

**Comment by JMXPSX** [comment]
Booking status changes from "Approved" to "On-Going" once at least one vendor is assigned to one or more of its Order Items under Planning Module.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
