### ISSUE TITLE
CRO user can delete a booking

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#481]
Steps to replicate:
1. Login as CRO.
2. Navigate to booking list.
3. Look for a pending or cancelled booking.
4. Click delete icon corresponding to it.
5. Click "Yes" on the confirmation message.

Actual result: Booking was deleted.
Expected result: CRO user should not be allowed to delete or even have an available delete booking icon on his page.

![image](https://cloud.githubusercontent.com/assets/7791554/6457787/cfa6f126-c1b5-11e4-8f47-ec310faf85fd.png)

**Comment by Leirum** [comment]
Issue can no longer be replicated. Delete icon has been removed.
