### ISSUE TITLE
Add New User:Company name of a "Regular User" role is ERNEST

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#482]
Steps to replicate:
1. Login as admin.
2. Navigate to add user page
3. Select "Regular Customer" from user types.

Actual result: Company name is still ERNEST
Expected result: Company name field should disappear because the customer field serves as the company/customer name. (Please check add customer page as reference).

![image](https://cloud.githubusercontent.com/assets/7791554/6460072/1b296138-c1cf-11e4-93d4-ac23ac2b2309.png)

**Comment by ZaX09** [comment]
fixed on next push

**Comment by ZaX09** [comment]
Company label and textfield have been hidden regardless of user type.

**Comment by Leirum** [comment]
Issue fix was already verified.
