### ISSUE TITLE
404 Page was displayed when IFO user logged in

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#483]
Steps to replicate:
1. Admin, create a new IFO account.
2. Login to the previously created IFO user account.

Actual result: 404 page was displayed. Also tried to access URLs of other modules but same thing happens.
Expected result: IFO user should be able to login.

![image](https://cloud.githubusercontent.com/assets/7791554/6496560/4e74165e-c310-11e4-8f17-e87952661184.png)

**Comment by JMXPSX** [comment]
This is now working

**Comment by Leirum** [comment]
Issue fix was already verified.
