### ISSUE TITLE
Edit Consignee Contact: Error page was displayed after saving

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#484]
Steps to replicate:
1. Navigate to customer module.
2. View the profile of an existing consumer.
3. Click the consignee's tab.
4. Click the view information icon corresponding to an existing consignee on the list.
5. On the consignee profile, click edit icon corresponding to an existing contact person.
6. On the edit contact person page, click Save.

Actual result: Error page was displayed.
Expected result: Page should go back to consignee profile page.

![image](https://cloud.githubusercontent.com/assets/7791554/6497226/c65fb19e-c317-11e4-8842-445b4c4405be.png)

**Comment by johnpelquingua** [comment]
Fixed. Please test again, I've updated the live site. Thank you!

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
