### ISSUE TITLE
Error page was displayed when viewed container management page

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#485]
Steps to replicate:
1. Login as admin.
2. Click "Container Management" under Yard Management menu.

Actual result: Error page was displayed.
Expected result: List of containers should display.

![image](https://cloud.githubusercontent.com/assets/7791554/6497633/49c89064-c31d-11e4-8c64-733ec5871e9c.png)

**Comment by johnpelquingua** [comment]
Fixed. Please test again, I've updated the live site.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
