### ISSUE TITLE
Series number in Add Documents modal has no character limit

### ISSUE THREAD

**Issue by ZaX09** [johnpelquingua/freightbit-logistics#486]
Steps to replicate:
1. Go to Pending Documents
2. Choose any of the documents and click [View Documents]
3. Click the [Add Outbound Document] button

![issue](https://cloud.githubusercontent.com/assets/9165543/6611561/73465d00-c8a8-11e4-9325-9c13d793b0e8.JPG)

Expected Result: Series number must have a defined character limit
Actual Result: Series number can be filled with infinite characters

**Comment by JMXPSX** [comment]
Done

**Comment by Leirum** [comment]
Issue fix was already verified.
