### ISSUE TITLE
View User Account: All permissions were displayed with unnecessary checkboxes

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#487]
Steps to replicate:
1. Navigate to the list of users.
2. Click view icon corresponding to any existing user account.
3. Observe the permissions section.

Actual result: All permissions were displayed with unnecessary checkboxes
Expected result: Only the permission associated with the user should be displayed and there should be no checkboxes at all.
![image](https://cloud.githubusercontent.com/assets/7791554/6794704/09355d32-d210-11e4-8eac-1cc0da5cea90.png)

**Comment by JMXPSX** [comment]
Permission Checklist temporarily hidden as one permission per account is decided upon. Further improvement will be applied on version 2.

Disregard this bug
