### ISSUE TITLE
Container and Item Listing displays declared value with 1 zero after decimal point

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#488]
Steps to replicate:
1. Fill-out the page 1 of add booking form.
2. Proceed to next page.
3. Try to add a container/item.
4. Observe the container/item listing.

Actual result: Container and item listing displays declared value with 1 zero after decimal point
Expected result: Container and item listing should display declared value with 2 zeroes after the decimal point

![image](https://cloud.githubusercontent.com/assets/7791554/6794830/60bb5e7e-d212-11e4-884f-95c710edc073.png)

![image](https://cloud.githubusercontent.com/assets/7791554/6794833/67e2c192-d212-11e4-80a6-b2ff9a100bb1.png)

**Comment by knarceo** [comment]
Fixed on next build update of live site :wrench:

**Comment by JMXPSX** [comment]
This was resolved on my git push c7cc4f2

all numeric values no longer shows an additional decimal number after

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
