### ISSUE TITLE
Freight Plan: "Hide Me" column was displayed on LCL tab

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#489]
Pre-condition:
-There should be an existing LCL booking

Steps to replicate:
1. Login as sales.
2. Navigate to freight plan page.
3. Go to LCL tab.
4. Observe the columns available.

Actual result: "Hide Me" column was displayed on LCL tab
Expected result: There should not be a "Hide Me" column displayed
![image](https://cloud.githubusercontent.com/assets/7791554/6794993/a2fdeac0-d214-11e4-96a2-1bd908479d7a.png)

**Comment by JMXPSX** [comment]
Cannot replicate

**Comment by Leirum** [comment]
Issue can still be replicated

![freight list](https://cloud.githubusercontent.com/assets/9795882/7224526/2789668c-e766-11e4-952c-4ad8ff60f790.png)

**Comment by Leirum** [comment]
Issue fix was already verified.
