### ISSUE TITLE
Search Vessel Schedule: Cannot search by shipping company

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#490]
Steps to replicate:
1. Navigate to vessel schedules list.
2. Click "Search Schedule"
3. Click "Search by" field to display the dropdown list.

Actual result: There was no available option for searching by shipping company
Expected result: There should be an available option for searching by shipping company

![image](https://cloud.githubusercontent.com/assets/7791554/6795137/d9c596a0-d216-11e4-9e8b-dd73718b26cd.png)

**Comment by Leirum** [comment]
Issue fix was already verified.
