### ISSUE TITLE
Sales user cannot view the status of the items within a booking

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#491]
Steps to replicate:
1. Login as sales.
2. Go to shipment monitoring.

Actual result: Sales user can only view the status of each booking but has no available option to open each booking and view the status of their items.

Expected result: Sales user should also be able to view the status of the booking items.

![image](https://cloud.githubusercontent.com/assets/7791554/6795316/5c0e19a0-d219-11e4-9e87-4b66c4d8121e.png)

**Comment by Leirum** [comment]
Issue fix was already verified.
