### ISSUE TITLE
Add Booking: Container/Item Information fields are not aligned

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#493]
Steps to replicate:

1. Fill-out the page 1 of add booking form.
2. Proceed to page 2 and observe the fields for adding container/item.

Actual result: Container/Item Information fields are not aligned
Expected result: Container/Item Information fields should be aligned

![image](https://cloud.githubusercontent.com/assets/7791554/6796114/abe0e5b2-d227-11e4-9ed1-f85a404a2588.png)

![image](https://cloud.githubusercontent.com/assets/7791554/6796120/d4f4a22c-d227-11e4-9abd-cf015c570d03.png)

**Comment by JMXPSX** [comment]
DONE

**Comment by Leirum** [comment]
Issue can still be replicated in container information
![screen shot 2015-04-20 at 1 20 42 pm](https://cloud.githubusercontent.com/assets/9795882/7224100/34367ba0-e760-11e4-8112-5475c19ea507.png)

**Comment by ZaX09** [comment]
fixed on next push

**Comment by Leirum** [comment]
Issue fix was already verified.
