### ISSUE TITLE
Add Booking: Cannot add an item because of validation message that displays on weight field even if input was valid

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#494]
Steps to replicate:
1. Fill-out the page 1 of add booking form. Use any service requirement that uses items and not containers.
2. Proceed to the next page.
3. Fill-out the add item form completely.
4. Click "Add Item to List".

Actual result: Validation message was displayed on the weight field saying "Please match the requested format".
Expected result: Validation message should not display and adding of item to list should succeed.

![image](https://cloud.githubusercontent.com/assets/7791554/6796176/0672ba04-d229-11e4-9ded-bd413dd4d46f.png)

**Comment by JMXPSX** [comment]
This was resolved on my git push c7cc4f2

This field is no longer viewable by the user

**Comment by barbacenasmc** [comment]
Issue can still be replicated on LCL and LTL
![image](https://cloud.githubusercontent.com/assets/7791554/6911510/37fb893c-d794-11e4-95e7-522a8cc2d515.png)

**Comment by JMXPSX** [comment]
Issue already been fixed.

**Comment by Leirum** [comment]
Issue fix was already verified.
