### ISSUE TITLE
CRO User: Page redirects to edit booking page when tried to delete a booking

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#495]
Steps to replicate:

1. Login as CRO user.
2. Go to booking list.
3. Try to delete an incomplete, pending or cancelled booking.

Actual result: Page redirects to edit page after confirming the deletion.
Expected result: Deletion of booking should succeed.

![image](https://cloud.githubusercontent.com/assets/7791554/6796284/175b5b44-d22b-11e4-8a62-20cddb4dd4b7.png)

**Comment by Leirum** [comment]
Issue can no longer be replicated.
