### ISSUE TITLE
Shipment Monitoring: Cannot set "Service Complete" even if booking items have "ARRIVED" status

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#496]
Pre-condition: There should be a booking that has an "ON-GOING" status so that it may already be seen in the shipment monitoring list.
**Sample Booking details:**
Freight Type: Shipping
Service Requirement: Rolling Cargo Load
Service Mode: Pier to Pier

Steps to replicate:

1. Navigate to shipment monitoring.
2. Update the status of the items of the preferred booking for 3 consecutive times. (Use queue for departure, in-transit, then, arrived)
3. Go back to booking item list.
4. Click "Set Service Complete" button.

Actual result: A prompt saying that "Statuses of all items must be Arrived/Delivered or one Returned to Origin."
Expected result: Set service complete should succeed. 
![order item list](https://cloud.githubusercontent.com/assets/7791554/6796538/ac77a3aa-d22f-11e4-9156-468588f872ad.png)

**Comment by knarceo** [comment]
Fixed this bug :beetle: on next build update of live site :wrench:

**Comment by barbacenasmc** [comment]
Issue fix was already verified.

**Comment by Leirum** [comment]
Issue needs to be reopened; can still be replicated.

![5](https://cloud.githubusercontent.com/assets/9795882/7744981/550dc832-ffda-11e4-8945-6027bcb2c4d3.png)

**Comment by egmsantos** [comment]
Bug fixed.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
