### ISSUE TITLE
Update Shipment Status: Confirmation message has no appropriate title

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#497]
Steps to replicate:
1. Navigate to shipment monitoring page.
2. Click "Update Status" icon corresponding to a booking.
3. Select the actual date and time.
4. Select a status.
5. Click "Update Status" button.

Actual result: Confirmation message was displayed but has no appropriate title.
Expected result: Confirmation message should be entitled "Update Status" or something more meaningful.

![image](https://cloud.githubusercontent.com/assets/7791554/6797922/ef88e5ba-d242-11e4-8616-5c51808a3aaf.png)

**Comment by knarceo** [comment]
Added on next build update of live site :wrench:

**Comment by barbacenasmc** [comment]
Modal has already a title but "i Warning" still displays.
![image](https://cloud.githubusercontent.com/assets/7791554/6911769/bfbcb1cc-d797-11e4-823e-0c4565dc5a1f.png)

**Comment by Leirum** [comment]
Issue can no longer be replicated.
