### ISSUE TITLE
Add Items to Booking: Volume was not computed

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#498]
Steps to replicate:
1. Fill-out the add booking form and use LCL as service requirement.
2. On the next page, add 1 item to list.

Actual result: Volume was not computed and has no value
Expected result: Volume should be displayed

![image](https://cloud.githubusercontent.com/assets/7791554/6839462/a72848b2-d3a3-11e4-8ead-12b400649122.png)

**Comment by knarceo** [comment]
Fixed on next build update of live site along with issue #488

**Comment by JMXPSX** [comment]
This was resolved on my git push c7cc4f2

Volume now computes correctly

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
