### ISSUE TITLE
Freight Planning: View booking information displays no pick-up and delivery date

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#499]
Steps to replicate:
1. Navigate to freight planning page.
2. Click "View Booking Information" icon.
3. Observe the pick-up and delivery date.

Actual result: View booking information displays no pick-up and delivery date
Expected result: View booking information should display pick-up and delivery date

![image](https://cloud.githubusercontent.com/assets/7791554/6839570/5f39cd4e-d3a5-11e4-8270-4875dbd6831a.png)

**Comment by Leirum** [comment]
Issue fix was already verified.
