### ISSUE TITLE
Fields on add booking displays "Comments" and "Commodity" while in add items form on customer module, it displays "Note" and "Description"

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#500]
Steps to replicate:
1. Fill-out the add booking form.
2. Proceed to the next page, add a new item.
3. Enter "Comments" on the comments field and "Commodity" on the commodity field to mark the difference.
4. Click "Add Item to List"
5. Navigate to customer module.
6. Open the customer profile of the customer used in the booking.
7. Go to items and edit the added item through the booking form.

Actual result: The "Note" column displays the content of comments field and the "Description" column displays the content of the commodity field in the add booking form.

Expected result: Add/Edit booking and Add/Edit Items form should have a uniform label for the previously mentioned fields.

![image](https://cloud.githubusercontent.com/assets/7791554/6839787/d4e3d262-d3a8-11e4-93ba-4d309245d7cd.png)

**Comment by Leirum** [comment]
Issue fix was already verified.
