### ISSUE TITLE
Add Booking: Cannot re-use an existing customer item due to a validation on Item Code

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#501]
Pre-condition:
- There is a customer that has existing items on record.
Steps to replicate:
1. Fill-out the add booking form.
2. On the next page, select the existing customer item from the items dropdown list.
3. Click "Add Item to List" button.

Actual result: Item could not be added to list. A validation message was displayed on item code field saying "Item Code already exists"
Expected result: Addition of item to list should succeed and no validation message on item code field should display.

![image](https://cloud.githubusercontent.com/assets/7791554/6839823/6b73d452-d3a9-11e4-85fc-7c7de01cbc92.png)

**Comment by JMXPSX** [comment]
already fixed on next build

**Comment by JMXPSX** [comment]
This was resolved on my git push c7cc4f2

Item code that does not exist now adds to the customer items and at the same time adds to the items in booking.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
