### ISSUE TITLE
Freight Plan (LCL): Volume was not computed

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#502]
Steps to replicate:
1. Create a booking with LCL as service requirement.
2. Add new items to booking. (Do not use the existing items on the list).
3. Save and approve the booking.
4. Go to freight plan.
5. Go to LCL tab.

Actual result: The previously added and approved booking displays no volume. (Only those booking with re-used customer items displays volume)

Expected result: All items should display its computed volume.

![image](https://cloud.githubusercontent.com/assets/7791554/6839958/83513748-d3ab-11e4-851d-028a2e1d5a2e.png)

**Comment by Leirum** [comment]
Issue fix was already verified.
