### ISSUE TITLE
Change user password form requires admin to enter the current password

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#503]
Steps to replicate:

1. Login as admin.
2. Navigate to users list.
3. Click edit icon corresponding to an existing user account.
4. On the edit page, click "Change Password" link.

Actual result: Change password form was displayed but the admin was asked to enter the current password which the admin might no longer be able to know because the user might change his password on his end. (I think the purpose of this feature is to reset the user's password just in case he/she has forgotten it.

Expected result: Admin should no longer be asked to enter the current password.

![image](https://cloud.githubusercontent.com/assets/7791554/6840217/396a7ffa-d3af-11e4-978c-bccc2a071f70.png)

**Comment by knarceo** [comment]
Fixed on next push in local and cloud

**Comment by Leirum** [comment]
Issue fix was already verified.
