### ISSUE TITLE
Add Item to Bookng: Declared value for containers was incorrect when user 2 or more in quantity

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#504]
1. Login as admin
2. Go to Booking
3. Add booking
4. Save the added booking
5. You will be redirected to booking information
6. Add container information
    Container: 10FT
    Container Qty: 3
    Declared Value: (250,000 x 3) = 750,000
7. Save it
8. On the container listing, there will be 3 records, each of the record will have 
QTy  Cont.    Wgt         Vol.     Declared Value 
1      10 FT    27000.0   42.0  750,000.00        0.00

Actual result: The record displays the sum of the declared value for the whole batch of containers.
Expected result: For each container list, the declared value should be the original declared value not the computed for the whole group of the containers

![image](https://cloud.githubusercontent.com/assets/7791554/6864150/7319e8f0-d498-11e4-9600-c82037d75dd0.png)

**Comment by JMXPSX** [comment]
already fixed on next build

**Comment by JMXPSX** [comment]
This was resolved on my git push c7cc4f2

Values no longer multiply per quantity

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
