### ISSUE TITLE
Freight Plan: Able to assign a booking to a vessel schedule with an arrival time later than the expected delivery time of the booking

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#505]
1. Log in as admin
2. Go to Operations
3. Go to Freight Plans
4. Select a record
5. Click on set vessel schedule
6. Select all the containers
7. Add a vessel schedule
8. On the vessel arrival time, input a date later than the delivery date of the booking
9. Save
10. Select the added vessel schedule 
11. Save the record so that the status will be planning 2.

Actual result: Booking was assigned even if the delivery date is earlier than the vessel arrival time.
Expected result: Booking should not be assigned to vessel schedule with arrival time later than the delivery time.

![image](https://cloud.githubusercontent.com/assets/7791554/6864240/7d8802bc-d499-11e4-84e6-7f434d41be8c.png)

**Comment by JMXPSX** [comment]
description seems a little confusing. At the moment, freight planning is not yet strict when it comes to time compared to date because the client mentioned to remove this aspect as the schedules are all estimates.

**Comment by JMXPSX** [comment]
If the delivery date is Apr. 7 and setting an arrival date later than that like Apr. 8 and onwards. The system will not display it however if set early or on the same date like Apr 7 and before then the vessel schedule will show. Working as intended.

**Comment by JMXPSX** [comment]
Delivery Time compared to Arrival Time especially if set on the same date will not be filtered. Waiting for the client to comment on this if needed to be acted upon

**Comment by barbacenasmc** [comment]
Hi, I would like to follow up the update about this. Thanks for your inputs.

**Comment by barbacenasmc** [comment]
No longer an issue as of team's decision.
