### ISSUE TITLE
Page breadcrumb navigation does not include the module name

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#506]
1. Log in as admin
2. Go to accounts
3. You will see the page breadcrumb navigation as 
Dashboard // Accounts // User // User List
4. Go to any modules (Operations, yard mgt, docs)
5. Check on the page breadcrumb navigation
6. The breadcrumb navigation is incomplete.

Actual result: The breadcrumb navigation is incomplete.
Expected result: The breadcrumb navigation for all the modules should be consistent and should properly follow the format so that the user will not be confused in which module he / she is currently at.

![image](https://cloud.githubusercontent.com/assets/7791554/6864268/e443c5ae-d499-11e4-8944-d6b4339661d1.png)

**Comment by JMXPSX** [comment]
I am the one who fixed that

**Comment by Leirum** [comment]
Issue fix was already verified.
