### ISSUE TITLE
Add Customer: Email with .com.ph is not accepted

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#507]
Steps to replicate:
1. Log in as admin
2. Go to customers
3. Add new customer
4. Fill out the necessary details
    email: emaymarino@gmail.com.ph
5. Click save

Actual result: The validation should include emails with .com.ph
Expected result: The validation does not accept emails with .com.ph

![image](https://cloud.githubusercontent.com/assets/7791554/6864309/77ea5976-d49a-11e4-94a7-3c1086906f0e.png)

**Comment by knarceo** [comment]
Issue was fixed in this commit number: 6aa9035634ef4ab587a24d92957c3dc689ec09c4

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
