### ISSUE TITLE
Add Vendor: No Data validation. Data table is destroyed.

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#508]
Steps to replicate:
1. Log in as admin
2. Go to vendor
3. Add a new vendor
4. Fill up the fields:
    CODE: 000
    Company Name: "<script>alert();</script>
    Service Area: Manila
5. Click Save.

Actual result: The data should be validated or the inputted data should be displayed properly without affecting the layout of the page table.

Expected result: The vendor's list table is no longer displaying the correct data for the vendors list. The page can still get the total number of vendors but can only display the first row's first 2 cells. The following cells on the saved data are no longer displayed.

![1](https://cloud.githubusercontent.com/assets/7791554/6864411/ec31679c-d49b-11e4-9e9e-6e3f3545ba73.png)

**Comment by JMXPSX** [comment]
Unable to replicate.

Three zeroes is valid as accepted input is alpanumberic. Reason for this is for company names that is similar to 2GO which has a number in their company code.

**Comment by Leirum** [comment]
Issue cannot be replicated.
