### ISSUE TITLE
Add Customer: User can add duplicate address

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#509]
Steps to replicate:

1. Log in as admin
2. Go to customers
3. Add new customer
4. Click the details icon for the customer
5. Add a contact person
6. Add a pickup address
7. Add pickup address as 43 Poblacion Calumpit Bulacan 3003
8. Go to booking
9. On the customer information, click the add address 
10. Enter the same address as above.
11. Click save.

Actual result: The system accepts duplicate record for the address field
Expected result: There should be a validation for duplicate record for the pickup address

![4](https://cloud.githubusercontent.com/assets/7791554/6864448/47d241fc-d49c-11e4-804c-27df2fd492f8.png)

**Comment by Leirum** [comment]
By replicating this, after the user had add the same address, the module will be refreshed and all the input data (except for the booking information panel) will be removed from its current fields, plus the drop down list for company retrieves no data.

**Comment by egmsantos** [comment]
Issue fixed and verified
![eios_626](https://cloud.githubusercontent.com/assets/12589800/9127908/f8cb213a-3cf3-11e5-806a-ac1ae9869987.png)
