### ISSUE TITLE
Add Booking: Customer Contact Person and Pick Up Address retains the values of previous selected customer even after the whole form was reset

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#510]
Steps to replicate:
1. Log in as admin
2. Go to Booking
3. Add New Booking
4. Select the values on the menu for the basic information
5. Note that the customer contact person will be loaded as well as the pick up address
6. Now Go to the basic information and select freight type as trucking or shipping. (Change the freight type)
7. Go to customer contact person and address.
8. The initial display value for the menu in customer contact is blank
9. Click on any of the menu, the previous values for the previous selected customer is retained

Actual result: Customer Contact Person and Pick Up Address retains the values of previous selected customer even after the whole form was reset

Expected result: The customer contact person and the pick up address should not display anything since the whole form was reset. (Customer is not selected)

**Comment by JMXPSX** [comment]
Fixed in Github push #0604ece

**Comment by Leirum** [comment]
Issue fix was already verified.
