### ISSUE TITLE
Add Booking: Pickup address and delivery address is disabled upon selecting shipping as the freight type

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#512]
Steps to replicate:
1. Login as admin
2. Go to booking
3. Add new booking
4. Fill up the following input for the booking form
    Freight type: Shipping
    Customer: Any customer with contact person and consignee
5. Notice that on the Customer and Consignee pickup address and delivery address is disabled.

Actual result: Pickup address and delivery address is disabled upon selecting shipping as the freight type
Expected result: The customer contact person's pick up address should be enabled.
The customer consignee contact person's delivery address should be enabled.

**Comment by JMXPSX** [comment]
There are really no associated address for this kind of transaction because the Pier will be the address for origin and destination

**Comment by JMXPSX** [comment]
Working as intended

**Comment by Leirum** [comment]
Issue can no longer be replicated.
