### ISSUE TITLE
Format on the declared has wrong format after changing the container quantity

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#513]
Steps to replicate:
1. Login as admin
2. Go to Booking
3. Add booking
4. Save the added booking
5. You will be redirected to booking information
6. Update the container information
7. Change the value of the container count to 2
8. Notice that the value for 250,000 will be 500000
9. Change back the value of the container count to 1
10. The value for the declared value will be 250000

Actual result: Format for declared value is not consistent. 
Expected result: Proper formatting should be applied for monetary value
![8](https://cloud.githubusercontent.com/assets/7791554/6864550/def95b64-d49d-11e4-88bf-6f438f597354.png)

**Comment by JMXPSX** [comment]
already fixed on next build

**Comment by JMXPSX** [comment]
This was resolved on my git push c7cc4f2

Declared Values now correctly displays money values with comma and decimals

**Comment by Leirum** [comment]
Issue fix was already verified.
