### ISSUE TITLE
Add Booking: Invalid date caused HTTP Status 404

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#514]
Steps to replicate:
1. Login as admin
2. Go to Booking
3. Add booking
4. Fill up the fields
5. On the pickup date and delivery date, type in 1111111111111111111111111111
6. Fill up the customer contact person and consignee 
7. Save
8.HTTP Status 404 - No result defined for action com.sr.apps.freightbit.order.action.OrderAction and result input will prompt the screen

Actual result: HTTP Status 404 - No result defined for action com.sr.apps.freightbit.order.action.OrderAction and result input is encountered
Expected result: There should be a validation for proper date format
![10](https://cloud.githubusercontent.com/assets/7791554/6864559/228ff5c2-d49e-11e4-921d-d18ba567ad21.png)

**Comment by knarceo** [comment]
Fixed on next push in local and cloud.

**Comment by Leirum** [comment]
Issue fix was already verified.
