### ISSUE TITLE
User can approve the booking even if it still incomplete

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#515]
Steps to replicate:
1. Login as admin
2. Go to Booking
3. Add booking
4. Fill up the form with proper data and save the booking
5. You will be redirected to the booking information page
6. Do not add any container
7. Go back to the booking home page
8. You will see that the record you added is labeled as incomplete
9. Click on the x icon to cancel the booking
10. Cancel the booking
11. After cancelling the booking, there will be a check icon
12. CLick on it
13. Approve the booking
14. Booking is approved

Actual result: User can approve the booking even if it still incomplete
Expected result: The booking should not be approved if it is incomplete

![11](https://cloud.githubusercontent.com/assets/7791554/6864573/7c25ab0e-d49e-11e4-8fe7-ba473de7a1f5.png)

**Comment by JMXPSX** [comment]
Fixed in Github push #0604ece

**Comment by Leirum** [comment]
Issue fix was already verified.
