### ISSUE TITLE
Freight Plan: Wrong message after adding a schedule for a vessel

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#516]
Steps to replicate:
1. Log in as admin
2. Go to Operations
3. Go to Freight Plan
4. Click on a booking record
5. Select the containers included in the booking
6. Select the all containers via checkbox
7. Click on Set vessel schedule
8. Click add schedule (vessel)
9. Fill up the form with valid data
10. Click Save
11. Vendor sucessfully added! appeared
12. This should be vessel schedule successfully added

Actual result: Vendor successfully added is displayed 
Expected result: Should display "Vessel schedule successfully added".
![13](https://cloud.githubusercontent.com/assets/7791554/6864602/e7e4a9d0-d49e-11e4-8349-d3cad79ac50a.png)

**Comment by Leirum** [comment]
Issue fix was already verified.
