### ISSUE TITLE
Freight Plan: Currently selected booking information disappeared after adding a vessel schedule

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#517]
Steps to replicate:
1. Log in as admin
2. Go to Operations
3. Go to Freight Plan
4. Click on a booking record
5. Select the containers included in the booking
6. Select the all containers via checkbox
7. Click on Set vessel schedule
8. Click add schedule (vessel)
9. Fill up the form with valid data
10. Click Save
11. Booking information is added. 
http://eios.ernest.com.ph/operations/addVesselScheduleInPlanningBulk.action#focusHere

Make sure that the destination and origin matches the booking information's origin and departure.

Actual result: Currently selected booking information disappeared after adding a vessle schedule
Expected result: The schedule should be saved and the booking information display should be retained

![14](https://cloud.githubusercontent.com/assets/7791554/6864631/33ca6b3c-d49f-11e4-9d3d-1b8215a56f1b.png)

**Comment by Leirum** [comment]
Issue fix was already verified.
