### ISSUE TITLE
Button on set vessel schedule is still enabled even if the required status for the booking is planning 2

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#518]
Steps to replicate:
1. Log in as admin
2. Go to Freights Planning
3. Select a record with ONGOING status 
4. View the details
5. There is a button set Vessel
6. Select the booking via checkbox
7. Click the set vessel button
8. There is an error message displayed, "Item must be planning 1 status"

Actual result: The button is still Clickable. Having the button enabled even if the status is planning 2 can confuse the user if he/she wants to edit the vessel vendor.
Expected result: The button should be disabled since the status is already planning 2.

**Comment by JMXPSX** [comment]
The reason for this is for multiple order items inside the booking. There is no way yet for the system to disable the button if ex. the first orderitem = planning 1 and second orderitem = planning 2. Disabling the button is inconsistent when encountering this scenario of orderitems with different statuses.

**Comment by barbacenasmc** [comment]
This is noted. Thanks.
