### ISSUE TITLE
Shipment Monitoring: Error page was displayed after clicking Set Status icon

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#519]
Steps to replicate:
1. Log in as admin
2. Go to dispatch Plan
3. Select a record with status planning 2
4. If there are no record with status planning 2, create a booking and update it's record to status planning 2
5. Go to Operations > Dispatch planning
6. Select the record
7. Click the Set Status button (No checkboxes will be selected)
8. You will be redirected to a page with error

Actual result: 
http://eios.ernest.com.ph/operations/viewStatusListItemsNullError is returned by the page
Expected result: There should be no error upon Clicking the set status button
![17](https://cloud.githubusercontent.com/assets/7791554/6864721/39db8c9e-d4a0-11e4-83e7-7f161daa9795.png)

**Comment by Leirum** [comment]
Issue fix was already verified.
