### ISSUE TITLE
Dispatch Plan: Page loads to Add Order Info even if the user did not Click on the YES or NO validation for the same date field on trucking

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#520]
Steps to replicate:
1. Log in as admin
2. Go to Booking
3. Add new booking
4. Select booking type as trucking
5. Set the other fields as valid data
6. Set the pickup date and delivery date equal
7. Click save
8. A dialog box will prompt
9. Do not Click on yes or no
10. Wait for the page to redirect to Add Order Info

Actual result: Page loads to Add Order Info even if the user did not Click on the YES or NO validation for the same date field on trucking
Expected result: The page should wait for the user's response before it redirects to the Add Order Info page

![18](https://cloud.githubusercontent.com/assets/7791554/6864765/bd635682-d4a0-11e4-8d72-6f72aa4de17d.png)

**Comment by knarceo** [comment]
Fixed on next local push.

**Comment by Leirum** [comment]
Issue fix was already verified.
