### ISSUE TITLE
Cancel button should be renamed close because it confuses the user about closing / cancelling the schedule on the calendar

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#521]
Steps to replicate:
1. Log in as admin
2. Go to dashboard
3. Click on any event on the calendar
4. A dialog box with info will prompt you
5. Notice that the cancel button operates as close the window

Actual result: The button is named as cancel. This confuses the user about cancelling the schedules on that day.
Expected result: The button should be renamed as close because it only closes the window
![19](https://cloud.githubusercontent.com/assets/7791554/6864784/067be014-d4a1-11e4-8108-d3f3d1f8b4a1.png)

**Comment by knarceo** [comment]
Issue fixed in this commit number 09b935c154251bc9e6b713e5d23c650208962aad

**Comment by Leirum** [comment]
Issue fix was already verified.
