### ISSUE TITLE
There is no maximum value for the Volume of a trucking booking

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#522]
Steps to replicate:
1. Log in as admin
2. Go to booking
3. Add new booking
4. Fill out the form with valid data
5. In the booking information, under the volume textbox type in 99999999999999
6. Save the record

Actual result: Volume accepts the 9999999999999999. Displays the data in 1E92 format
Expected result: There should be a maximum value for the volume
![20](https://cloud.githubusercontent.com/assets/7791554/6864816/4f2a7d84-d4a1-11e4-882a-54eccfb99d18.png)

**Comment by JMXPSX** [comment]
This was resolved on my git push c7cc4f2

Volume field is now hidden to the user

**Comment by barbacenasmc** [comment]
Issue can still be replicated. Please try Trucking as freight type and use Full Truck Load as service requirement.

![image](https://cloud.githubusercontent.com/assets/7791554/6910917/90be3ee6-d78c-11e4-8d64-8972ea68cd59.png)

**Comment by JMXPSX** [comment]
Fixed in Github push #0604ece

**Comment by Leirum** [comment]
Issue fix was already verified.
