### ISSUE TITLE
Notification checkboxes were reset when editing a booking

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#523]
Steps to replicate:

1. Navigate to booking list.
2. Click edit icon corresponding to an existing booking.
3. Observe the notification checkboxes.

Actual result: Notification checkboxes were reset
Expected result: The notification type for the booking should be checked.

![image](https://cloud.githubusercontent.com/assets/7791554/6911479/c47a0d58-d793-11e4-984b-8e5d1980e89a.png)

**Comment by JMXPSX** [comment]
Fixed in Github push #0604ece

**Comment by Leirum** [comment]
Issue fix was already verified.
