### ISSUE TITLE
Bulk dispatch planning for origin displays no form for selecting truck details

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#525]
Steps to replicate:
1. Navigate to dispatch plan.
2. Open an existing booking with planning 2 status.
3. Check all the available items and click "Set Vendor" button.

Actual result: There was no form displayed for selecting truck details.
Expected result: Form for selecting truck details should display.
(Note: It can be replicated with booking with shipping freight type)
![dispatch plan 4](https://cloud.githubusercontent.com/assets/7791554/6911722/fc828786-d796-11e4-8afe-664a3fc87b08.png)
![Uploading Dispatch Plan (3).png . . .]()

**Comment by Leirum** [comment]
Issue can no longer be replicated.
