### ISSUE TITLE
Edit booking item form has no item code, length, height and width fields and displays volume field

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#526]
Steps to replicate:
1. Add a new booking with LCL or LTL as service requirement.
2. Proceed to next page.
3. Add an item to the list.
4. Click edit icon corresponding to the item on the list.

Actual result: Edit booking item form has no length, height and width fields and displays volume field.
Expected result: There should be item code, length, height and width fields and volume field should not be displayed. Moreover, the labels "Name" and "Quantity" should be "Item Name" and "Item Quantity" to be consistent.

![image](https://cloud.githubusercontent.com/assets/7791554/6911922/055c6fe0-d79a-11e4-9e8a-4a3bdf051166.png)

**Comment by JMXPSX** [comment]
redesigned and corrected on Github pushes 
#80841FF
#fef1590

**Comment by Leirum** [comment]
Issue fix was already verified.
