### ISSUE TITLE
Add Booking Form: User can add more than 1 contact person for a consignee

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#527]
Steps to replicate:
1. Navigate to add booking form.
2. Fill-out the form and select a customer which already has a consignee with contact person.
3. Scroll down to the consignee information section at the bottom.

Actual result: Add contact person button is still available. And user can add more contact persons for 1 consignee.
Expected result: Add contact person button should no longer be available if there is an existing consignee contact person already.

![image](https://cloud.githubusercontent.com/assets/7791554/6912118/c295704a-d79d-11e4-96ba-1e5cc9a13492.png)

![image](https://cloud.githubusercontent.com/assets/7791554/6912116/be87a43c-d79d-11e4-8f6b-b63458987016.png)

**Comment by knarceo** [comment]
Issue was fixed in this commit number a5d185a

**Comment by Leirum** [comment]
Issue fix was already verified.
