### ISSUE TITLE
Wrong status from Dispatch order list and on Dispatch plan items. The status on dispatch order is approved while in the dispatch plan items is cancelled

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#528]
**Steps to replicate**
1. Log in as admin
2. Go to booking
3. Add a new booking - trucking only
4. Fill up proper data 
5. Add container / trucking info
6. Go to booking list
7. Cancel the created data
8. Approve the created data
9. Go to operations dispatch plan
10. Go to trucking
11. Notice the status on the record is approved
12. CLick to view the record,
13. The status is now cancelled

**Actual Result**
Status mismatch on page 21A and 21B (see picture)

![21a](https://cloud.githubusercontent.com/assets/9795882/6999390/d78c8022-dc3b-11e4-8262-1b26b2db9b71.png)

![21b](https://cloud.githubusercontent.com/assets/9795882/6999395/f437010c-dc3b-11e4-858b-1f6a22383cfc.png)

**Expected Result**
The status of a booking should be displayed properly and accurately.

**Comment by knarceo** [comment]
Fixed on next push in local and cloud

**Comment by Leirum** [comment]
Issue fix was already verified.
