### ISSUE TITLE
Volume is not computed for Trucking Less Truck Load

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#529]
**Steps to replicate**
1. Log in as admin
2. Go to booking
3. Add a trucking service booking
4. Set the Service requirement as less truck load 
5. Save the record
6. On booking information, fill out the data same as the data on the picture
7. Save the data 
8. On the records of the container / truck, there is no computation for the volume.

**Actual Result**
Volume is not computed

![22](https://cloud.githubusercontent.com/assets/9795882/6999403/48f17754-dc3c-11e4-99a0-be522a14d396.png)

**Expected Result**
Volume should be computed since the L x W x H was given by the user.

**Comment by knarceo** [comment]
Restricted it into three digits only, since it is the common digit values used for length, width, and height.

**Comment by Leirum** [comment]
Issue fix was already verified.
