### ISSUE TITLE
Lenght, width and height as specified on the form Item information is not reflected on the edit form for the edit item information

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#530]
**Steps to replicate**
1. Log in as admin
2. Go to booking
3. Add a trucking service booking
4. Set the Service requirement as less truck load 
5. Save the record
6. On booking information, fill out the data same as the data on the picture
7. Save the data 
8. On the records of the container / truck, click edit
9. Notice that there is no field for the length height and width

**Actual Result**
Length, width and height as specified on the form Item information is not reflected on the edit form for the edit item information

![23](https://cloud.githubusercontent.com/assets/9795882/6999415/b3d5ff68-dc3c-11e4-9dbf-4f9c0c98f721.png)

**Expected Result**
Since the user inputs the L x W x H, upon editing the record, the system should also offer the same field as the item information entry form.

**Comment by knarceo** [comment]
The modal popup was changed into redirecting it into a page so this means that this issue was fixed. :trollface:

**Comment by Leirum** [comment]
Issue fix was already verified.
