### ISSUE TITLE
There is no maximum value for the length, width and height and declared value . Weight also has invalid format. 

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#531]
**Steps to Replicate**
1. Log in as admin
2. Go to booking
3. Add a trucking service booking
4. Set the Service requirement as less truck load 
5. Save the record
6. On booking information, fill out the data same as the data on the picture
7. Save the data 
8. Data was saved. No validation for maximum value input for the fields.

**Actual Result**
There is no maximum value for the length, width and height and declared value . Weight also has invalid format. 

![24](https://cloud.githubusercontent.com/assets/9795882/6999423/ee0970d4-dc3c-11e4-9676-6aa2c0460ae4.png)

**Expected Result**
There should be maximum value for the length, width and height as well as the declared value of the cargo

**Comment by knarceo** [comment]
Restricted it into five digits only, since it is the common digit values used for weight, also in length width and height. Decimals are rounded in actual encoding as per Sir Jan so there's no need to add it.

**Comment by Leirum** [comment]
Issue fix was already verified.
