### ISSUE TITLE
Able to assign a booking to a dispatch schedule with an arrival time later than the expected delivery time of the booking

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#532]
**Steps to Replicate**
1. Log in as admin
2. Go to Operations
3. Go to Dispatch Plans
4. Select a record - trucking record
5. Click on set vendor
6. Add a dispatch schedule with a delivery or arrival date later than the order delivery date

**Actual Result**
Booking was assigned even if the delivery date is earlier than the vessel arrival time.

![25](https://cloud.githubusercontent.com/assets/9795882/6999446/a567c5fa-dc3d-11e4-9294-42134cc3014e.png)

**Expected Result**
Booking should not be assigned to dispatch schedule with arrival time later than the delivery time.

**Comment by JMXPSX** [comment]
Somehow the client let us remove the restrictions on dates as schedule can be changed.

They only have us edit the date and time at anytime

**Comment by barbacenasmc** [comment]
This is noted. Thanks.
