### ISSUE TITLE
The record does not show which type of contact person the current record is

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#533]
**Steps to Replicate**
1. Log in as admin
2. Go to vendors
3. Add vendor
4. Add contact person
5. Add contact person for each type (Shipper, Bill to, solicitor)
6. Go to contact person list, the record does not show which type of contact person the current record is

**Actual Result**
the record does not show which type of contact person the current record is

![26](https://cloud.githubusercontent.com/assets/9795882/6999480/124cc796-dc3f-11e4-9a1d-d5402304374c.png)

**Expected Result**
Display the type of Contact Person on the table. (Shipper/BillTo/Solicitor)

**Comment by knarceo** [comment]
Fixed on next push in cloud and localhost

**Comment by Leirum** [comment]
Issue fix was already verified.
