### ISSUE TITLE
No View Information Icon is Displayed in the Action Panel for Contact Person Lists.

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#534]
**Steps to Replicate**
1. Log in as admin
2. Go to vendors
3. Add vendor
4. Add contact person
5. Add contact person for each type (Shipper, Bill to, solicitor)
6. Go to contact person list

**Actual Result**
No View Information Icon is Displayed in the Action Panel for Contact Person Lists.

![27](https://cloud.githubusercontent.com/assets/9795882/6999489/807e26e2-dc3f-11e4-8718-d45210d1f2d8.png)

**Expected Result**
Display the position of the contact person. There is no view action on the record so the position will not be viewed by the user.

**Comment by knarceo** [comment]
Fixed on next push in cloud and localhost

**Comment by Leirum** [comment]
Issue fix was already verified.
