### ISSUE TITLE
The add truck module accepts 9999 for the year and accepts 0 values for the total weight of the truck.

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#535]
**Steps to Replicate**
1. Log in as admin
2. Go to vendors
3. Add vendor
4. Add truck
5. Fill up the form and on the year and weight part, input the values found in the picture
6. Save the record
7. Record is saved

**Actual Result**
The system accepted the 9999 and 0 values for the KG of the trucks

![28](https://cloud.githubusercontent.com/assets/9795882/6999529/20ddac70-dc40-11e4-81ae-96780269491c.png)

**Expected Result**
The year should be validated to the current year only. And the total weight of the truck should not be zero.

**Comment by JMXPSX** [comment]
FIXED on Jan's Push

**Comment by Leirum** [comment]
Issue fix was already verified.
