### ISSUE TITLE
The validation on empty notification type only displays an alert box. It does not prevent the page from saving the booking.

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#536]
**Steps to Replicate**
1. Log in as admin
2. Go to booking
3. Add new booking
4. Fill up the form with correct details except leave the notification type blank
5. Hit save.
6. An alert box will prompt you, click OK
7. There will be a dialog box. CLick next
8. The booking is saved even if the notification type which is required is empty

**Actual Result**
The booking should not proceed if the notification type is empty

![32](https://cloud.githubusercontent.com/assets/9795882/6999605/c9c63afe-dc41-11e4-88a0-6957ce1527f2.png)

**Expected Result**
The validation on empty notification type only displays an alert box. It does not prevent the page from saving the booking.

**Comment by JMXPSX** [comment]
This is already fixed on later builds

**Comment by Leirum** [comment]
Issue fix was already verified.
