### ISSUE TITLE
The comment does not filter the script tag entered. As a result, when viewing the whole records, the browser rendered the script tag and displayed it as an alert box.

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#537]
**Steps to Replicate**
1. Log in as admin
2. Go to booking
3. Add a new booking and save it
4. On the Container listing, Add a continer list record
5. Edit it and set the comment value as ""<script>alert();</script>
6. Save it 
7. Reload the page
8. There will be an alert box

**Actual Result**
There were no validation for script tags. 

![33](https://cloud.githubusercontent.com/assets/9795882/6999595/7ccc805a-dc41-11e4-8baa-36c5eeb91e9f.png)

**Expected Result**
There should be a validation for special characters on the comments details

**Comment by knarceo** [comment]
Somehow, this issue was fixed.

**Comment by Leirum** [comment]
Issue fix was already verified.
