### ISSUE TITLE
The Length, height, width and weight of the item accepts 0 value and the SRP accepts 0.01 value.

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#538]
**Steps to Replicate**
1. Log in as admin
2. Go to customers
3. Add a customer
4. On the items list, add a new one
5. Fill up the form with 0 values for the L x H x W as well as the weight. On the SRP field, fill out 0.01 for the SRP value

**Actual Result**
The Length, height, width and weight of the item accepts 0 value and the SRP accepts 0.01 value.

![30](https://cloud.githubusercontent.com/assets/9795882/6999658/6a25e0f2-dc43-11e4-82da-a3122bd27159.png)

**Expected Result**
There should be a validation for the proper input value for the LxWxH and weight

**Comment by ZaX09** [comment]
issue is fixed in latest build

**Comment by Leirum** [comment]
Issue fix was already verified.
