### ISSUE TITLE
The system accepts duplicate record for MAIN Address on customer contact. The resultant menu box on the booking displays triplicate data of the same record

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#539]
**Steps to Replicate**
1. Log in admin
2. Go to booking
3. Fill up the form
4. On the customer contact person, add address as MAIN type
5. Fill up the address details according to the data on the picture
6. Do it 3x and save the record
7. The system will save the address
8. Triplicate record will be displayed on the menu box

**Actual Result**
The system accepts duplicate record for MAIN Address on customer contact. The resultant menu box on the booking displays triplicate data of the same record

![31](https://cloud.githubusercontent.com/assets/9795882/6999676/af44d314-dc43-11e4-83ac-b72aba8edc3a.png)

**Expected Result**
There should be a validation for duplicate / triplicate address with the same type of address.

**Comment by knarceo** [comment]
The same type of address validation in this issue was somehow fixed in the new builds.

**Comment by Leirum** [comment]
Issue fix was already verified.
