### ISSUE TITLE
Edit Booking: Approved Status for Booking With No Containers.

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#540]
**Steps to Replicate**
1. Log in as admin
2. Go to booking
3. Add a record
4. Add container details
5. Approve the booking
6. Edit the booking
7. Go to container listing
8. Remove all the containers
9. Save the booking
10. Check the status of the booking, the status should be changed back to incomplete since there are no containers allotted for that booking

**Actual Result**
The status of the booking is still approved even if there are no containers for that booking. This should be incomplete

![35](https://cloud.githubusercontent.com/assets/9795882/6999693/14307526-dc44-11e4-84d3-9eda6f6da1f2.png)

**Expected Result**
The status should be changed back to incomplete since there are no containers alloted for that booking

**Comment by knarceo** [comment]
Fix on next push in local and live.

**Comment by Leirum** [comment]
Issue fix was already verified.
