### ISSUE TITLE
Dispatch Plan: Inactive drivers are Included in Selection of Drivers

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#542]
**Steps to Replicate**
1. Log in as admin
2. Go to booking
3. Add a trucking booking, save it, approve it
4. Go to dispatch plan
5. Look for the created record
6. Go to drivers list
7. Add an inactive driver thru the button
8. Save it
9. The inactive driver will be on the drop down box.

**Actual Result**
Even inactive drivers are displayed on the list of drivers.

![39](https://cloud.githubusercontent.com/assets/9795882/6999745/6826c7d8-dc45-11e4-8381-ade14e869bbf.png)

**Expected Result**
Inactive drivers should not be included in the selection of drivers

**Comment by knarceo** [comment]
Problem solved :thumbsup:

**Comment by Leirum** [comment]
Adding inactive drives results in a page error.
![4](https://cloud.githubusercontent.com/assets/9795882/7487263/b14e2696-f3e6-11e4-87bd-d4f64d4ec4db.png)

**Comment by knarceo** [comment]
Cannot replicate in local/live when adding inactive drivers either via in Vendor's module or in the Add Driver modal in Dispatch Planning.

**Comment by Leirum** [comment]
Issue can no longer be replicated
