### ISSUE TITLE
Vendor: Drivers List: No Information Icon is Displayed..

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#543]
**Steps to Replicate**
1. Log in as admin
2. Go to vendor
3. Add an inactive vendor
4. Save it
5. View drivers record
6. There are no information icon, so the status is not displayed
7. The status should be displayed to know the current status of the driver

**Actual Result**
User cannot view the information of every drivers in the list.

![38](https://cloud.githubusercontent.com/assets/9795882/6999781/627f6c62-dc46-11e4-8261-f63edfb40734.png)

**Expected Result**
There should be an information icon for viewing all the data given for the selected driver.

**Comment by JMXPSX** [comment]
all table information are already shown.

Kindly check next build

**Comment by Leirum** [comment]
Issue fix was already verified.
