### ISSUE TITLE
Proceeds to Homepage When User Navigates Back to Previous Page After Logging Out.

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#544]
**Steps to Replicate**
1. Log in
2. On the home screen, click the back button
3. User will be redirected to the log in page
4. Click log in again
5. On home page, click log out
6. Click back again
7. User will be inside the homepage again

**Actual Result**
- Session are not handled properly.
- Navigates back to home page even the user has been logged out.
- Calendar is not displayed.
- Log in module was placed inside the frame of booking booking calendar

![40](https://cloud.githubusercontent.com/assets/9795882/6999806/57ed3b2a-dc47-11e4-9eec-a8a7de1176af.png)

**Expected Result**
- There should be a proper session handler for log in module.
- Since the user has already logged out, navigating back to homepage should be forbidden.
- Page should remain on the Log In page.

**Comment by knarceo** [comment]
Fixed on next push.

**Comment by Leirum** [comment]
Issue can no longer be replicated.
