### ISSUE TITLE
New Added Booking Does Not Reflect on the New Booking Count in Dashboard

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#545]
**Steps to Replicate**
1. Log in
2. Go to booking
3. Add new bookings
4. Save it
5. Go to dashboard
6. New booking count does not reflect on the bookings count

**Actual Result**
0 is displayed on the new bookings count even if there are new bookings added.

![43](https://cloud.githubusercontent.com/assets/9795882/7000000/6fe5fbdc-dc4b-11e4-8561-443fba70ca42.png)

**Expected Result**
Booking count should be reflected

**Comment by JMXPSX** [comment]
This is now working on the latest build.

Kindly check it

**Comment by Leirum** [comment]
Issue fix was already verified.
