### ISSUE TITLE
Booking List: No Tool Tip for Cancel and Approve Icons.

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#546]
**Steps to Replicate**
1. Log in as admin
2. Go to booking
3. Add a record
4. Go to booking 
5. Hover the icons on the action column
6. Notice that on the cancel or approve icon, there is no tooltip
7. There should be a tool tip for those icons too

**Actual Result**
Icon for cancel and approve has no tool tip

![44](https://cloud.githubusercontent.com/assets/9795882/7000027/d78e6bca-dc4b-11e4-9108-69a9af0fe119.png)

**Expected Result**
There should be a tool tip for those icons too

**Comment by JMXPSX** [comment]
Wait for May's push

**Comment by Leirum** [comment]
Issue fix was already verified.
