### ISSUE TITLE
Edit Freight Plan: Accepts Schedule with Invalid Time Frame for Arrival and Departure.

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#547]
**Steps to Replicate**
1. Log in as admin
2. Go to Operations > Freight Plan
3. Go to  Freight Plan : Orders   Freight Plan : Items   Freight Plan
4. On any item, click on set vessel
5. Go to add schedule
6. Add a schedule with same date but in time of departure add the following
   Time departure: 5:00PM
   Time arrival : 8:00 AM
7. Save it
8. Record is saved

**Actual Result**
Accepted a schedule which the time of arrival is earlier than time of departure

![45](https://cloud.githubusercontent.com/assets/9795882/7000077/990946d0-dc4c-11e4-8f18-7533e6b8c5a1.png)

**Expected Result**
There should be a validation for time arrival and time departure.

**Comment by JMXPSX** [comment]
The restriction was requested by the client to be removed.

The reason was that the schedules indicated in Freight Planning are all estimates and can change at any time so what we did was to have a popup window that will ask the user to proceed even with the dates are not valid

**Comment by barbacenasmc** [comment]
This is noted. Thanks.
