### ISSUE TITLE
Null is displayed as the destination on the calendar schedule destination instead of NONE

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#548]
**Steps to Replicate**
1. Log in as admin
2. Check on the calendar
3. If there are no booking record, add one - trucking booking
4. Add a dispatch plan for the trucking
5. Go to the calendar
6. The destination will display a NULL value

**Actual Result**
NULL is displayed

![46](https://cloud.githubusercontent.com/assets/9795882/7000122/9cfa34ce-dc4d-11e4-834c-e64b09a48f08.png)

**Expected Result**
NULL should be omitted, add the type of booking for that day I.E., Trucking or shipping only.

**Comment by jjsarmiento** [comment]
i think this is a problem with the interpretation of data from your database. back-end.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
