### ISSUE TITLE
Booking Information: Improper format for the currency value

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#549]
**Steps to Replicate**
1. Log in as admin
2. Go to booking
3. Add one booking
4. On the booking information, add container
5. Save it
6. Check the format on the declared value

**Actual Result**
Format was 250000

![47](https://cloud.githubusercontent.com/assets/9795882/7000135/e8080be4-dc4d-11e4-954e-2fa5ad76b24e.png)

**Expected Result**
Format should follow : 250,000.00

**Comment by JMXPSX** [comment]
This has now been corrected. See latest build.

-- Peter Parker

**Comment by Leirum** [comment]
Issue fix was already verified.
