### ISSUE TITLE
Arrived bookings can be cancelled

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#554]
**Steps to Replicate**
1. Log in as admin
2. Go to booking
3. Add a booking record, approve it
4. Go to dispatch planning
5. Add a vendor
6. Go to shipping monitoring
7. Set the status of the booking to ARRIVED
8. Go back to booking
9.  Look for the booking record
10. Cancel it
11. The record is cancelled even if it ARRIVED in the destination

**Actual Result**
Arrived bookings can be cancelled

![53](https://cloud.githubusercontent.com/assets/9795882/7000322/676fa15a-dc51-11e4-80e5-1917fa178f7b.png)

**Expected Result**
The record should not be cancelled because it has already arrived.

**Comment by knarceo** [comment]
Fixed on next push.

**Comment by barbacenasmc** [comment]
Issue fix was already reviewed however, there was no message to tell the user why the booking can't be cancelled.

**Comment by barbacenasmc** [comment]
Hi, any update about this? Thanks.

**Comment by knarceo** [comment]
Fixed on next push

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
