### ISSUE TITLE
User can access the Yard Management >Container Management even if he/she has no privilege in doing the transactions inside that module like adding of containers, editing and deleting of containers

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#555]
**Steps to Replicate**
1. Log in as regular customer
2. Use direct URL access using 
http://192.168.5.165:8080/freightbit/operations/viewContainerList.action
3. Play around the module, do add, edit and delete of records
4. Records are updated.

NOTE: ALSO APPLICABLE TO
1. View consolication container list module  
http://192.168.5.165:8080/freightbit/operations/viewConsolidationContainerList.action

2. View Sea Freight List Module
http://192.168.5.165:8080/freightbit/operations/viewSeaFreightList.action

3. View Inland Freight List
http://192.168.5.165:8080/freightbit/operations/viewInlandFreightList.action

4. View Vessel Schedules
http://192.168.5.165:8080/freightbit/operations/viewVesselSchedules.action

**Actual Result**
User can access the Yard Management >Container Management even if he/she has no privilege in doing the transactions inside that module like adding of containers, editing and deleting of containers.

**Expected Result**
There should be a proper validation for the access rights for each of the users type

**Comment by knarceo** [comment]
Fixed on next push.

**Comment by Leirum** [comment]
Issue fix was already verified.
