### ISSUE TITLE
Regular Customer: Add Outbound Documents: Server Error Occured

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#556]
**Steps to Replicate**
1. Log in as regular customer
2. Go to documentation > pending documents
3. Click "ADD OUTBOUND DOCUMENTS"

**Actual Result**
Server error occurred

![screen shot 2015-04-08 at 11 02 58 am](https://cloud.githubusercontent.com/assets/9795882/7038118/093be956-dddf-11e4-9337-3f05c032ae74.png)

**Expected Result**
There should be no server error occurring after clicking the button

**Comment by JMXPSX** [comment]
Already retooled on latest build

**Comment by Leirum** [comment]
Issue can no longer be replicated.
