### ISSUE TITLE
There is no page to be displayed on reports page > container

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#557]
**Steps to Replicate**
1. Log in as admin
2. Go to reports > container
3. No page is displayed

NOTE: ALSO REPLICABLE TO THE FF MODULES
1. CARGO
2. CUSTOMER RELATION
3. SALES

**Actual Result**
There is no page to be displayed on reports page > container

![screen shot 2015-04-06 at 1 23 47 pm](https://cloud.githubusercontent.com/assets/9795882/7000879/42766cc6-dc60-11e4-8464-341d0cd853a1.png)

**Expected Result**
There should be a corresponding page to be displayed

**Comment by JMXPSX** [comment]
This is just for demo.

Function wise this may change whilst in development
