### ISSUE TITLE
Report: The chart does not change based on the value selected on the Statistics by:

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#558]
**Steps to Replicate**
1. Log in as admin
2. Go to reports > trucks
3. There will be a drop down box
4. Change the value
5. Notice that the chart does not change accordingly

**Actual Result**
The chart does not change based on the value selected on the Statistics by

![58 week](https://cloud.githubusercontent.com/assets/9795882/7000942/884a5054-dc61-11e4-9582-360d91f3c580.png)
![58 month](https://cloud.githubusercontent.com/assets/9795882/7000943/89f24416-dc61-11e4-9c0c-59094f1f350c.png)
![58 year](https://cloud.githubusercontent.com/assets/9795882/7000944/8ac4fa5a-dc61-11e4-9fda-5eef911028b9.png)

**Expected Result**
The chart should change accordingly to the value selected on the drop down box

**Comment by JMXPSX** [comment]
this is still in beta. no need to QA

**Comment by JMXPSX** [comment]
yet
