### ISSUE TITLE
Regular Customer: HTTP Error 404 upon notification click

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#560]
**Steps to Replicate**
1. Log in as regular customer
2. Go to the header and look for notification
3. Click on the notification
4. There will be 42 notifications
5. Click on the 42 notifications
6. HTTP Error 404 page not found is displayed

ALSO REPLICABLE TO HELP MODULE

**Actual Result**
HTTP Error 404 upon notification click

![61](https://cloud.githubusercontent.com/assets/9795882/7037987/9a09ba82-dddd-11e4-9e7c-11e5ece93337.png)

**Expected Result**
There should be corresponding page to display the notifications

**Comment by knarceo** [comment]
Issue was fixed somehow. Cannot be replicated anymore.

**Comment by Leirum** [comment]
Issue fix was already verified.
