### ISSUE TITLE
Edit Regular Customer: The customer dropdown can not fetch the saved user's customer data.

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#561]
**Steps to Replicate**
1. Log in as admin
2. Go to users
3. Edit a regular customer
4. Check the dropdown box
5. Dropdown does not displayed the correct data, the dropdown displays empty value

**Actual Result**
The customer dropdown can not fetch the saved user's customer data.

![63](https://cloud.githubusercontent.com/assets/9795882/7001080/1a646612-dc64-11e4-9dec-8b4943ebba76.png)

**Expected Result**
The user's customer data should be displayed accordingly.

**Comment by knarceo** [comment]
Issue was fixed somehow. Cannot be replicated anymore.  Admins are the only ones who can edit their Customer drop down value.

**Comment by Leirum** [comment]
Issue fix was already verified.
