### ISSUE TITLE
User List: Updating Regular Customers Information Navigates into an Error Page.

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#562]
**Steps to Replicate**
1. Log in as admin
2. Go to users
3. Edit a regular customer
4. Update some fields
5. Click Update

**Actual Result**
Error 500 Server error occurs after editing a regular customer for a customer
But when the user navigates back to user list, information has been updated successfully.

![64](https://cloud.githubusercontent.com/assets/9795882/7000802/fd93d766-dc5e-11e4-8a69-58316966cd51.png)

**Expected Result**
It should display a validation message indicating that update has been successful.

**Comment by knarceo** [comment]
This issue was fixed along with this issue number #372

**Comment by Leirum** [comment]
Issue fix was already verified.
