### ISSUE TITLE
Records of same item type is displayed in different record row.

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#563]
**Steps to Replicate**
1. Log in as admin
2. Go to booking
3. Add new Trucking - Interwarehouse booking
4. Fill up the form based on the booking data, then save it
5. On the items list, select any from the dropdown box, if there are none, add one in the customer's information module
6. Add 1 item, save
7. Repeat the same item for 3x
8. Check the table. This will display 3 different records of the same item.

**Actual Result**
Records of same item type is displayed in different record row.

![36](https://cloud.githubusercontent.com/assets/9795882/7001019/080a383a-dc63-11e4-85ab-51a9e8dd5784.png)

**Expected Result**
If there are records of the same, the quantity should be incremented.

**Comment by Leirum** [comment]
Issue can still be replicated
![screen shot 2015-05-06 at 10 07 04 am](https://cloud.githubusercontent.com/assets/9795882/7486414/b57cef04-f3d7-11e4-818f-9043da3c9dc5.png)

**Comment by barbacenasmc** [comment]
Issue fix was already reviewed but found out that it only applies to items and not on containers. Can we also apply the same behavior on bookings that deal with containers?

**Comment by JMXPSX** [comment]
Containers need to be broken down into 1 quantity per row. The reason for this is to have each order item be indentified to one conatainer number

**Comment by ZaX09** [comment]
verified as fixed. Replicating the steps yields a single row of item list with the quantity set to 3 and updates if the same item is added.
