### ISSUE TITLE
Regular customer can view/update bookings done by other companies 

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#564]
**Steps to replicate**
1. Log in as admin
2. Go to users
3. Create a user under a certain customer
4. Log Out
5. Log in as regular customer (recently created regular customer)
6. Go to bookings
7. Other company's bookings can be edited and viewed by the regular customer

**Actual Result**
Regular customer can view/update bookings done by other companies.

![65](https://cloud.githubusercontent.com/assets/9795882/7037726/9a3dac06-ddd9-11e4-8fed-fc7994753dbd.png)

**Expected Result**
The booking table should display ONLY the bookings made by the company the regular customer is working for

**Comment by knarceo** [comment]
This issue was fixed in this commit number ae44af469fac62294428f20b067a6229a5c5eae4 by Ms. May

**Comment by Leirum** [comment]
Issue fix was already verified.
