### ISSUE TITLE
Regular customer can add bookings for other companies

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#565]
**Steps to Replicate**
1. Log in as admin
2. Go to users
3. Create a user under a certain customer
4. Log Out
5. Log in as regular customer (recently created regular customer)
6. Go to bookings
7. Add a booking record
8. On the customers dropdown box, you will notice that other customers(companies) are also displayed.
9. The available customer in that dropdown box should be the company of the regular customer only

**Actual Result**
Regular customer can add bookings for other companies

![screen shot 2015-04-08 at 10 25 03 am](https://cloud.githubusercontent.com/assets/9795882/7037735/d9c7430a-ddd9-11e4-8ed1-0fd55dd939ed.png)

**Expected Result**
The available customer in that dropdown box should be the company of the regular customer only.

**Comment by JMXPSX** [comment]
DONE on push 426d716128cee5770086fb61d3dba211fbe5d234

**Comment by Leirum** [comment]
Issue fix was already verified.
