### ISSUE TITLE
Regular Customer can Access Yard Management Module thru direct link.

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#566]
**Steps to Replicate**
1. Log in as regular customer
2. Use direct URL access using 
localhost/freightbit/operations/viewContainerList.action
3. Play around the module, do add, edit and delete of records
4. Records are updated.

NOTE: ALSO APPLICABLE TO
1. View consolication container list module  
localhost/freightbit/operations/viewConsolidationContainerList.action

2. View Sea Freight List Module
localhost/freightbit/operations/viewSeaFreightList.action

3. View Inland Freight List
localhost/freightbit/operations/viewInlandFreightList.action

4. View Vessel Schedules
localhost/freightbit/operations/viewVesselSchedules.action

**Actual Result**
User can access the Yard Management >Container Management even if he/she has no privilege in doing the transactions inside that module like adding of containers, editing and deleting of containers

![55](https://cloud.githubusercontent.com/assets/9795882/7038035/31cc8c1e-ddde-11e4-9dc7-a846504f6701.png)

**Expected Result**
There should be a proper validation for the access rights for each of the users type

**Comment by knarceo** [comment]
This issue was fixed in this commit number 9a0eacf588604efb6067bb3231279361a305b3d3

**Comment by Leirum** [comment]
Issue can no longer be replicated.
