### ISSUE TITLE
Error Page 500 is displayed

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#567]
**Steps to replicate**
Condition:
1. Log in
2. On the home screen, click the back button
3. You wil be redirected to the log in page
4. Click log in again
5. On home page, on the calendar do a valid log In
6. You will be redirected to homepage
7. Go to booking
8. Add a booking record.
9. On the Contact consignee contact person, add a record
10. Click save
11. Error 500 is displayed

This is also can be replicated in any module which has the DDM operation

**Actual Result**
Error Page 500 is displayed

**Expected Result**
Saving should be OK

**Comment by knarceo** [comment]
This issue was fixed along with issue #544

**Comment by Leirum** [comment]
Issue can no longer be replicated.
