### ISSUE TITLE
License missing from repo

### ISSUE THREAD

**Issue by karan** [johnpelquingua/freightbit-logistics#568]
Without a license, this project isn't open source and no one can use the code.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

> A novel effort by [**Add a License Please**](https://github.com/karan/add-a-license-please)

**Comment by JMXPSX** [comment]
who are you?

**Comment by karan** [comment]
I'm @karan ?

**Comment by JMXPSX** [comment]
Hi nice to meet you

**Comment by karan** [comment]
Nice to meet you too.. 

What do you do?

**Comment by JMXPSX** [comment]
We're developing a system for a company and we're using Struts 2, Hibernate J2EE.

**Comment by karan** [comment]
Nice. What will the system do?
