### ISSUE TITLE
Customer Relations Report: Error page was displayed when no date was selected

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#569]
Steps to replicate:

1. On the Reports submenu, select Customer Relations.
2. On the Statistics tab, select "Total Number of Bookings".
3. Do not select dates from and to.
4. Click "View Statistics" button.

Actual Result: Another window will display like on the screenshot below.
Expected Result: User should not be allowed to view a report if date to and date from field have no value.

![1](https://cloud.githubusercontent.com/assets/7791554/7580824/47563e5a-f8ae-11e4-82a4-533625c6b60f.png)

**Comment by barbacenasmc** [comment]
**Note:** Same thing also happens when user did not select date from or date to. If this is the case, can we have a validation message instead to tell the user that he needs to select dates before viewing the report?

**Comment by Leirum** [comment]
Issue can no longer be replicated.
