### ISSUE TITLE
View Report: Past dates were disabled on the datepicker of "Date From" field

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#570]
Steps to replicate:
1. Click "Customer Relations" under Reports menu.
2. Select "Total No. of Bookings".
3. Click the "Date From" field to display the datepicker.

Actual result: Past dates were disabled on the datepicker
Expected result: Past dates should be enabled.

![report-date-from](https://cloud.githubusercontent.com/assets/7791554/7602814/0a460d98-f95c-11e4-9333-e80cbf2137ed.png)

**Comment by Leirum** [comment]
Issue can no longer be replicated.
