### ISSUE TITLE
Customer Relations Report: Services field display all instead of the services associated with the enlisted customer

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#571]
Test Data:
For 1 week:
Customer1 - 2 bookings (FCL and LCL)
Customer2 - 1 bookings (LCL)

Steps to replicate:
1. On the Reports submenu, select Customer Relations.
2. On the Statistics tab, select "Total Number of Bookings".
3. Select dates for report period.
4. Click "View Statistics" button.

Actual result: Another window displayed showing the list of customers with their corresponding no. of bookings each. But the services field displayed all types of services 
Expected result: Services field should display FCL and LCL only.

![image](https://cloud.githubusercontent.com/assets/7791554/7603297/4e478524-f963-11e4-9102-35df6e57b2f3.png)

![image](https://cloud.githubusercontent.com/assets/7791554/7603323/cd4cf1ba-f963-11e4-9322-05f57135a6c6.png)

**Comment by JMXPSX** [comment]
This had been fixed already

**Comment by barbacenasmc** [comment]
Issue no longer exists due to change of report template design.
