### ISSUE TITLE
Missing Values in the Generated Statistics Report When The User Views The Total Number of Bookings from the Past Week up to the Date Today.

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#573]
**Steps to replicate**
1. Navigate to Report > Statistics Tab.
2. On the date field, select the "Date From" as the week ago (e.g. May 11, 2015)
3. Select the "Date To" as the date today. (e.g. May 18, 2015)
4. Select the data as the "Total Number of Bookings"

**Actual Result**
- Values of Date from and Date To was not displayed.
- Report Date has not been generated.
- Average Number of Bookings displays no value.

![1](https://cloud.githubusercontent.com/assets/9795882/7694704/86b60432-fe16-11e4-8c21-e4792c4a17a2.png)

**Expected Result**
- Another window should display knowing the list of customers with their corresponding no. of bookings each.
- Should display the selected Date From and Date To value.
- Should display the summary containing the values of total number of bookings and average number of bookings.
- Should display the date and time when the report was generated.

**Comment by emarino0411** [comment]
Fixed and is for verification
