### ISSUE TITLE
Archived Bookings Proceeds to the Second Page of the Active Bookings once the Next button has been clicked by the User

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#580]
**Steps to replicate**
1. Navigate to Archived Bookings
2. Click its page 2 or the link Next/ Last.

**Actual Result**
- User cannot access the rest of the page of the archived bookings.
- Once the user clicks the next page, it navigates to the 2nd page of the Active Bookings Module.

![9 3](https://cloud.githubusercontent.com/assets/9795882/7696474/53f4ed46-fe30-11e4-99bd-382e71f3d19a.png)

![10](https://cloud.githubusercontent.com/assets/9795882/7696488/867a94dc-fe30-11e4-8a6e-ed64477364bf.png)

**Expected Result**
- The page should proceed to the next page of the archived bookings.

**Comment by ZaX09** [comment]
fixed on next push

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
