### ISSUE TITLE
Statistics Report: CRS Total Number of Bookings per Consignee per Destination: Consignees under Same Cust Code were Repeatedly Listed and Randomly Arranged.

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#585]
**Steps to replicate**
1. Navigate to Active Bookings.
2. Search for a specific consignee and check for its booking destination.
3. Navigate to Reports Module.
4. Select Customer Relations as Department.
5. Select Statistics
6. Select Total Number of Bookings per Consignee per Destination.
7. Select January 1, 2015 as "From" date.
8. Select the date today as "To" date.

**Actual Result**
- Lists were randomly arranged.
- Consignees under same Cust Code were repeatedly listed.

***Note:*** *Can also be replicated in Statistics Report: CRS Total Number of Bookings per Shipper per Destination*

![1 3](https://cloud.githubusercontent.com/assets/9795882/7717638/30f28608-fed7-11e4-9db3-0fb26e459f7b.png)
![1 1](https://cloud.githubusercontent.com/assets/9795882/7717636/2cbb565a-fed7-11e4-975b-ef69cda616d3.png)

**Expected Result**
- Group the same Cust Code then arrange the Consignees name alphabetically.
- Consignees under same Cust Code should have a distinct record.

**Comment by emarino0411** [comment]
Fixed and is for verification

**Comment by barbacenasmc** [comment]
Issue can still be replicated:
![image](https://cloud.githubusercontent.com/assets/7791554/7879036/f4c1f156-061e-11e5-9555-7c6337c8bb37.png)

![image](https://cloud.githubusercontent.com/assets/7791554/7879025/d8b84c1c-061e-11e5-95bd-5fb8b4007808.png)

**Comment by knarceo** [comment]
Fixed on next push.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
