### ISSUE TITLE
Statistics Report: CRS Total Number of Bookings per Consignee per Destination: Total Number of Bookings Summary has an Invalid Value

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#586]
**Steps to replicate**
1. Navigate to Reports Module.
2. Select Customer Relations as Department.
3. Select Statistics.
4. Select Total Number of Bookings per Consignee per Destination as Data Result.
5. Select January 1, 2015 as "From" date.
6. Select the date today as "To" date.

**Actual Result**
Total Number of Bookings Summary has a nonequivalent value with the total number of bookings per consignee per destination.

![2](https://cloud.githubusercontent.com/assets/9795882/7717803/0ac40f4e-feda-11e4-8d90-d8a3d6a9cee5.png)

**Expected Result**
Total Number of Bookings Summary should be equal to the sum of Total Number of Bookings per Consignee per Destination.

**Comment by JMXPSX** [comment]
This is working as intended. Do not confuse the total value of [Total Number of Bookings per "CONSIGNEE" per Destination] versus [Total Number of Bookings].

The only one that could have the same value is [Total Number of Bookings per "SHIPPER" per Destination] versus [Total Number of Bookings].

**Comment by Leirum** [comment]
Issue can still be replicated. 
![7](https://cloud.githubusercontent.com/assets/9795882/7806140/8d1757e2-03af-11e5-8180-09c540fa6aa1.png)

**Comment by emarino0411** [comment]
Fixed and is for verification

**Comment by ZaX09** [comment]
verified
