### ISSUE TITLE
Statistics Report: CRS Total Number of Bookings per Consignee per Destination: All registered consignees were retrieved in report and some of the values have an improper label and arrangement.

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#587]
**Steps to replicate**
1. Navigate to Reports Module.
2. Select Customer Relations as Department.
3. Select Statistics.
4. Select Total Number of Bookings per Consignee per Destination as Data Result.
5. Select January 1, 2015 as "From" date.
6. Select the date today as "To" date.

**Actual Result**
- Attribute for consignee is labeled as customer
- All registered consignees (even without assigned bookings) were retrieved in statistics report.
- Destination were not properly arranged. Palawan and Ozamis have an exchanged position.

***Note:*** *Can also be replicated in Statistics Report: CRS Total Number of Bookings per Shipper per Destination*

![3 1](https://cloud.githubusercontent.com/assets/9795882/7718230/d2fac944-fedf-11e4-86c4-ea0e3d2ff7b2.png)

![3](https://cloud.githubusercontent.com/assets/9795882/7718231/d4546188-fedf-11e4-8b86-3cef424e6d70.png)

**Expected Result**
- Customer should be labeled as Consignee.
- Only the consignees with assigned bookings should be listed in statistics report.
- Destination label should be alphabetically arranged.

**Comment by emarino0411** [comment]
Fixed

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
