### ISSUE TITLE
Statistics Report: FCL OPERATIONS: Total FCL Bookings: Some of the important data were missing.

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#588]
**Steps to replicate**
1. Navigate to Reports Module.
2. Select FCL OPERATIONS as Department.
3. Select Statistics.
4. Select Total FCL Bookings as Data Result.
5. Select the preferred dates.

**Actual Result**
- Date from and Date To were not displayed.
- Report Date has not been generated.
- Summary for the Total Number of Bookings and Average Number of Bookings has no values.

![6](https://cloud.githubusercontent.com/assets/9795882/7722948/45214f48-ff17-11e4-9a4e-2a5b1040ef3b.png)

**Expected Result**
- Another window should display knowing the list of customers with their corresponding no. of bookings each.
- Should display the selected Date From and Date To value.
- Should display the summary containing the values of total number of bookings and average number of bookings.
- Should display the date and time when the report was generated.

**Comment by emarino0411** [comment]
Fixed

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
