### ISSUE TITLE
Last Chosen Dates are Still Disabled even all the Date Inputs have been Cleared by the User

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#589]
**Steps to replicate**
1. Navigate to Report Module
2. Fill out all the required fields.
3. Select the preferred dates.
4. Delete the values in the date fields.
5. Try to select a date again.

**Actual Result**
The last selected dates are still disabled even the user deletes the value on date fields.

![6 2](https://cloud.githubusercontent.com/assets/9795882/7746136/b563a6f4-ffe2-11e4-8f38-c771a72a9032.png)
![6 1](https://cloud.githubusercontent.com/assets/9795882/7746137/b566b588-ffe2-11e4-85e7-12f85caf47e1.png)

**Expected Result**
Once the user removes the input on date fields, all dates should be enabled again.

**Comment by emarino0411** [comment]
Fixed

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
