### ISSUE TITLE
Mislabeled Columns for Statistics Report: FCL OPERATIONS: Total Cancelled FCL Bookings: 

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#590]
**Steps to replicate**
1. Navigate to Reports Module.
2. Select FCL OPERATIONS as Department.
3. Select Statistics.
4. Select Total Cancelled FCL Bookings as Data Result.
5. Select the preferred dates.

**Actual Result**
- Has no label for No. column
- Code is labeled as Company Code instead of Customer Code.
- Columns for all the service requirements (FCL, LCL, RCU, LC, TKG) has been shown.

***Note:*** *Can be replicated on LCL Operations: Total Cancelled LCL Bookings*

![7](https://cloud.githubusercontent.com/assets/9795882/7746575/0364f8e6-ffe6-11e4-8a70-a7594f7f6ae1.png)

**Expected Result**
- There should be a label for "No." column.
- Company Code should be labeled as "Customer Code."
- Columns for all the service requirements (FCL, LCL, RCU, LC, TKG) should not be included.

**Comment by barbacenasmc** [comment]
Issue no longer exists
