### ISSUE TITLE
 Lists were randomly arranged on Statistics Report: FCL OPERATIONS: Total FCL Bookings

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#591]
**Steps to replicate**
1. Navigate to Reports Module.
2. Select FCL OPERATIONS as Department.
3. Select Statistics.
4. Select Total FCL Bookings as Data Result.
5. Select January 1, 2015 as "From" date.
6. Select the date today as "To" date.

Actual Result
- The lists were randomly arranged.
- Arrangement of data is based upon the number of bookings that the customers have. 

***Note:*** *Can also be replicated in other data result of the same department*

![8](https://cloud.githubusercontent.com/assets/9795882/7746895/a567584e-ffe8-11e4-9434-4ceb88085935.png)

**Expected Result**
- Lists (Customers) should be alphabetically arranged.

**Comment by barbacenasmc** [comment]
Issue can no longer be replicated.
