### ISSUE TITLE
Shipment Monitoring: Page proceeds to the Log In Module When Navigating on the Next Page of the On-Going Booking List.

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#592]
**Steps to replicate**
1. Log in as admin.
2. Navigate to Operations > Shipment Monitoring.
3. Click on the Next page.

**Actual Result**
The page proceeds to the log in module once the user clicks on the next page.

![3 1](https://cloud.githubusercontent.com/assets/9795882/7763410/cf5348cc-0072-11e5-993b-84250d7b1114.png)

![3 2](https://cloud.githubusercontent.com/assets/9795882/7763466/8e6e099a-0073-11e5-89c3-f2da0cfc117a.png)

**Expected Result**
It should proceed to the next page of the on going booking list.

**Comment by knarceo** [comment]
Fixed on Next Push

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
