### ISSUE TITLE
Bookings under FTL Service Requirement were also Counted for Statistics Report: FCL OPERATIONS: Total Container Vans 

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#593]
**Steps to replicate**
1. Navigate to Reports Module
2. Select FCL OPERATIONS as Department.
3. Select Statistics.
4. Select Total Container Vans as Data Result.
5. Select the preferred dates.
6. View Reports.
7. Navigate to Bookings Module.
8. Observe the bookings list with FCL and FTL service requirement for a certain customer.

**Actual Result**
FTL were also counted and listed in statistics report of FCL Operations: Total Container Vans

![4](https://cloud.githubusercontent.com/assets/9795882/7764914/4378d886-008a-11e5-83d0-f877a41729cd.png)

![4 1](https://cloud.githubusercontent.com/assets/9795882/7764934/8be300ba-008a-11e5-9b94-72c35936af01.png)

**Expected Result**
Only the bookings under FCL service requirement must be shown in the statistics report.

**Comment by emarino0411** [comment]
Fixed

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
