### ISSUE TITLE
Regular Customer can view other customer's on-going bookings on shipment monitoring page

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#594]
Steps to replicate:

1. Login as regular user.
Test data: 
*Customer: Mighty Corporation
*Username: cperez

2. Click Shipment Monitoring under Operations.

Actual result: He can view other customer's on-going bookings on the list.
Expected result: He should only be able to view his own on-going bookings on the list.
![customer-shipment-monitoring](https://cloud.githubusercontent.com/assets/7791554/7793324/f868c3f2-02ef-11e5-979e-e1809ca45fb9.png)

**Comment by knarceo** [comment]
Fixed on next push

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
