### ISSUE TITLE
There are Containers under FCL Bookings that were Retrieved in Statistics Report: LCL Operations: Total Items per LCL Bookings

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#595]
**Steps to replicate**
1. Navigate to Reports Module.
2. Select LCL OPERATIONS as Department
3. Select Statistics.
4. Select Total Items per LCL Bookings as Data Result.
5. Select January 1, 2015 as "From" date.
6. Select the date today as "To" date.
7. Navigate to Bookings List.
8. Look for FCL bookings and check if its containers retrieve in the statistics report of Total Items per LCL Bookings

**Actual Result**
- There are containers under FCL bookings that were retrieved in statistics report.
- It duplicate the order number, but has different item code.

![2 1](https://cloud.githubusercontent.com/assets/9795882/7805637/62b879d8-03a8-11e5-94eb-44280f14f126.png)
![2 2](https://cloud.githubusercontent.com/assets/9795882/7805638/62c01800-03a8-11e5-8fb5-ce77afa64a5c.png)

**Expected Result**
Only the items under LCL bookings should be listed in the report.

**Comment by emarino0411** [comment]
Fixed

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
