### ISSUE TITLE
Approve Booking: Name of customer on "Booked By" field was replaced by super admin name

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#597]
Steps to replicate:
1. As regular customer, add a new booking.
2. As super admin, approve the booking.

Actual result: Name of customer on "Booked By" field was replaced by super admin name
Expected result: Name of customer should still display on the "Booked By" field
![image](https://cloud.githubusercontent.com/assets/7791554/7805800/834e110a-03ab-11e5-9f6f-ac5e1aad3d3c.png)

**Comment by knarceo** [comment]
Fixed on next push

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
