### ISSUE TITLE
View Booking Summary: Name column displays item no. while on the booking form, item name was displayed

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#598]
Steps to replicate:
1. Add a new LCL booking.
2. Add items to the booking.
3. Click "Save Booking" button.

Actual result: Name column displays item no. while on the booking form, item name was displayed
Expected result: Name column should display item names.

![screenshot-2](https://cloud.githubusercontent.com/assets/7791554/7806169/2ee4bede-03b0-11e5-9f50-9f2795c0a1cc.png)
![screenshot-1](https://cloud.githubusercontent.com/assets/7791554/7806170/2ef92d6a-03b0-11e5-9c40-fd4b7cd5bc3f.png)

**Comment by knarceo** [comment]
Fixed on next push.

**Comment by ZaX09** [comment]
verified as fixed
