### ISSUE TITLE
Booking List: Approve, cancel and archive proceeds even if user is not yet confirming

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#600]
Steps to replicate:
1. Navigate to booking list.
2. Click approve, cancel or archive button.
3. When confirmation message displays, do nothing and wait for it to automatically close after some seconds.

Actual result: The status of the booking changes according to the action selected.
Expected result: Selected action should not proceed and should stay on that page until the user clicks anything.
![screenshot-4](https://cloud.githubusercontent.com/assets/7791554/7806452/a5aa1cb4-03b3-11e5-8038-5775ff8e05b9.png)

**Comment by knarceo** [comment]
Refer to #613 for this issue.

**Comment by emarino0411** [comment]
Fixed

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
