### ISSUE TITLE
Freight Planning: Error page was displayed when selected vessel schedule for an LCL booking

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#601]
Steps to replicate:
1. Login as Freight Operations Officer.
2. Go to LCL tab of Freight Planning page.
3. Tick the checkbox corresponding to the booking and click "Consolidate" button.
4. When the list of vessel schedules display, select one.

Actual result: Error page displays.
Expected result: Setting of vessel schedule should proceed.

![screenshot-6](https://cloud.githubusercontent.com/assets/7791554/7806828/0cb796a8-03b8-11e5-9942-da41ca837caf.png)
![screenshot-5](https://cloud.githubusercontent.com/assets/7791554/7806829/0cebb6ae-03b8-11e5-8efb-608775dc71c0.png)

**Comment by knarceo** [comment]
Fixed on next push.

**Comment by barbacenasmc** [comment]
Issue can still be replicated on a newly added booking. But on some existing booking, issue can't be replicated.
![screenshot-42](https://cloud.githubusercontent.com/assets/7791554/7928212/a4b87e98-091e-11e5-873d-c1ee01a6b10d.png)

**Comment by egmsantos** [comment]
Issue already fixed. User (FOO) successfully finished the consolidation.

**Comment by egmsantos** [comment]
For Closure
