### ISSUE TITLE
User can Select the Upcoming Dates in Generating Reports

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#602]
**Steps to replicate**
1. Navigate to Reports Module.
2. Select Customer Relations as Department.
3. Select Statistics.
4. Select Total Bookings as Data Result.
5. Select the upcoming dates on the date fields or select the same dates for "From" and "To" date fields.

**Actual Result**
- User can select the upcoming dates.
- Report has been generated.
- LibFormulaErrorValue{errorCode has been retrieved in the report.

![8 1](https://cloud.githubusercontent.com/assets/9795882/7808184/0ac9e952-03c4-11e5-9eaf-d331f9c77c82.png)
![8](https://cloud.githubusercontent.com/assets/9795882/7808182/09385696-03c4-11e5-9899-4d8b88bb9e42.png)

**Expected Result**
Since generating of reports is based upon the order dates, impending dates should be disabled in date fields.

**Comment by emarino0411** [comment]
Fixed and is for verification

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
