### ISSUE TITLE
Missing and Incorrect Data in Generating Statistics Report for Total Cancelled LC Bookings

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#603]
**Steps to replicate**
1. Navigate to Reports Module.
2. Select Loose Cargo Operations as Department.
3. Select Statistics.
4. Select Total Cancelled LC Booking as Data Result.
5. Select January 1, 2015 as "From" date
6. Select the date today as "To" date.

**Actual Result**
- Has no label for No. column
- Code is labeled as Company Code instead of Customer Code.
- Columns for all the service requirements (FCL, LCL, RCU, LC, TKG) has been shown.
- No column for service mode.

![10](https://cloud.githubusercontent.com/assets/9795882/7809699/bbb2b316-03ce-11e5-8e9c-63190d6ac611.png)

**Expected Result**
- Another window should display showing the list of customers with their corresponding no. of bookings each
- There should be a label for "No." column.
- Company Code should be labeled as ""Customer Code.""
- Columns for all the service requirements (FCL, LCL, RCU, LC, TKG) should not be included.
- It should display a column for service mode.

**Comment by emarino0411** [comment]
Fixed and for verification

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
