### ISSUE TITLE
The User has Set a Vessel Schedule for an Already Cancelled Booking

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#605]
**Steps to replicate**
1. Open 2 new tabs.
2. On the first tab, open the active bookings list.
3. On the second tab, open the freight plan list.
4. Select a booking on the freight plan list and click its set vessel schedule icon.
5. Click the first tab, look for the selected booking on the second tab then cancel the booking.
6. Click the second tab.
7. On freight plan: containers module, click the set schedule icon of the container with a planning 1 status.
8. Proceed in assigning container to the preferred vessel schedule and click save.
9. Click the first tab, refresh it, then observe the status of the recently cancelled booking.

**Actual Result**
Booking is now on on-going status.

**Expected Result**
When clicking set vessel schedule on the freight plan containers, module should be refreshed, since the status of the selected booking has been changed into cancelled booking.

**Comment by knarceo** [comment]
Fixed on next push.

**Comment by barbacenasmc** [comment]
Hi, I would like to know what should be the final expected behavior for this? I can still replicate the actual result stated above. Thanks.

**Comment by barbacenasmc** [comment]
This will be added to the list of known bugs for version 1 terminal report.
