### ISSUE TITLE
Proceeds to an Error page when Setting the Vendor of the Recently Deleted Item.

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#606]
**Steps to replicate**
1. Open 2 new tabs.
2. On the first tab, open the active bookings list.
3. On the second tab, open the dispatch plan list.
4. Click the set vendor icon of the selected booking on the dispatch plan list.
5. Click the first tab.
6. Edit the selected booking from the second tab and delete its item.
7. Click the second tab; click the set vendor icon of the recently deleted item.

**Actual Result**
It proceeds into an error page.

![1](https://cloud.githubusercontent.com/assets/9795882/7831395/0257e696-0489-11e5-94e3-45fa8e8bca70.png)

**Expected Result**
It should refresh the page and display "No cargo/container found!"

**Comment by emarino0411** [comment]
browser issue.

**Comment by barbacenasmc** [comment]
Hi team, I just want to know if this will still be resolved or the expected result will be considered as invalid? I also wonder why should this be considered as browser issue? Any thoughts on this? Thanks.

**Comment by egmsantos** [comment]
Issue #606 solved, but a new issue found:

Steps to replicate:
1. Open 2 new tabs.
2. On the first tab, open the active bookings list.
3. On the second tab, open the dispatch plan list.
4. Click the set vendor icon of the selected booking on the dispatch plan list.
5. Click the first tab.
6. Edit the selected booking from the second tab and delete its item (archive).
7. Click the second tab; click the set vendor icon of the recently deleted item.

Bug: You can still set/edit vendor even the record is deleted (archived), changing the shipment monitoring status from "CANCELLED" to "ON GOING".

**Comment by barbacenasmc** [comment]
This will be added to the list of known bugs for version 1 terminal report.
