### ISSUE TITLE
Page Proceeds to Log In Module when the User Navigates to the Next Page of Dispatch Plan List

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#607]
**Steps to replicate**
1. Navigate to Dispatch Plan list.
2. Click the Next/ Last Page.

**Actual Result**
The page proceeds to the login module.

**Expected Result**
The user should be able to access all the page of the dispatch plan list.

**Comment by emarino0411** [comment]
Fixed

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
