### ISSUE TITLE
Regular Customer can Access the Freight Plan List and Dispatch Plan List.

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#608]
**Steps to replicate**
1. Navigate to freight plan list.
2. Select a booking and click the set vessel schedule icon.
3. Once the page proceeds to freight plan: container, click the set schedule icon on a selected item.
4. Open a new tab (Page proceeds to login module <unable to cache data of the logged in user>)
5. Log in as regular customer.
6. Click the first tab, assign the item on a preferred vessel schedule and click Save.

**Actual Result**
The booking is now on Planning 2 Status.
- RC clicks the "Back to Freight Plan: Orders" button.
   - The RC can now access the freight plan list.
- type in the direct URL of dispatch plan list (http://localhost/freightbit/operations/viewInlandFreightList)
   - The RC can now access the dispatch plan list.

![10 1](https://cloud.githubusercontent.com/assets/9795882/7831733/17b8649a-048c-11e5-8fab-c62efbed4a81.png)
![10 2](https://cloud.githubusercontent.com/assets/9795882/7831734/17bc3930-048c-11e5-92ca-59ce8ba5b8d6.png)
![10 3](https://cloud.githubusercontent.com/assets/9795882/7831736/1b30de9a-048c-11e5-92c2-7970379cf64a.png)

**Expected Result**
It should display a page for "Hi, <regular customer> you do not have permission to access this page!"

**Comment by knarceo** [comment]
Fixed on next push.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
