### ISSUE TITLE
Unresponsive Design for Viewing Information of Booking.

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#609]
**Steps to replicate**
1.Navigate to Active Bookings.
2. Select a booking and click its view information icon.
3. Resize the browser into different dimensions.

**Actual Result**
- 1212 x 730
   - Customer information label has been wrapped to its cell.
   - Gridlines for booking information under booking number had exceeded its frame.
- 1100 x 730
   - Data inside the first frame under booking number had exceeded its frame dimension.

![12 1](https://cloud.githubusercontent.com/assets/9795882/7832069/b41d4038-048e-11e5-9804-3be861cd0fb2.png)
![12 2](https://cloud.githubusercontent.com/assets/9795882/7832070/b4beb1de-048e-11e5-8035-182ed95218d0.png)

**Expected Result**
Page content should be responsive.

**Comment by emarino0411** [comment]
Fixed

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
