### ISSUE TITLE
On-going Bookings List was Placed in Dashboard of CRD User.

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#610]
**Steps to replicate**
1. Log in as CRD
2. Observe the Dashboard

**Actual Result**
- On-going bookings list was placed in dashboard module.
- Click the set status icon indicated from table of on-going booking list displayed on dashboard.
   - Html page was displayed.

![3](https://cloud.githubusercontent.com/assets/9795882/7832199/c350b05c-048f-11e5-927c-22bb9beed342.png)
![4](https://cloud.githubusercontent.com/assets/9795882/7832200/c465b622-048f-11e5-951c-380fcbdcc656.png)

**Expected Result**
- On-going bookings list should not be indicated in dashboard module.

**Comment by emarino0411** [comment]
Not a bug.
