### ISSUE TITLE
Missing Elements in Shipment Monitoring Module of CRD User.

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#611]
**Steps to replicate**
1. Log in as CRD.
2. Navigate to Shipment Monitoring.
3. Select an On-going booking and click its update status icon.
4. Observe the shipment monitoring module.

**Actual Result**
The following were missing:
- Check boxes button for selecting an item.
- Column for Action
- Set Status button.

![5](https://cloud.githubusercontent.com/assets/9795882/7832280/60d8c1a2-0490-11e5-96f6-214defec4b0b.png)
![5 1](https://cloud.githubusercontent.com/assets/9795882/7832281/62613446-0490-11e5-8fab-9c1d2ef0847f.png)

**Expected Result**
These elements should be present in the Shipment Monitoring module of CRD User

**Comment by emarino0411** [comment]
Not a bug. CRD users has no right to edit / update bookings. However, they are not allowed to set service complete.

**Comment by barbacenasmc** [comment]
Hi, may I just clarify, CRD users are not allowed to set service complete?

**Comment by barbacenasmc** [comment]
Ser service complete button should still be available for the CRD user. For re-testing.

**Comment by barbacenasmc** [comment]
Set service complete button was now available again for the CRD user. Issue will now be closed
