### ISSUE TITLE
Setting Vessel Schedule for One Item Changed the Status of all Items.

### ISSUE THREAD

**Issue by Leirum** [johnpelquingua/freightbit-logistics#612]
**Steps to replicate**
1. Log in as admin.
2. Create new booking and add two containers.
3. Navigate to Freight plan and set vessel schedule for one item.

**Actual Result**
All items had changed into a planning 2 Status.

![13](https://cloud.githubusercontent.com/assets/9795882/7832503/2d88e244-0492-11e5-8542-3e37655f4ca1.png)

**Expected Result**
The only selected item that has set a schedule should only undergo the planning 2 status

**Comment by emarino0411** [comment]
Not a bug. Its a feature.

**Comment by barbacenasmc** [comment]
I think this is an issue based on its expected behavior before. Or else there should be no more checkboxes for multiple selection.

**Comment by JMXPSX** [comment]
This was a UI design flaw. It was proposed before to have multiple vessel schedules per booking but it was too complicated therefore this workaround was done instead,

Improvement on the UI will be addressed on version 2

**Comment by barbacenasmc** [comment]
Alright, this is noted. I will add this to label called "For version 2"

**Comment by JMXPSX** [comment]
One Vessel Schedule per booking is the current workaround for the proposed multiple Vessel Schedule per booking. Database design, Reference ID had become an issue when handling multiple schedules and creates more complications/inconsistencies in a booking therefore this was the last option to be implemented.

Improvement with the feature will be further discussed when planning for version 2 starts to roll out.

**Comment by egmsantos** [comment]
Issue fixed and verified. For Closure.

**Comment by egmsantos** [comment]
![eios_626](https://cloud.githubusercontent.com/assets/12589800/9127692/ec253518-3cf0-11e5-81d4-e54763f3e169.png)
