### ISSUE TITLE
Cancel Booking: A booking has to be cancelled twice before it changes its status

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#613]
Steps to replicate:

1. Navigate to the list of booking.
2. Click cancel icon corresponding to an existing approved booking.
3. Click "Yes" to confirm.

Actual result: The status of the booking remains approved. User has to repeat the process before it could finally becomes cancelled.

Expected result: A booking should be cancelled once.

![image](https://cloud.githubusercontent.com/assets/7791554/7874555/a1a3bcba-05e3-11e5-8ebc-8ac8bda81145.png)

![image](https://cloud.githubusercontent.com/assets/7791554/7874562/c4259fd8-05e3-11e5-822f-d58c5e3d9f67.png)

**Comment by emarino0411** [comment]
fixed

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
