### ISSUE TITLE
Report generated date is incorrect and incremented by 8 to 10 minutes every generation and decreases at some point

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#615]
Steps to replicate:
1. Navigate to reports.
2. Generate any type of report.
3. Observe the report generated date at the bottom of the page.
4. Close the window.
5. Repeat the process for 5 to 10 times.

Actual result: Report generated date is incorrect and incremented by 8 to 10 minutes every generation and decreases at some point

Expected result: Report generated date should display the current time and date.
![screenshot-11](https://cloud.githubusercontent.com/assets/7791554/7875296/c35a5ba2-05ed-11e5-9eb8-e5a07190826b.png)
![screenshot-12](https://cloud.githubusercontent.com/assets/7791554/7875297/c35c2da6-05ed-11e5-836c-cb0bfb912bff.png)
![screenshot-13](https://cloud.githubusercontent.com/assets/7791554/7875287/c283a878-05ed-11e5-9fe7-63502a47cc5c.png)
![screenshot-14](https://cloud.githubusercontent.com/assets/7791554/7875288/c2868ca0-05ed-11e5-930c-cd1f8893eb51.png)
![screenshot-15](https://cloud.githubusercontent.com/assets/7791554/7875289/c28a6fd2-05ed-11e5-9f98-1479104db419.png)
![screenshot-16](https://cloud.githubusercontent.com/assets/7791554/7875290/c29b329a-05ed-11e5-9999-29ad705a3629.png)
![screenshot-17](https://cloud.githubusercontent.com/assets/7791554/7875291/c29e00a6-05ed-11e5-8635-c60d185d934c.png)
![screenshot-18](https://cloud.githubusercontent.com/assets/7791554/7875293/c2a6402c-05ed-11e5-8d44-e8fb00eb4ab5.png)
![screenshot-19](https://cloud.githubusercontent.com/assets/7791554/7875292/c2a11d40-05ed-11e5-8e1d-fe81438810f5.png)
![screenshot-20](https://cloud.githubusercontent.com/assets/7791554/7875298/c38046fa-05ed-11e5-9cbe-70f6cfd4160a.png)
![screenshot-21](https://cloud.githubusercontent.com/assets/7791554/7875299/c39d1410-05ed-11e5-88e1-a1769aa18e68.png)
![screenshot-22](https://cloud.githubusercontent.com/assets/7791554/7875294/c2c9436a-05ed-11e5-8f88-efd57cb199f8.png)

**Comment by emarino0411** [comment]
Fixed

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
