### ISSUE TITLE
CSR Total No. of Bookings: There are discrepancies between the service req. total and overall total of bookings per customer

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#617]
Steps to replicate:

1. Generate a Total No. of Bookings for Customer Relations.
2. For date range, use Jan.1 to May 29.

Actual result: There are discrepancies between the service req. total and overall total of bookings per customer
Expected result: The overall total of bookings per customer should be equal to the sum of all count per service requirement.

![image](https://cloud.githubusercontent.com/assets/7791554/7877332/40dea448-060c-11e5-861a-658e19802a99.png)

**Comment by emarino0411** [comment]
Fixed

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
