### ISSUE TITLE
Freight Planning: Error page was displayed when tried to filter the list

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#618]
Steps to replicate:
1. Navigate to the freight planning page.
2. Select "Manila" on the filter by origin.
3. Select "Tacloban" on the filter by destination.
4. Click "Filter" button.

Actual result: Error page was displayed.

Expected result: The list of bookings should be filtered according to the origin and destination selected.

![screenshot-26](https://cloud.githubusercontent.com/assets/7791554/7877679/c7cc5fe6-0610-11e5-9f76-43cfe61241eb.png)
![screenshot-27](https://cloud.githubusercontent.com/assets/7791554/7877680/c7d22fca-0610-11e5-8a30-3b6478bab981.png)

**Comment by emarino0411** [comment]
Fixed

**Comment by barbacenasmc** [comment]
Issue can still be replicated.

**Comment by emarino0411** [comment]
already fixed in the latest version in git.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
