### ISSUE TITLE
Total Cancelled LC Bookings: Some values are not aligned

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#619]
Steps to replicate:

1. Generate a Total Cancelled LC Bookings.

Actual result: Some values are not aligned.
Expected result: All values should be properly aligned.
![screenshot-30](https://cloud.githubusercontent.com/assets/7791554/7878655/606010ea-061b-11e5-9be1-f3fdad10414f.png)

**Comment by emarino0411** [comment]
Fixed

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
