### ISSUE TITLE
Freight Planning: There is a "Hide Me" column on LCL tab

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#620]
Steps to replicate:

1. Go to freight planning page.
2. Go to LCL tab.
3. Scroll to the rightmost part of the list.

Actual result: There is a "Hide Me" column.
Expected result: "Hide Me" column should not display.

**Comment by JMXPSX** [comment]
Refrain from the using adminUser account. Kindly create a new admin account then logout of adminUser. Login using the new admin account. this error should not occur.

**Comment by barbacenasmc** [comment]
Issue can no longer be replicated on admin account.
