### ISSUE TITLE
Total Items per LCL bookings enlists all customer items even if they are not included in a booking

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#621]
Steps to replicate:

1. Create an LCL booking for a customer that has more than 1 items . (Pllease check the customer module)
2. Add only 1 of its item to its booking.
3. Approve the booking.
4. Go to reports and generate a new Total Items per LCL bookings (under LCL Operation).
5. Look for the entries associated with the booking number of the recently added booking.

Actual result: All other items were displayed on the list.
Expected result: Only the item included in the booking should be displayed on the list.
![image](https://cloud.githubusercontent.com/assets/7791554/7905385/4fd913da-084a-11e5-8da3-d9780b020576.png)

![image](https://cloud.githubusercontent.com/assets/7791554/7905387/5485d454-084a-11e5-8736-060a1fe1d205.png)

![image](https://cloud.githubusercontent.com/assets/7791554/7905390/5fe83a80-084a-11e5-9be4-9e6e8f9a037e.png)

**Comment by JMXPSX** [comment]
The reason for this was because the item Batteries do have two different Item Code under the same customer account: BATT and BAT respectively. That is why they were listed as two rows having the same item name. The report is separating items for every unique item code not item names.

**Comment by barbacenasmc** [comment]
Yup, that's correct but let me clarify the real issue here:
-Booking has 1 customer item only (let's say SMC-0675)
-But report displayed ALL the customer items under the booking no. SMC-0675
Expected result: 
-The report should only show 1 customer item under booking SMC-0675 because this is the only item used in the booking.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
