### ISSUE TITLE
Back button was displayed as link after successful password change

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#622]
Steps to replicate:

1. Login as admin.
2. Go to the list of users.
3. Edit an existing user account.
4. Change the user's password.

Actual result: Back button was displayed as link 
Expected result: It should display a button instead.
![screenshot-48](https://cloud.githubusercontent.com/assets/7791554/7998146/ecb1b1d0-0b6a-11e5-943f-5bc6b7dabd7d.png)

**Comment by egmsantos** [comment]
Bug fixed on next push; Changed program flow; this time, when the user changed his password, this will now redirect to "Edit User Profile" page instead.

**Comment by barbacenasmc** [comment]
Buf fixed and was verified.
