### ISSUE TITLE
Dispatch Planning: A prompt with unknown value was displayed after clicking save when setting vendor

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#623]
Test Data:
-New booking, FCL, Door to Door, with multiple containers
-Freight planning is already finished

Steps to replicate:
1. Navigate to dispatch planning.
2. Open the booking.
3. Check 2 items and click Set Vendor button.
4. Fill-out the dispatch plan origin form. Select a date 1 day ahead of the current date.
5. Click Save.

Actual result: A prompt saying "Date must be no later than NaN-NaN-NaN
Do you still wish to proceed?"

Expected result: The prompt should not display at all because the date selected is within the range of the pick-up and delivery date. Should proceed to " Confirm Dispatch Plan Details" page.

Note: Issue cannot be replicated when setting vendor for single item only. (When user clicks the set vendor icon corresponding to 1 item.)

![screenshot-49](https://cloud.githubusercontent.com/assets/7791554/7998708/d4a5c3d0-0b72-11e5-99ed-685dd1c95d13.png)

**Comment by egmsantos** [comment]
Issue fixed.
![eios_626](https://cloud.githubusercontent.com/assets/12589800/9107713/29c66f4e-3c5c-11e5-89f2-22f2923ed015.png)

**Comment by egmsantos** [comment]
Issue fixed.
![eios_626](https://cloud.githubusercontent.com/assets/12589800/9107781/92dcbf88-3c5c-11e5-8fee-a7e6a8bb5ae5.png)
