### ISSUE TITLE
Add Customer: Save button is not enabled even if required fields were filled-out

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#625]
Steps to replicate:

1. Navigate to add customer page.
2. Fill-out only the required fields.

Actual result: Save button is still disabled. (Try to fill-out the phone no., mobile and fax no. field, then that's the time when the Save button will enable)

Expected result: Save button should be enabled when all required fields were filled-out.

![image](https://cloud.githubusercontent.com/assets/7791554/8179280/3736cd7c-1448-11e5-9a97-fc8452767cd0.png)

**Comment by emarino0411** [comment]
Fixed

**Comment by egmsantos** [comment]
Issue fixed.

**Comment by egmsantos** [comment]
For closure.
