### ISSUE TITLE
CRD User cannot print Booking Request Form

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#626]
Steps to replicate:

1. Login as CRD user.
2. Go to active bookings list.
3. Click the print icon.

Actual result: No booking request form was generated.

Expected result: Booking request form should be generated.

![image](https://cloud.githubusercontent.com/assets/7791554/8566555/6b4ce8b2-2591-11e5-89ad-2daa2936aaf4.png)

Note: Administrator can generate BRF.

**Comment by egmsantos** [comment]
Booking Request Form is generated.
Date/Time: Aug 06 2015/15:06
![eios_626](https://cloud.githubusercontent.com/assets/12589800/9105738/2cf32d2e-3c4d-11e5-8304-55e68df1b7c8.png)

**Comment by egmsantos** [comment]
Fixed #626
